import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import ts from 'typescript';

// Compile the actual pure domain and storage adapter; no duplicated business logic.
const moduleCache = new Map();
async function sourceModule(name) {
  if (moduleCache.has(name)) return moduleCache.get(name);
  let source;try { source = await readFile(new URL(`../app/${name}.ts`, import.meta.url), 'utf8'); } catch { source = await readFile(new URL(`../app/${name}.tsx`, import.meta.url), 'utf8'); }
  const local = [...source.matchAll(/from ['"]\.\/([^'"]+)['"]/g)];
  for (const match of local) source = source.replaceAll(match[0], `from '${await sourceModule(match[1])}'`);
  let code = ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
  for (const match of [...code.matchAll(/from ["']([^"']+)["']/g)]) { if (!match[1].startsWith('data:') && !match[1].startsWith('node:')) code = code.replaceAll(match[0], `from '${import.meta.resolve(match[1])}'`); }
  const url = `data:text/javascript;base64,${Buffer.from(code).toString('base64')}`;
  moduleCache.set(name,url); return url;
}
const domain = await import(await sourceModule('operations-model'));
const access = await import(await sourceModule('access-control'));
const {emptyOperations,applyOperation,scopedOperations,visibleRecords,calculateDeadline,defaultCalendar,delegationAllows} = domain;
const alice={id:'alice',fullName:'Gestora A',department:'Setor A',role:'Secretária',principal:'admin',manager:true,executive:false};
const bob={id:'bob',fullName:'Gestor B',department:'Setor B',role:'Secretário',principal:'admin',manager:true,executive:false};
const aide={id:'aide',fullName:'Assistente A',department:'Setor A',role:'Funcionário',principal:'admin',manager:false,executive:false,settings:access.createDefaultPermissionSettings()};
const records=[{kind:'ticket',id:'ticket-a',title:'Reparo A',department:'Setor A',status:'Recebido',ownerId:'alice',dueAt:'2026-09-08T20:00:00Z'},{kind:'ticket',id:'ticket-b',title:'Reparo B',department:'Setor B',status:'Recebido'}, {kind:'document',id:'doc-a',title:'Pedido A',department:'Setor A'}, {kind:'document',id:'doc-b',title:'Pedido B',department:'Setor B'}];
const context=(actor=alice,now='2026-09-07T12:00:00Z')=>({actor,department:actor.department,users:[alice,bob,aide],departments:['Setor A','Setor B'],records,now});
let seq=0;
const command=(type,data,id=`command-${++seq}`)=>({type,data,id});
const act=(s,type,data,c=context())=>applyOperation(s,command(type,data),c);
function serviceState(stages=[{name:'Análise',userId:'alice',requiredDocuments:[]}]) {return act(emptyOperations(),'service.save',{title:'Serviço com aprovação',days:2,businessDays:true,fields:[],requiredDocuments:[],stages});}
function requestState(stages){const s=serviceState(stages);return act(s,'request.create',{serviceId:s.services[0].id,values:{},documents:{}});}

test('history uses server actor/time and survives serialization with idempotent replay',()=>{const cmd=command('ticket.note',{ticketId:'ticket-a',text:'Vistoria registrada',actorName:'Forged',createdAt:'1900-01-01'});const s=applyOperation(emptyOperations(),cmd,context());const loaded=JSON.parse(JSON.stringify(s));assert.equal(loaded.tickets['ticket-a'].history[0].actorName,alice.fullName);assert.equal(loaded.tickets['ticket-a'].history[0].at,context().now);assert.equal(applyOperation(loaded,cmd,context()).revision,1);assert.equal(loaded.tickets['ticket-a'].history.length,1);});
test('cross-sector mutations and executive read-only mutations are rejected',()=>{assert.throws(()=>act(emptyOperations(),'ticket.note',{ticketId:'ticket-b',text:'blocked'}),/acesso/);const executive={...alice,role:'Prefeito',executive:true};assert.throws(()=>act(emptyOperations(),'resource.save',{name:'Sala',kind:'Sala',ownerId:'bob'}, {...context(executive),department:'Setor B'}),/não pode/);});
test('transfer accepts once, changes visible membership, and keeps internal notes in origin',()=>{let s=act(emptyOperations(),'ticket.note',{ticketId:'ticket-a',text:'Nota privada A',internal:true});s=act(s,'ticket.forward',{ticketId:'ticket-a',to:'Setor B',reason:'Análise no destino'});const id=s.transfers[0].id;assert.equal(visibleRecords(s,context()).filter(x=>x.kind==='ticket').length,1);s=act(s,'transfer.respond',{id,decision:'accept',assigneeId:'bob',dueAt:'2026-09-09T20:00:00Z'},context(bob));assert.equal(visibleRecords(s,context()).filter(x=>x.kind==='ticket').length,0);assert.equal(visibleRecords(s,context(bob)).filter(x=>x.kind==='ticket').length,2);assert.equal(scopedOperations(s,context(bob)).tickets['ticket-a'].history.some(h=>h.internal),false);assert.equal(scopedOperations(s,context()).transfers[0].status,'Recebido');assert.throws(()=>act(s,'transfer.respond',{id,decision:'accept',assigneeId:'bob',dueAt:'2026-09-10T20:00:00Z'},context(bob)),/já confirmado/);});
test('transfer requires reason and rejects unknown transitions',()=>{assert.throws(()=>act(emptyOperations(),'ticket.forward',{ticketId:'ticket-a',to:'Setor B',reason:''}),/motivo/);let s=act(emptyOperations(),'ticket.forward',{ticketId:'ticket-a',to:'Setor B',reason:'Analisar pedido'});assert.throws(()=>act(s,'transfer.respond',{id:s.transfers[0].id,decision:'anything'},context(bob)),/inválida/);s=act(s,'transfer.respond',{id:s.transfers[0].id,decision:'complement',response:'Informe o endereço completo'},context(bob));s=act(s,'transfer.supplement',{id:s.transfers[0].id,response:'Endereço complementar informado'});assert.equal(s.transfers[0].status,'Enviado');});
test('checklist rejects stale replacements instead of losing another edit',()=>{let s=act(emptyOperations(),'ticket.checklist',{ticketId:'ticket-a',expectedHistoryLength:0,items:[{id:'one',label:'Conferir',done:false}]});s=act(s,'ticket.note',{ticketId:'ticket-a',text:'Atualização concorrente'});assert.throws(()=>act(s,'ticket.checklist',{ticketId:'ticket-a',expectedHistoryLength:1,items:[]}),/outra atualização/);assert.equal(s.tickets['ticket-a'].checklist.length,1);});
test('justified pause extends deadline by elapsed pause and prevents duplicate pause',()=>{let s=act(emptyOperations(),'ticket.pause',{ticketId:'ticket-a',reason:'Aguardando equipamento'});assert.throws(()=>act(s,'ticket.pause',{ticketId:'ticket-a',reason:'Outra pausa'}),/já está/);s=act(s,'ticket.resume',{ticketId:'ticket-a'},context(alice,'2026-09-08T12:00:00Z'));assert.equal(s.tickets['ticket-a'].dueDate,'2026-09-09T20:00:00.000Z');assert.equal(s.tickets['ticket-a'].pausedMs,86400000);});
test('business deadlines skip weekends and configured holidays',()=>{const cal=defaultCalendar('Setor A');cal.holidays=['2026-09-07'];assert.equal(calculateDeadline('2026-09-04T12:00:00Z',1,true,cal),'2026-09-08T20:00:00.000Z');assert.equal(calculateDeadline('2026-09-04T12:00:00Z',1,false,cal),'2026-09-05T20:00:00.000Z');assert.equal(calculateDeadline('2026-09-04T22:00:00Z',0,true,cal),'2026-09-08T20:00:00.000Z');});
test('calendar rejects fractional weekdays, invalid times and impossible dates',()=>{for(const change of [{weekdays:[1.5]},{starts:'08:99'},{ends:'25:00'},{holidays:['2026-02-30']},{holidays:['2026-99-99']}])assert.throws(()=>act(emptyOperations(),'calendar.save',{weekdays:[1,2,3,4,5],starts:'08:00',ends:'17:00',holidays:[],...change}));});
test('shared filters validate shape and do not share private views',()=>{const preferences={viewMode:'table',savedView:'Todos',query:'urgente',priority:'Todas',status:'Todos',columns:['protocol','status']};let s=act(emptyOperations(),'filter.save',{name:'Minha busca',shared:false,preferences});assert.equal(scopedOperations(s,context(aide)).filters.length,0);assert.throws(()=>act(s,'filter.save',{name:'Quebrado',shared:true,preferences:{...preferences,query:{},columns:null}}),/inválida/);s=act(s,'filter.save',{name:'Busca compartilhada',shared:true,preferences});assert.equal(scopedOperations(s,context(aide)).filters.length,1);});
test('a profile without module rights receives no workflow, reservation or filter data',()=>{const s=emptyOperations();s.resources=[{id:'r',department:'Setor A'}];s.reservations=[{id:'b',department:'Setor A',purpose:'private'}];s.filters=[{id:'f',department:'Setor A',shared:true}];s.services=[{id:'s',department:'Setor A'}];const actor={...aide,settings:access.createDefaultPermissionSettings()};actor.settings.assignments.aide='consulta';actor.settings.profiles.consulta.permissions.Chamados.view=false;const scoped=scopedOperations(s,context(actor));assert.equal(scoped.resources.length+scoped.reservations.length+scoped.filters.length+scoped.services.length,0);});
test('request keeps service and calendar version snapshots after configuration edits',()=>{let s=requestState();const r=s.requests[0],oldTitle=r.definition.title,oldDue=r.dueAt;s=act(s,'service.save',{id:r.serviceId,title:'Outro serviço',days:50,fields:[],stages:[],requiredDocuments:[]});s=act(s,'calendar.save',{weekdays:[2],starts:'09:00',ends:'10:00',holidays:[]});assert.equal(s.requests[0].definition.title,oldTitle);assert.equal(s.requests[0].dueAt,oldDue);});
test('same approver cannot accidentally advance two consecutive stages from stale tabs',()=>{let s=requestState([{name:'Etapa 1',userId:'alice',requiredDocuments:[]},{name:'Etapa 2',userId:'alice',requiredDocuments:[]}]);const id=s.requests[0].id,stage=s.requests[0].stages[0].id;s=act(s,'request.decide',{id,expectedStageId:stage,decision:'approve',note:'Primeira conferência'});assert.equal(s.requests[0].stage,1);assert.throws(()=>act(s,'request.decide',{id,expectedStageId:stage,decision:'approve',note:'Repetida'}),/etapa foi atualizada/);});
test('approval requires evidence and prevents linking a document from another sector',()=>{let s=requestState([{name:'Análise',userId:'alice',requiredDocuments:['Parecer']}]);const r=s.requests[0];assert.throws(()=>act(s,'request.decide',{id:r.id,expectedStageId:r.stages[0].id,decision:'approve',note:'Conferido'}),/Documento pendente/);assert.throws(()=>act(s,'request.document',{id:r.id,label:'Parecer',documentId:'doc-b'}),/acesso/);s=act(s,'request.document',{id:r.id,label:'Parecer',documentId:'doc-a'});s=act(s,'request.decide',{id:r.id,expectedStageId:r.stages[0].id,decision:'approve',note:'Conferido'});assert.equal(s.requests[0].status,'Aprovado');});
test('conditional approval only includes applicable stages',()=>{let s=act(emptyOperations(),'service.save',{title:'Condicional',days:2,fields:[{id:'type',label:'Tipo',type:'text',required:true}],stages:[{name:'Urgente',userId:'alice',conditionField:'type',conditionValue:'Urgente',requiredDocuments:[]}],requiredDocuments:[]});s=act(s,'request.create',{serviceId:s.services[0].id,values:{type:'Normal'},documents:{}});assert.equal(s.requests[0].stages.length,0);assert.equal(s.requests[0].status,'Aprovado');});
test('delegation expires at end boundary, respects duty and revocation',()=>{let s=act(emptyOperations(),'delegation.save',{ownerId:'alice',substituteId:'aide',startsAt:'2026-09-07T12:00:00Z',endsAt:'2026-09-08T12:00:00Z',duties:['approvals']});assert.equal(delegationAllows(s,aide,'alice','approvals','2026-09-07T12:00:00Z'),true);assert.equal(delegationAllows(s,aide,'alice','reservations','2026-09-07T12:00:00Z'),false);assert.equal(delegationAllows(s,aide,'alice','approvals','2026-09-08T12:00:00Z'),false);s=act(s,'delegation.revoke',{id:s.delegations[0].id});assert.equal(delegationAllows(s,aide,'alice','approvals','2026-09-07T13:00:00Z'),false);});
test('specifically assigned employee can approve without general edit privileges',()=>{let s=requestState([{name:'Revisão',userId:'aide',requiredDocuments:[]}]);const r=s.requests[0];s=act(s,'request.decide',{id:r.id,expectedStageId:r.stages[0].id,decision:'approve',note:'Conferido pela equipe'},context(aide));assert.equal(s.requests[0].status,'Aprovado');});
test('reservations reject overlaps while accepting adjacent intervals and cancellation frees time',()=>{let s=act(emptyOperations(),'resource.save',{name:'Sala A',kind:'Sala',ownerId:'alice',approval:false});const resourceId=s.resources[0].id;const booking={resourceId,startsAt:'2026-09-08T12:00:00Z',endsAt:'2026-09-08T13:00:00Z',purpose:'Reunião interna'};s=act(s,'reservation.create',booking);assert.throws(()=>act(s,'reservation.create',{...booking,startsAt:'2026-09-08T12:30:00Z'}),/já está reservado/);s=act(s,'reservation.create',{...booking,startsAt:'2026-09-08T13:00:00Z',endsAt:'2026-09-08T14:00:00Z'});const first=s.reservations.find(r=>r.startsAt==='2026-09-08T12:00:00.000Z');s=act(s,'reservation.decide',{id:first.id,decision:'cancel'});s=act(s,'reservation.create',booking);assert.equal(s.reservations.filter(r=>r.status==='Aprovada').length,2);});
test('related records require both endpoints and prevent reversed duplicates',()=>{let s=act(emptyOperations(),'link.create',{from:{kind:'ticket',id:'ticket-a'},to:{kind:'document',id:'doc-a'}});assert.throws(()=>act(s,'link.create',{from:{kind:'ticket',id:'ticket-a'},to:{kind:'document',id:'doc-b'}}),/acesso/);assert.throws(()=>act(s,'link.create',{from:{kind:'document',id:'doc-a'},to:{kind:'ticket',id:'ticket-a'}}),/já vinculados/);assert.equal(scopedOperations(s,context(bob)).links.length,0);});

test('immutable journal resolves concurrent reservations and lost upload responses',async()=>{
  const objects=new Map();let loseResponse=false;const previousFetch=globalThis.fetch;
  const before={url:process.env.SUPABASE_URL,secret:process.env.SUPABASE_SECRET_KEY};
  process.env.SUPABASE_URL='https://isolated-storage.invalid';process.env.SUPABASE_SECRET_KEY='test-key';
  globalThis.fetch=async(url,options={})=>{const path=new URL(String(url)).pathname;const respond=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json'}});
    if(path.includes('/bucket/'))return respond({id:'prefeitura-conecta-data'});
    if(path.includes('/object/list/')){const q=JSON.parse(options.body),prefix=q.prefix+'/';return respond([...objects.keys()].filter(k=>k.startsWith(prefix)).sort().reverse().slice(0,1).map(k=>({name:k.slice(prefix.length)})));}
    const key=decodeURIComponent(path.split('/object/prefeitura-conecta-data/')[1]);
    if(options.method==='POST'){if(objects.has(key)&&!options.headers['x-upsert'])return respond({message:'Asset Already Exists'},400);objects.set(key,JSON.parse(options.body));if(loseResponse){loseResponse=false;throw new Error('simulated lost response');}return respond({ok:true});}
    return objects.has(key)?respond(objects.get(key)):respond({message:'not found'},404);
  };
  try{const server=await import(await sourceModule('operations-server'));let s=await server.commitOperation(command('resource.save',{name:'Sala única',kind:'Sala',ownerId:'alice',approval:false}),context());const booking={resourceId:s.resources[0].id,startsAt:'2026-09-08T12:00:00Z',endsAt:'2026-09-08T13:00:00Z',purpose:'Teste simultâneo'};
    const results=await Promise.allSettled([server.commitOperation(command('reservation.create',booking),context()),server.commitOperation(command('reservation.create',booking),context())]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await server.readOperations()).reservations.length,1);
    loseResponse=true;const note=command('ticket.note',{ticketId:'ticket-a',text:'Resposta perdida'});await server.commitOperation(note,context());await server.commitOperation(note,context());s=await server.readOperations();assert.equal(s.tickets['ticket-a'].history.length,1);assert.deepEqual([...objects.keys()].map(k=>Number(k.match(/(\d+)\.json$/)?.[1])).sort(),[1,2,3]);
  }finally{globalThis.fetch=previousFetch;if(before.url===undefined)delete process.env.SUPABASE_URL;else process.env.SUPABASE_URL=before.url;if(before.secret===undefined)delete process.env.SUPABASE_SECRET_KEY;else process.env.SUPABASE_SECRET_KEY=before.secret;}
});


test('all operational tabs and populated ticket details render from actual components',async()=>{
  const React=await import('react'),{renderToStaticMarkup}=await import('react-dom/server');
  const {OperationsContext}=await import(await sourceModule('operations-context'));
  const {OperationsHub}=await import(await sourceModule('operations-hub'));
  const {OperationalTicketDetail}=await import(await sourceModule('operations-ui'));
  const value={state:requestState(),records,users:[alice,aide],departments:['Setor A','Setor B'],manager:true,readOnly:false,actorId:'alice',scopeDepartment:'Setor A',department:'Setor A',busy:false,ready:true,error:'',refresh:async()=>{},act:async()=>true,openRecord:()=>{}};
  for(const initialTab of ['Meu dia','Recebimentos','Serviços','Aprovações','Reservas','Configurações']){
    const html=renderToStaticMarkup(React.createElement(OperationsContext.Provider,{value},React.createElement(OperationsHub,{initialTab})));
    assert.match(html,/role="tabpanel"/);assert.ok(html.includes(initialTab));assert.doesNotMatch(html,/NaN|undefined/);
  }
  const html=renderToStaticMarkup(React.createElement(OperationsContext.Provider,{value},React.createElement(OperationalTicketDetail,{ticket:{id:'ticket-a',protocol:'CH-001',title:'Solicitação de manutenção com título extenso',description:'Descrição do pedido',department:'Setor A',requester:'Equipe',status:'Recebido',priority:'Alta',dueDate:'2026-09-08T20:00:00Z',createdAt:'2026-09-07T12:00:00Z'},onClose:()=>{}})));
  assert.match(html,/Histórico do atendimento/);assert.match(html,/Checklist de execução/);assert.match(html,/Registros relacionados/);assert.doesNotMatch(html,/NaN|undefined/);
});
