import { hasValidSession } from "../../auth-session";
import { analyzeMunicipalDemand, createTicketAiDraft, generateMunicipalDraft, generateMunicipalWeeklyReport, hasMunicipalAiConfig, municipalAiProviderInfo, runMunicipalCopilot, summarizeMunicipalText } from "../../municipal-ai.server";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
function clean(value: unknown, max = 12000) { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
function stringArray(value: unknown, max = 60) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean).slice(0, max) : []; }
export async function GET(request: Request) { if (!hasValidSession(request)) return Response.json({ error: "Sessão expirada." }, { status: 401 }); return Response.json({ ok: true, ...municipalAiProviderInfo() }, { headers: { "cache-control": "no-store" } }); }
export async function POST(request: Request) { if (!hasValidSession(request)) return Response.json({ error: "Sessão expirada." }, { status: 401 }); try { const body = await request.json() as Record<string, unknown>; const operation = clean(body.operation, 50);
  if (operation === "analyze") { const subject = clean(body.subject, 300), message = clean(body.message, 12000), neighborhood = clean(body.neighborhood, 140); if (!subject && !message) return Response.json({ error: "Informe um relato para análise." }, { status: 400 }); return Response.json({ ok: true, configured: hasMunicipalAiConfig(), provider: municipalAiProviderInfo(), analysis: await analyzeMunicipalDemand(subject, message, neighborhood) }); }
  if (operation === "summarize") { const text = clean(body.text, 16000); if (!text) return Response.json({ error: "Informe o texto para resumir." }, { status: 400 }); const result = await summarizeMunicipalText(text); return Response.json({ ok: true, configured: hasMunicipalAiConfig(), provider: municipalAiProviderInfo(), ...result }); }
  if (operation === "weekly_report") { const result = await generateMunicipalWeeklyReport(body.data ?? {}); return Response.json({ ok: true, configured: hasMunicipalAiConfig(), provider: municipalAiProviderInfo(), ...result }); }
  if (operation === "copilot") { const prompt = clean(body.prompt, 8000), mode = clean(body.mode, 40) || "assistant"; if (!prompt) return Response.json({ error: "Escreva o que deseja pedir ao Copiloto Municipal." }, { status: 400 }); const result = await runMunicipalCopilot({ prompt, mode, context: body.context ?? {} }); return Response.json({ ok: true, configured: hasMunicipalAiConfig(), provider: municipalAiProviderInfo(), result }); }
  if (operation === "ticket_assist") { const title = clean(body.title, 300), description = clean(body.description, 12000); if (!title && !description) return Response.json({ error: "Informe um título ou uma descrição para a IA preparar o chamado." }, { status: 400 }); const result = await createTicketAiDraft({ title, description, neighborhood: clean(body.neighborhood, 140), departments: stringArray(body.departments) }); return Response.json({ ok: true, configured: hasMunicipalAiConfig(), provider: municipalAiProviderInfo(), result }); }
  if (operation === "draft") { const kind = clean(body.kind, 50) || "improve_message", text = clean(body.text, 12000); if (!text) return Response.json({ error: "Informe o texto que a IA deve trabalhar." }, { status: 400 }); const result = await generateMunicipalDraft({ kind, text, context: body.context ?? {} }); return Response.json({ ok: true, configured: hasMunicipalAiConfig(), provider: municipalAiProviderInfo(), ...result }); }
  return Response.json({ error: "Operação de IA inválida." }, { status: 400 });
} catch (error) { const message = error instanceof Error ? error.message : "Falha ao executar a análise inteligente."; const safeMessage = message.startsWith("GROQ_") ? "A Groq recusou ou não conseguiu concluir esta solicitação. Verifique a chave, o modelo e os limites da conta." : message; return Response.json({ error: safeMessage }, { status: 500 }); } }
