"use client";
import { CheckCircle2, Clock3, Crown, ExternalLink, Landmark, ShieldCheck, UserRoundCheck } from "./site-icons";
import { usePersistentState } from "./persistence";
type Notify=(message:string)=>void; type Agenda={id:string;time:string;title:string;context:string;status:"Confirmado"|"Em preparação"|"Concluído"}; type Decision={id:string;title:string;department:string;status:"Aguardando análise"|"Em análise"|"Aprovado";priority:"Alta"|"Normal"}; type Desk={agenda:Agenda[];decisions:Decision[]};
const LEADERS=[{initials:"RB",name:"Rodrigo Aguiar Dalla Bernardina",role:"Prefeito Municipal",scope:"Coordenação geral do Executivo, prioridades de governo, integração entre secretarias e acompanhamento das entregas municipais.",tags:["Visão executiva","Gestão municipal","Articulação intersetorial"],profileUrl:"https://www.varzeadapalma.mg.gov.br/portal/prefeito/1"},{initials:"JS",name:"Jaime de Souza",role:"Vice-Prefeito",scope:"Apoio à coordenação do Executivo, acompanhamento administrativo e integração das pautas estratégicas com as áreas de gestão.",tags:["Vice-Prefeitura","Administração","Acompanhamento estratégico"],profileUrl:"https://www.varzeadapalma.mg.gov.br/portal/prefeito/2"}] as const;
const INITIAL:Desk={agenda:[{id:"a1",time:"09:00",title:"Despacho de prioridades",context:"Gabinete e Secretaria de Governo",status:"Concluído"},{id:"a2",time:"11:30",title:"Acompanhamento de entregas",context:"Infraestrutura, Saúde e Educação",status:"Em preparação"},{id:"a3",time:"13:00",title:"Reunião de alinhamento executivo",context:"Secretariado municipal",status:"Confirmado"}],decisions:[{id:"d1",title:"Consolidar prioridades da semana",department:"Secretaria de Governo",status:"Em análise",priority:"Alta"},{id:"d2",title:"Validar agenda intersetorial",department:"Gabinete do Prefeito",status:"Aguardando análise",priority:"Normal"},{id:"d3",title:"Revisar entregas com risco de prazo",department:"Gestão municipal",status:"Aguardando análise",priority:"Alta"}]};
function tone(s:string){return s==="Concluído"||s==="Aprovado"?"success":s==="Em preparação"||s==="Em análise"?"warning":"info"}
export function ExecutiveLeadershipPanel({department,userRole,notify}:{department:string;userRole:string;notify:Notify}) {
  const show=department==="Gabinete do Prefeito"||/prefeito/i.test(userRole);
  const [desk,setDesk,saveStatus]=usePersistentState<Desk>("executive:leadership-desk:v1",INITIAL);
  if(!show)return null;
  const pending=desk.decisions.filter((item)=>item.status!=="Aprovado").length;
  function cycleDecision(id:string){setDesk((current)=>({...current,decisions:current.decisions.map((item)=>item.id!==id?item:{...item,status:item.status==="Aguardando análise"?"Em análise":item.status==="Em análise"?"Aprovado":"Aguardando análise"})}));notify("Situação da decisão executiva atualizada.")}
  function cycleAgenda(id:string){setDesk((current)=>({...current,agenda:current.agenda.map((item)=>item.id!==id?item:{...item,status:item.status==="Confirmado"?"Em preparação":item.status==="Em preparação"?"Concluído":"Confirmado"})}));notify("Agenda executiva atualizada.")}

  return <section className="executive-leadership-panel executive-leadership-v3">
    <header className="executive-leadership-header"><div className="executive-leadership-title"><span><Crown size={20}/></span><div><p className="eyebrow">GABINETE EXECUTIVO</p><h2>Prefeito e Vice-Prefeito</h2><p>Decisões, agenda e responsabilidades da chefia do Executivo em um único espaço.</p></div></div><div className="executive-leadership-summary"><span><strong>{pending}</strong><small>decisões abertas</small></span><i className={`sync-inline ${saveStatus}`}>{saveStatus==="salvando"?"Salvando…":saveStatus==="offline"?"Aguardando conexão":"Sincronizado"}</i></div></header>
    <div className="executive-leadership-body-v3">
      <div className="executive-profile-stack-v3">{LEADERS.map((leader,index)=><article className={`executive-profile-card ${index===0?"mayor":"vice"}`} key={leader.name}><div className="executive-profile-top"><span className="executive-profile-avatar">{leader.initials}</span><span className="executive-profile-office">{index===0?<Crown size={14}/>:<UserRoundCheck size={14}/>} {leader.role}</span></div><div className="executive-profile-copy"><h3>{leader.name}</h3><p>{leader.scope}</p></div><div className="executive-profile-tags">{leader.tags.map((tag)=><span key={tag}>{tag}</span>)}</div><a href={leader.profileUrl} target="_blank" rel="noreferrer">Perfil institucional <ExternalLink size={12}/></a></article>)}</div>
      <div className="executive-desk-stack-v3">
        <article className="panel executive-agenda-card"><header><span><Clock3 size={17}/></span><div><h3>Agenda executiva</h3><p>Compromissos e despachos em acompanhamento.</p></div></header><div>{desk.agenda.map((item)=><button key={item.id} onClick={()=>cycleAgenda(item.id)}><time>{item.time}</time><span><strong>{item.title}</strong><small>{item.context}</small></span><i className={tone(item.status)}>{item.status}</i></button>)}</div></article>
        <article className="panel executive-decision-card"><header><span><Landmark size={17}/></span><div><h3>Fila de decisões</h3><p>Pautas que exigem leitura, validação ou despacho.</p></div></header><div>{desk.decisions.map((item)=><button key={item.id} onClick={()=>cycleDecision(item.id)}><span className={`executive-decision-priority ${item.priority.toLowerCase()}`}>{item.priority}</span><span><strong>{item.title}</strong><small>{item.department}</small></span><i className={tone(item.status)}>{item.status}</i></button>)}</div><footer><ShieldCheck size={13}/><span>As mudanças ficam registradas no espaço executivo.</span><CheckCircle2 size={14}/></footer></article>
      </div>
    </div>
  </section>;
}
