"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, ArrowRight, BarChart3, Bot, BriefcaseBusiness, Building2, CalendarClock, Check, CheckCircle2,
  ChevronRight, CircleDot, ClipboardList, Clock3, Cloud, Database, FileCheck2, Gauge, HeartHandshake, History, Landmark,
  ListChecks, Map as MapIcon, MapPin, Network, Plus, RefreshCcw, Search, ServerCog, ShieldCheck, Sparkles, Star, Target, UsersRound,
  Wifi, WifiOff, Workflow, X,
} from "lucide-react";
import { loadPersistentValue, persistenceKey, usePersistentState } from "./persistence";
import { RealMunicipalMap, type RealMapPoint } from "./real-municipal-map";

type Notify = (message: string) => void;
type TicketInput = { id: string; protocol: string; title: string; description: string; department: string; status: string; priority: string; dueDate: string | null; neighborhood?: string; address?: string; latitude?: number | null; longitude?: number | null; requester: string };
type UserInput = { id: string; fullName: string; department: string; role: string; initials?: string };
type OfficeInput = { id: string; name: string; head: string; address: string; phone?: string; email?: string; category?: string };
type EventInput = { id: string; title: string; department: string; location: string; startsAt: string; endsAt?: string | null };
type IntegratedTab = "Central" | "Tarefas" | "Projetos e metas" | "Mapa e locais" | "Organograma" | "IA Municipal" | "Saúde do sistema";
export type WorkStatus = "A fazer" | "Em andamento" | "Aguardando" | "Concluído";
export type TaskPriority = "Baixa" | "Normal" | "Alta" | "Urgente";

type TaskComment = { id: string; author: string; text: string; createdAt: string };
export type IntegratedTask = {
  id: string; title: string; description: string; kind: "Tarefa" | "Solicitação interna" | "Vistoria"; requesterDepartment: string; department: string;
  assignee: string; priority: TaskPriority; status: WorkStatus; dueAt: string; slaHours: number; createdAt: string; updatedAt: string;
  tags: string[]; comments: TaskComment[]; history: Array<{ at: string; action: string }>;
};
export type Project = { id: string; title: string; department: string; owner: string; status: "Planejamento" | "Em execução" | "Em risco" | "Concluído"; progress: number; dueDate: string; stages: Array<{ name: string; done: boolean }> };
export type Goal = { id: string; title: string; department: string; current: number; target: number; unit: string; dueDate: string };
type PublicPlace = { id: string; name: string; type: string; department: string; neighborhood: string; address: string; status: string; lastMaintenance: string; history: string[]; latitude?: number | null; longitude?: number | null };

type HealthPayload = { checkedAt: string; services: Record<string, { ok: boolean; label: string; model?: string }> };
type AiAnalysis = { summary: string; category: string; suggestedDepartment: string; urgency: string; urgencyReason: string; tags: string[]; recommendedAction: string; source: string };

const WORK_COLUMNS: WorkStatus[] = ["A fazer", "Em andamento", "Aguardando", "Concluído"];
export const INITIAL_TASKS: IntegratedTask[] = [
  { id: "it-1", title: "Vistoriar iluminação da Rua São José", description: "Verificar três pontos informados pela comunidade e anexar evidências.", kind: "Vistoria", requesterDepartment: "Gabinete do Prefeito", department: "Secretaria de Infraestrutura e Transporte", assignee: "Equipe de iluminação", priority: "Alta", status: "Em andamento", dueAt: "2026-08-20T18:00:00.000Z", slaHours: 48, createdAt: "2026-08-18T12:00:00.000Z", updatedAt: "2026-08-18T15:00:00.000Z", tags: ["iluminação", "campo"], comments: [{ id: "c1", author: "Gabinete", text: "@Infraestrutura confirmar equipe responsável ainda hoje.", createdAt: "2026-08-18T13:00:00.000Z" }], history: [{ at: "2026-08-18T12:00:00.000Z", action: "Solicitação criada pelo Gabinete" }, { at: "2026-08-18T15:00:00.000Z", action: "Movida para Em andamento" }] },
  { id: "it-2", title: "Conferir disponibilidade de medicamentos", description: "Consolidar estoque das unidades e informar itens abaixo do mínimo.", kind: "Solicitação interna", requesterDepartment: "Gabinete do Prefeito", department: "Secretaria de Saúde", assignee: "Coordenação de Assistência Farmacêutica", priority: "Urgente", status: "A fazer", dueAt: "2026-08-19T15:00:00.000Z", slaHours: 24, createdAt: "2026-08-18T14:00:00.000Z", updatedAt: "2026-08-18T14:00:00.000Z", tags: ["saúde", "estoque"], comments: [], history: [{ at: "2026-08-18T14:00:00.000Z", action: "Solicitação interna criada" }] },
  { id: "it-3", title: "Revisar cronograma da volta às aulas", description: "Validar transporte, comunicação e manutenção das unidades.", kind: "Tarefa", requesterDepartment: "Secretaria de Educação", department: "Secretaria de Educação", assignee: "Gabinete da Educação", priority: "Normal", status: "Aguardando", dueAt: "2026-08-23T17:00:00.000Z", slaHours: 96, createdAt: "2026-08-17T10:00:00.000Z", updatedAt: "2026-08-18T09:00:00.000Z", tags: ["educação", "planejamento"], comments: [], history: [{ at: "2026-08-17T10:00:00.000Z", action: "Tarefa criada" }, { at: "2026-08-18T09:00:00.000Z", action: "Aguardando validação de transporte" }] },
];
export const INITIAL_PROJECTS: Project[] = [
  { id: "pj-1", title: "Revitalização da Praça Central", department: "Secretaria de Infraestrutura e Transporte", owner: "Diretoria de Obras", status: "Em execução", progress: 63, dueDate: "2026-10-15", stages: [{ name: "Projeto", done: true }, { name: "Licitação", done: true }, { name: "Execução", done: false }, { name: "Iluminação", done: false }, { name: "Paisagismo", done: false }] },
  { id: "pj-2", title: "Saúde Digital nas UBS", department: "Secretaria de Saúde", owner: "Coordenação de TI em Saúde", status: "Em execução", progress: 42, dueDate: "2026-11-30", stages: [{ name: "Mapeamento", done: true }, { name: "Infraestrutura", done: true }, { name: "Treinamento", done: false }, { name: "Implantação", done: false }] },
];
export const INITIAL_GOALS: Goal[] = [
  { id: "g-1", title: "Resolver solicitações dentro do prazo", department: "Secretaria de Infraestrutura e Transporte", current: 86, target: 90, unit: "%", dueDate: "2026-12-31" },
  { id: "g-2", title: "Reformar escolas municipais", department: "Secretaria de Educação", current: 6, target: 10, unit: "escolas", dueDate: "2026-12-20" },
  { id: "g-3", title: "Reduzir tempo médio de triagem", department: "Gabinete do Prefeito", current: 5, target: 4, unit: "horas", dueDate: "2026-09-30" },
];
const INITIAL_PLACES: PublicPlace[] = [
  { id: "pl-1", name: "Prefeitura Municipal de Várzea da Palma", type: "Prédio público", department: "Gabinete do Prefeito", neighborhood: "Pinlar", address: "Rua Cláudio Manoel da Costa, 1000 — Pinlar — Várzea da Palma/MG", status: "Operacional", lastMaintenance: "2026-08-08", history: ["08/08 — cadastro territorial revisado", "02/08 — atualização do ponto no mapa"] },
  { id: "pl-2", name: "Secretaria Municipal de Saúde", type: "Unidade de Saúde", department: "Secretaria de Saúde", neighborhood: "Planalto", address: "Rua Reinaldo Rodrigues, 305 — Planalto — Várzea da Palma/MG", status: "Operacional", lastMaintenance: "2026-08-12", history: ["12/08 — endereço institucional conferido", "30/07 — cadastro operacional atualizado"] },
  { id: "pl-3", name: "Secretaria Municipal de Educação", type: "Prédio público", department: "Secretaria de Educação", neighborhood: "Centro", address: "Rua Safira, 1244 — Centro — Várzea da Palma/MG", status: "Operacional", lastMaintenance: "2026-08-03", history: ["03/08 — endereço institucional conferido", "21/07 — cadastro operacional atualizado"] },
];

function id(prefix: string) { return `${prefix}-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`}`; }
function normalize(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function dateLabel(value: string) { try { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "America/Sao_Paulo" }).format(new Date(value)); } catch { return value; } }
function daysUntil(value: string) { return Math.ceil((new Date(`${value}T23:59:59`).getTime() - Date.now()) / 86400000); }
function taskRisk(task: IntegratedTask) {
  if (task.status === "Concluído") return { label: "Concluído", level: 0, className: "done" };
  const due = new Date(task.dueAt).getTime(); const created = new Date(task.createdAt).getTime(); const now = Date.now(); const hoursLate = Math.floor((now - due) / 3600000); const idle = Math.floor((now - new Date(task.updatedAt).getTime()) / 3600000);
  if (hoursLate > 48 || task.priority === "Urgente" && now > due) return { label: "Escalado ao Gabinete", level: 3, className: "critical" };
  if (now > due) return { label: `${Math.max(1, hoursLate)}h atrasada`, level: 2, className: "late" };
  if (idle >= 48) return { label: "48h sem movimentação", level: 2, className: "late" };
  const remaining = Math.round((due - now) / 3600000);
  if (remaining <= Math.max(2, task.slaHours * .2)) return { label: `${Math.max(0, remaining)}h para vencer`, level: 1, className: "warning" };
  return { label: "Dentro do SLA", level: 0, className: "ok" };
}
function wordSet(value: string) { return new Set(normalize(value).replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter((w)=>w.length>4)); }
function similarity(a: string, b: string) { const first=wordSet(a), second=wordSet(b); if(!first.size||!second.size)return 0; let hit=0; first.forEach((w)=>{if(second.has(w))hit++}); return hit/Math.min(first.size,second.size); }

function IntegratedModal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) {
  return <div className="integrated-modal-backdrop" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose();}}><section className="integrated-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">GESTÃO INTEGRADA</p><h2>{title}</h2></div><button onClick={onClose} aria-label="Fechar"><X size={18}/></button></header>{children}</section></div>;
}

export function IntegratedManagementSection({ department, currentUser, tickets, users, offices, events, departments, notify, initialTab = "Tarefas" }: {
  department: string; currentUser: UserInput; tickets: TicketInput[]; users: UserInput[]; offices: OfficeInput[]; events: EventInput[]; departments: string[]; notify: Notify; initialTab?: IntegratedTab;
}) {
  const [tab, setTab] = useState<IntegratedTab>(initialTab);
  const [tasks, setTasks, taskSave] = usePersistentState<IntegratedTask[]>("integrated:tasks:v2", INITIAL_TASKS);
  const [projects, setProjects, projectSave] = usePersistentState<Project[]>("integrated:projects:v2", INITIAL_PROJECTS);
  const [goals, setGoals, goalSave] = usePersistentState<Goal[]>("integrated:goals:v2", INITIAL_GOALS);
  const [places, setPlaces, placeSave] = usePersistentState<PublicPlace[]>("integrated:places:v2", INITIAL_PLACES);
  const [favorites, setFavorites] = usePersistentState<string[]>(persistenceKey("dashboard-favorites", currentUser.id, "v2"), ["Tarefas", "Projetos e metas", "IA Municipal"]);
  const [widgets, setWidgets] = usePersistentState<Record<string, boolean>>(persistenceKey("dashboard-widgets", currentUser.id, "v2"), { agenda: true, riscos: true, metas: true, secretarias: true });
  const [taskModal, setTaskModal] = useState(false); const [projectModal, setProjectModal] = useState(false); const [goalModal, setGoalModal] = useState(false); const [placeModal, setPlaceModal] = useState(false);
  const [selectedTask, setSelectedTask] = useState<IntegratedTask | null>(null); const [query, setQuery] = useState(""); const [dragId, setDragId] = useState<string | null>(null);
  const [aiText, setAiText] = useState(""); const [aiSubject, setAiSubject] = useState(""); const [aiNeighborhood, setAiNeighborhood] = useState(""); const [aiBusy, setAiBusy] = useState(false); const [aiResult, setAiResult] = useState<AiAnalysis | null>(null); const [weeklyReport, setWeeklyReport] = useState(""); const [aiConfigured, setAiConfigured] = useState<boolean | null>(null);
  const [health, setHealth] = useState<HealthPayload | null>(null); const [online, setOnline] = useState(true); const [backupBusy, setBackupBusy] = useState(false);

  useEffect(()=>{ const sync=()=>setOnline(navigator.onLine); sync(); window.addEventListener("online",sync); window.addEventListener("offline",sync); return()=>{window.removeEventListener("online",sync);window.removeEventListener("offline",sync)}; },[]);
  useEffect(()=>{ const refresh=(event:Event)=>{ const key=(event as CustomEvent<{key?:string}>).detail?.key; if(key==="integrated:tasks:v2")void loadPersistentValue<IntegratedTask[]>(key).then((value)=>value&&setTasks(value)).catch(()=>undefined); if(key==="integrated:projects:v2")void loadPersistentValue<Project[]>(key).then((value)=>value&&setProjects(value)).catch(()=>undefined); if(key==="integrated:goals:v2")void loadPersistentValue<Goal[]>(key).then((value)=>value&&setGoals(value)).catch(()=>undefined); if(key==="integrated:places:v2")void loadPersistentValue<PublicPlace[]>(key).then((value)=>value&&setPlaces(value)).catch(()=>undefined); }; window.addEventListener("municipal-agent-data-changed",refresh); return()=>window.removeEventListener("municipal-agent-data-changed",refresh); },[setGoals,setPlaces,setProjects,setTasks]);
  useEffect(()=>{ if(tab!=="Saúde do sistema")return; void fetch("/api/system-health",{cache:"no-store"}).then(r=>r.ok?r.json():null).then((p)=>{if(p)setHealth(p as HealthPayload)}).catch(()=>undefined); },[tab]);
  const allowedDepartment = (value: string) => departments.find((item)=>normalize(item)===normalize(value)) ?? department;
  const scopedTasks = useMemo(()=>tasks.filter((task)=>normalize(task.department)===normalize(department)),[department,tasks]);
  const filteredTasks = scopedTasks.filter((task)=>[task.title,task.description,task.department,task.assignee,task.kind,...task.tags].join(" ").toLowerCase().includes(query.toLowerCase()));
  const overdue = scopedTasks.filter((task)=>taskRisk(task).level>=2 && task.status!=="Concluído"); const urgent = scopedTasks.filter((task)=>task.priority==="Urgente"&&task.status!=="Concluído");
  const scopedProjects = projects.filter((project)=>normalize(project.department)===normalize(department)); const scopedGoals = goals.filter((goal)=>normalize(goal.department)===normalize(department));
  const scopedPlaces = places.filter((place)=>Boolean(place.department) && normalize(place.department)===normalize(department));
  const upcomingEvents = [...events].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).filter((event)=>new Date(event.startsAt).getTime()>=Date.now()-86400000).slice(0,5);
  const departmentLoad = useMemo(()=>[{name:department,total:scopedTasks.filter((task)=>task.status!=="Concluído").length,late:scopedTasks.filter((task)=>taskRisk(task).level>=2&&task.status!=="Concluído").length}].filter((item)=>item.total),[department,scopedTasks]);
  const mapTickets = tickets.filter((ticket)=>normalize(ticket.department)===normalize(department)&&(ticket.neighborhood||ticket.address));
  const hotspots = useMemo(()=>{const map=new Map<string,number>();mapTickets.forEach((t)=>{const key=t.neighborhood||"Local informado";map.set(key,(map.get(key)||0)+1)});return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[mapTickets]);
  const neighborhoodTicketPoints = useMemo<RealMapPoint[]>(() => {
    const priorityRank: Record<string, number> = { urgente: 4, alta: 3, media: 2, normal: 1, baixa: 0 };
    const groups = new Map<string, { neighborhood: string; count: number; priority: string; samples: string[]; address?: string; latitude?: number | null; longitude?: number | null }>();
    mapTickets.slice(0, 80).forEach((ticket) => {
      const neighborhood = ticket.neighborhood?.trim() || "Local informado";
      const key = normalize(neighborhood);
      const current = groups.get(key);
      const ticketPriority = ticket.priority || "Normal";
      if (!current) {
        groups.set(key, { neighborhood, count: 1, priority: ticketPriority, samples: [ticket.title].filter(Boolean), address: ticket.address, latitude: ticket.latitude, longitude: ticket.longitude });
        return;
      }
      current.count += 1;
      if ((priorityRank[normalize(ticketPriority)] ?? 0) > (priorityRank[normalize(current.priority)] ?? 0)) current.priority = ticketPriority;
      if (current.samples.length < 2 && ticket.title) current.samples.push(ticket.title);
      if ((!current.latitude || !current.longitude) && ticket.latitude && ticket.longitude) { current.latitude = ticket.latitude; current.longitude = ticket.longitude; }
      if (!current.address && ticket.address) current.address = ticket.address;
    });
    return [...groups.values()].map((group) => ({
      id: `bairro:${normalize(group.neighborhood)}`,
      title: group.neighborhood,
      subtitle: `${group.count} ${group.count === 1 ? "ocorrência" : "ocorrências"}${group.samples.length ? ` · ${group.samples.join(" · ")}` : ""}`,
      priority: group.priority,
      address: group.address,
      neighborhood: group.neighborhood,
      latitude: group.latitude,
      longitude: group.longitude,
      kind: "ticket" as const,
    }));
  }, [mapTickets]);
  const realMapPoints = useMemo<RealMapPoint[]>(() => [
    ...neighborhoodTicketPoints,
    ...scopedPlaces.map((place) => ({ id: `place:${place.id}`, title: place.name, subtitle: `${place.type} · ${place.address}`, priority: "Normal", address: place.address, neighborhood: place.neighborhood, latitude: place.latitude, longitude: place.longitude, kind: "place" as const })),
  ], [neighborhoodTicketPoints, scopedPlaces]);

  function createTask(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form=new FormData(event.currentTarget); const now=new Date().toISOString(); const due=String(form.get("dueAt"));
    const next: IntegratedTask={ id:id("task"), title:String(form.get("title")), description:String(form.get("description")), kind:String(form.get("kind")) as IntegratedTask["kind"], requesterDepartment:department, department:allowedDepartment(String(form.get("department"))), assignee:String(form.get("assignee"))||"Responsável a definir", priority:String(form.get("priority")) as TaskPriority, status:"A fazer", dueAt:due?new Date(due).toISOString():new Date(Date.now()+48*3600000).toISOString(), slaHours:Number(form.get("slaHours"))||48, createdAt:now, updatedAt:now, tags:String(form.get("tags")||"").split(",").map((v)=>v.trim()).filter(Boolean), comments:[], history:[{at:now,action:`Criada por ${currentUser.fullName} em ${department}`}] };
    setTasks((current)=>[next,...current]); setTaskModal(false); notify(`Tarefa “${next.title}” criada e encaminhada para ${next.department}.`);
  }
  function moveTask(taskId: string, status: WorkStatus) { setTasks((current)=>current.map((task)=>task.id===taskId?{...task,status,updatedAt:new Date().toISOString(),history:[...task.history,{at:new Date().toISOString(),action:`Movida para ${status} por ${currentUser.fullName}`}]}:task)); setSelectedTask((current)=>current?.id===taskId?{...current,status}:current); }
  function addComment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if(!selectedTask)return; const form=new FormData(event.currentTarget); const text=String(form.get("comment")||"").trim(); if(!text)return; const comment={id:id("comment"),author:currentUser.fullName,text,createdAt:new Date().toISOString()}; setTasks((current)=>current.map((task)=>task.id===selectedTask.id?{...task,comments:[...task.comments,comment],updatedAt:comment.createdAt,history:[...task.history,{at:comment.createdAt,action:"Comentário interno registrado"}]}:task)); setSelectedTask((task)=>task?{...task,comments:[...task.comments,comment]}:task); event.currentTarget.reset(); const mentions=(text.match(/@[\p{L}0-9_-]+/gu)||[]).join(", "); notify(mentions?`Comentário salvo. Menções identificadas: ${mentions}.`:`Comentário salvo no histórico da tarefa.`); }
  function createProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=new FormData(event.currentTarget); const stages=String(form.get("stages")||"Planejamento,Execução,Validação,Entrega").split(",").map((name)=>({name:name.trim(),done:false})).filter((s)=>s.name); const next:Project={id:id("project"),title:String(form.get("title")),department:allowedDepartment(String(form.get("department"))),owner:String(form.get("owner"))||currentUser.fullName,status:"Planejamento",progress:0,dueDate:String(form.get("dueDate")),stages}; setProjects((current)=>[next,...current]);setProjectModal(false);notify(`Projeto “${next.title}” cadastrado.`); }
  function createGoal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=new FormData(event.currentTarget); const target=Math.max(1,Number(form.get("target"))||1); const next:Goal={id:id("goal"),title:String(form.get("title")),department:allowedDepartment(String(form.get("department"))),current:Math.max(0,Number(form.get("current"))||0),target,unit:String(form.get("unit"))||"%",dueDate:String(form.get("dueDate"))}; setGoals((current)=>[next,...current]);setGoalModal(false);notify(`Meta “${next.title}” cadastrada.`); }
  function createPlace(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=new FormData(event.currentTarget); const rawLat=String(form.get("latitude")||"").trim(),rawLon=String(form.get("longitude")||"").trim(); const latitude=rawLat?Number(rawLat.replace(",",".")):null,longitude=rawLon?Number(rawLon.replace(",",".")):null; const next:PublicPlace={id:id("place"),name:String(form.get("name")),type:String(form.get("type")),department,neighborhood:String(form.get("neighborhood")),address:String(form.get("address")),status:String(form.get("status"))||"Operacional",lastMaintenance:new Date().toISOString().slice(0,10),history:[`${new Date().toLocaleDateString("pt-BR")} — local cadastrado por ${currentUser.fullName}`],latitude:Number.isFinite(latitude)?latitude:null,longitude:Number.isFinite(longitude)?longitude:null};setPlaces((current)=>[next,...current]);setPlaceModal(false);notify(`${next.name} adicionado ao cadastro de locais do setor.`); }
  async function analyzeAi() { if(!aiText.trim()&&!aiSubject.trim())return;setAiBusy(true);setAiResult(null);try{const response=await fetch("/api/ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"analyze",subject:aiSubject,message:aiText,neighborhood:aiNeighborhood,department})});const payload=await response.json() as {analysis?:AiAnalysis;configured?:boolean;error?:string};if(!response.ok||!payload.analysis)throw new Error(payload.error||"Falha na IA");setAiResult({...payload.analysis,suggestedDepartment:allowedDepartment(payload.analysis.suggestedDepartment)});setAiConfigured(Boolean(payload.configured));}catch(error){notify(error instanceof Error?error.message:"Não foi possível executar a IA.");}finally{setAiBusy(false);} }
  async function generateWeekly() { setAiBusy(true);try{const grouped=[{department,total:tickets.length,open:tickets.filter((t)=>!["Concluído","Cancelado"].includes(t.status)).length,late:scopedTasks.filter((t)=>taskRisk(t).level>=2&&t.status!=="Concluído").length}];const response=await fetch("/api/ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"weekly_report",data:{generatedAt:new Date().toISOString(),scope:{department},tickets:{total:tickets.length,open:tickets.filter((t)=>!["Concluído","Cancelado"].includes(t.status)).length},tasks:{total:scopedTasks.length,overdue:scopedTasks.filter((t)=>taskRisk(t).level>=2&&t.status!=="Concluído").length},projects:scopedProjects.map(({title,department:projectDepartment,status,progress,dueDate})=>({title,department:projectDepartment,status,progress,dueDate})),goals:scopedGoals,departments:grouped}})});const payload=await response.json() as {text?:string;configured?:boolean;error?:string};if(!response.ok||!payload.text)throw new Error(payload.error||"Falha ao gerar resumo");setWeeklyReport(payload.text);setAiConfigured(Boolean(payload.configured));}catch(error){notify(error instanceof Error?error.message:"Não foi possível gerar o resumo semanal.");}finally{setAiBusy(false);} }
  async function createBackup() { setBackupBusy(true);try{const response=await fetch("/api/backup",{method:"POST"});const payload=await response.json() as {count?:number;error?:string};if(!response.ok)throw new Error(payload.error||"Falha no backup");notify(`Backup concluído: ${payload.count??0} registros críticos copiados.`);}catch(error){notify(error instanceof Error?error.message:"Não foi possível criar o backup.");}finally{setBackupBusy(false);} }
  function toggleFavorite(label:string){setFavorites((current)=>current.includes(label)?current.filter((i)=>i!==label):[...current,label]);}

  const saveState=[taskSave,projectSave,goalSave,placeSave].includes("offline")?"offline":[taskSave,projectSave,goalSave,placeSave].includes("salvando")?"salvando":"salvo";
  const similarToAi=aiResult?[...tickets].map((ticket)=>({ticket,score:similarity(`${aiSubject} ${aiText} ${aiNeighborhood}`,`${ticket.title} ${ticket.description} ${ticket.neighborhood||""}`)})).filter((x)=>x.score>=.35).sort((a,b)=>b.score-a.score).slice(0,5):[];

  return <section className="integrated-shell">
    <div className="integrated-topline"><span className={`module-sync-banner ${saveState}`}>{saveState==="offline"?"Modo resiliente: alterações mantidas localmente até reconectar":saveState==="salvando"?"Sincronizando gestão integrada…":"Gestão integrada sincronizada"}</span><span className={online?"connectivity online":"connectivity offline"}>{online?<Wifi size={13}/>:<WifiOff size={13}/>} {online?"Online":"Sem conexão"}</span></div>
    <div className="integrated-tabs clean-integrated-tabs" role="tablist">
      {(["Central","Tarefas","Projetos e metas"] as IntegratedTab[]).map((item)=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item === "Projetos e metas" ? "Projetos" : item}</button>)}
      <details className={`integrated-more-nav ${["Mapa e locais","Organograma","IA Municipal","Saúde do sistema"].includes(tab)?"active":""}`}>
        <summary>Mais <ChevronRight size={14}/></summary>
        <div>
          {(["Mapa e locais","Organograma","IA Municipal","Saúde do sistema"] as IntegratedTab[]).map((item)=><button key={item} className={tab===item?"active":""} onClick={(event)=>{setTab(item);const details=event.currentTarget.closest("details");details?.removeAttribute("open");}}>{item==="IA Municipal"&&<Sparkles size={14}/>} {item}</button>)}
        </div>
      </details>
    </div>

    {tab==="Central"&&<>
      <article className="panel integrated-command-hero"><div><p className="eyebrow">CENTRAL DE GESTÃO SETORIAL</p><h2>{`Painel operacional de ${department}`}</h2><p>Uma visão exclusiva das tarefas, prazos, projetos, metas, agenda e riscos do setor selecionado.</p></div><div className="integrated-command-score"><Gauge size={22}/><strong>{Math.max(0,100-Math.min(45,overdue.length*6))}%</strong><small>saúde operacional</small></div></article>
      <div className="integrated-kpis"><article><ClipboardList size={18}/><span><small>Tarefas abertas</small><strong>{scopedTasks.filter((t)=>t.status!=="Concluído").length}</strong></span></article><article className="danger"><AlertTriangle size={18}/><span><small>Atrasadas / escaladas</small><strong>{overdue.length}</strong></span></article><article><BriefcaseBusiness size={18}/><span><small>Projetos ativos</small><strong>{scopedProjects.filter((p)=>p.status!=="Concluído").length}</strong></span></article><article><Target size={18}/><span><small>Metas monitoradas</small><strong>{scopedGoals.length}</strong></span></article><article><CalendarClock size={18}/><span><small>Próximos eventos</small><strong>{upcomingEvents.length}</strong></span></article></div>
      <article className="panel favorite-strip"><header><div><p className="eyebrow">ATALHOS FAVORITOS</p><h3>Seu espaço de trabalho</h3></div><small>Personalização por usuário</small></header><div>{["Tarefas","Projetos e metas","Mapa e locais","IA Municipal","Saúde do sistema"].map((label)=><button key={label} className={favorites.includes(label)?"favorite":""} onClick={()=>favorites.includes(label)?setTab(label as IntegratedTab):toggleFavorite(label)}><Star size={14} fill={favorites.includes(label)?"currentColor":"none"}/><span>{label}</span>{favorites.includes(label)&&<ChevronRight size={13}/>}</button>)}</div></article>
      <div className="widget-controls"><span>Widgets do painel:</span>{Object.entries({agenda:"Agenda",riscos:"Riscos",metas:"Metas",secretarias:"Secretarias"}).map(([key,label])=><button key={key} className={widgets[key]?"active":""} onClick={()=>setWidgets((current)=>({...current,[key]:!current[key]}))}><Check size={12}/>{label}</button>)}</div>
      <div className="integrated-dashboard-grid">
        {widgets.riscos&&<article className="panel integrated-risk-list"><header><div><h3>Riscos e escalonamentos</h3><p>SLA, inatividade e prioridades</p></div><AlertTriangle size={18}/></header>{[...overdue,...urgent.filter((t)=>!overdue.some((o)=>o.id===t.id))].slice(0,6).map((task)=>{const risk=taskRisk(task);return <button key={task.id} onClick={()=>{setSelectedTask(task);setTab("Tarefas")}}><i className={risk.className}><Clock3 size={13}/></i><span><strong>{task.title}</strong><small>{task.department} · {task.assignee}</small></span><b>{risk.label}</b></button>})}{!overdue.length&&!urgent.length&&<div className="integrated-empty"><CheckCircle2 size={22}/><strong>Nenhum risco crítico</strong><p>Os escalonamentos automáticos aparecerão aqui.</p></div>}</article>}
        {widgets.agenda&&<article className="panel integrated-agenda"><header><div><h3>Agenda executiva</h3><p>Próximos compromissos</p></div><CalendarClock size={18}/></header>{upcomingEvents.map((event)=><div key={event.id}><span><strong>{dateLabel(event.startsAt)}</strong><small>{event.department}</small></span><p>{event.title}<small>{event.location||"Local a definir"}</small></p></div>)}{!upcomingEvents.length&&<div className="integrated-empty"><CalendarClock size={22}/><strong>Agenda livre</strong></div>}</article>}
        {widgets.metas&&<article className="panel integrated-goal-mini"><header><div><h3>Metas da gestão</h3><p>Progresso das prioridades</p></div><Target size={18}/></header>{scopedGoals.slice(0,5).map((goal)=>{const pct=Math.min(100,Math.round((goal.current/goal.target)*100));return <div key={goal.id}><span><strong>{goal.title}</strong><small>{goal.department}</small></span><div><i style={{width:`${pct}%`}}/></div><b>{goal.current}/{goal.target} {goal.unit}</b></div>})}</article>}
        {widgets.secretarias&&<article className="panel department-load"><header><div><h3>Carga do setor</h3><p>Tarefas abertas e atrasos</p></div><Building2 size={18}/></header>{departmentLoad.map((item)=><div key={item.name}><span><strong>{item.name}</strong><small>{item.total} abertas</small></span><b className={item.late?"late":""}>{item.late?`${item.late} atrasadas`:"sem atraso"}</b></div>)}</article>}
      </div>
      <div className="quick-create-grid"><button onClick={()=>setTaskModal(true)}><Plus size={17}/><span><strong>Nova tarefa</strong><small>Responsável, SLA e setor</small></span></button><button onClick={()=>setProjectModal(true)}><BriefcaseBusiness size={17}/><span><strong>Novo projeto</strong><small>Etapas e progresso</small></span></button><button onClick={()=>setPlaceModal(true)}><MapPin size={17}/><span><strong>Novo local público</strong><small>Histórico de manutenção</small></span></button><button onClick={()=>setTab("IA Municipal")}><Bot size={17}/><span><strong>Analisar com IA</strong><small>Triagem e resumo</small></span></button></div>
    </>}

    {tab==="Tarefas"&&<>
      <div className="integrated-section-heading"><div><p className="eyebrow">TAREFAS E SOLICITAÇÕES INTERNAS</p><h2>Fluxo operacional com SLA</h2><p>Tarefas, vistorias e pedidos entre setores mantêm responsável, prazo, comentários, menções e histórico.</p></div><button className="button primary" onClick={()=>setTaskModal(true)}><Plus size={15}/> Nova tarefa</button></div>
      <div className="module-toolbar"><label className="module-search"><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar tarefa, setor, responsável ou tag..." /></label><span className="sla-legend"><i className="ok"/> SLA normal <i className="warning"/> vencendo <i className="late"/> atraso/escalado</span></div>
      <div className="integrated-kanban">{WORK_COLUMNS.map((status)=><section key={status} className="integrated-kanban-column" onDragOver={(e)=>e.preventDefault()} onDrop={()=>{if(dragId){moveTask(dragId,status);setDragId(null)}}}><header><span><CircleDot size={13}/>{status}</span><strong>{filteredTasks.filter((t)=>t.status===status).length}</strong></header><div>{filteredTasks.filter((t)=>t.status===status).map((task)=>{const risk=taskRisk(task);return <article draggable onDragStart={()=>setDragId(task.id)} key={task.id} className={`integrated-task-card risk-${risk.className}`}><div className="task-card-meta"><span>{task.kind}</span><b>{task.priority}</b></div><h3>{task.title}</h3><p>{task.description}</p><small>{task.department}</small><div className="task-owner"><UsersRound size={13}/><span>{task.assignee}</span></div><div className={`task-risk ${risk.className}`}><Clock3 size={12}/>{risk.label}</div><footer><span>{task.comments.length} comentários</span><button onClick={()=>setSelectedTask(task)}>Abrir <ChevronRight size={12}/></button></footer></article>})}</div></section>)}</div>
    </>}

    {tab==="Projetos e metas"&&<>
      <div className="integrated-section-heading"><div><p className="eyebrow">PROJETOS E METAS DO SETOR</p><h2>Do planejamento à entrega</h2><p>Acompanhe progresso, etapas, prazos e metas mensuráveis de {department}.</p></div><div className="integrated-heading-actions"><button className="button secondary" onClick={()=>setGoalModal(true)}><Target size={15}/> Nova meta</button><button className="button primary" onClick={()=>setProjectModal(true)}><Plus size={15}/> Novo projeto</button></div></div>
      <div className="project-grid">{scopedProjects.map((project)=><article className="panel project-card" key={project.id}><header><span><BriefcaseBusiness size={18}/></span><b className={`project-status ${normalize(project.status).replaceAll(" ","-")}`}>{project.status}</b></header><h3>{project.title}</h3><p>{project.department} · {project.owner}</p><div className="project-progress"><span><i style={{width:`${project.progress}%`}}/></span><strong>{project.progress}%</strong></div><div className="project-stages">{project.stages.map((stage,index)=><button key={stage.name} className={stage.done?"done":""} onClick={()=>setProjects((current)=>current.map((p)=>p.id===project.id?{...p,stages:p.stages.map((s,i)=>i===index?{...s,done:!s.done}:s)}:p))}><span>{stage.done?<Check size={11}/>:index+1}</span>{stage.name}</button>)}</div><footer><span><CalendarClock size={13}/> prazo {new Date(`${project.dueDate}T12:00:00`).toLocaleDateString("pt-BR")}</span><div><button onClick={()=>setProjects((current)=>current.map((p)=>p.id===project.id?{...p,progress:Math.max(0,p.progress-10)}:p))}>−10</button><button onClick={()=>setProjects((current)=>current.map((p)=>p.id===project.id?{...p,progress:Math.min(100,p.progress+10),status:p.progress+10>=100?"Concluído":p.status}:p))}>+10</button></div></footer></article>)}</div>
      <article className="panel goals-table"><header><div><p className="eyebrow">METAS</p><h2>Indicadores vinculados a resultado</h2></div><Target size={19}/></header>{scopedGoals.map((goal)=>{const higherIsBetter=goal.unit!=="horas";const pct=higherIsBetter?Math.min(100,Math.round(goal.current/goal.target*100)):Math.min(100,Math.round(goal.target/goal.current*100));return <div key={goal.id}><span><strong>{goal.title}</strong><small>{goal.department} · prazo {new Date(`${goal.dueDate}T12:00:00`).toLocaleDateString("pt-BR")}</small></span><div><i style={{width:`${pct}%`}}/></div><b>{goal.current} / {goal.target} {goal.unit}</b><button onClick={()=>setGoals((current)=>current.map((g)=>g.id===goal.id?{...g,current:Math.max(0,g.current+(g.unit==="%"?1:g.unit==="horas"?-1:1))}:g))}>Atualizar</button></div>})}</article>
    </>}

    {tab==="Mapa e locais"&&<>
      <div className="integrated-section-heading"><div><p className="eyebrow">GESTÃO TERRITORIAL</p><h2>Mapa de ocorrências e locais públicos</h2><p>Concentre demandas por bairro e mantenha histórico operacional de escolas, UBSs, praças e demais equipamentos.</p></div><button className="button primary" onClick={()=>setPlaceModal(true)}><Plus size={15}/> Cadastrar local</button></div>
      <div className="territorial-layout"><article className="panel operational-map real-map-panel"><header><div><h3>Mapa real de Várzea da Palma</h3><p>Ruas, bairros, chamados e equipamentos públicos posicionados sobre o OpenStreetMap.</p></div><MapIcon size={19}/></header><RealMunicipalMap points={realMapPoints} onPointClick={(point)=>notify(`${point.title}${point.subtitle ? ` · ${point.subtitle}` : ""}`)}/><footer><span><i className="priority-urgente"/> Urgente</span><span><i className="priority-alta"/> Alta</span><span><i className="priority-media"/> Moderada</span><span><i/> Demais</span></footer></article><aside className="panel hotspot-list"><header><div><h3>Áreas com concentração</h3><p>Ocorrências por bairro</p></div><BarChart3 size={18}/></header>{hotspots.map(([name,count],index)=><div key={name}><span>{index+1}</span><strong>{name}</strong><b>{count} {count===1?"ocorrência":"ocorrências"}</b></div>)}{!hotspots.length&&<div className="integrated-empty"><MapIcon size={22}/><strong>Sem concentração identificada</strong></div>}</aside></div>
      <article className="panel territorial-ai-insight"><span><Sparkles size={20}/></span><div><small>LEITURA TERRITORIAL DA IA</small><strong>{hotspots[0] ? `${hotspots[0][0]} concentra o maior volume observado` : "Mapa pronto para análise inteligente"}</strong><p>{hotspots[0] ? `A região reúne ${hotspots[0][1]} ocorrência(s) no contexto atual. Cruze prioridade, tipo e localização para planejar a próxima ação de campo.` : "Adicione ocorrências e locais para a IA destacar concentrações, riscos e prioridades de atendimento."}</p></div><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent("prefeitura:open-ai",{detail:{prompt:"Analise o mapa, os bairros e as ocorrências visíveis. Mostre concentrações, riscos e um plano de ação territorial."}}))}><Bot size={14}/> Analisar mapa com IA <ChevronRight size={13}/></button></article>
      <div className="public-place-grid">{scopedPlaces.map((place)=><article className="panel public-place-card" key={place.id}><header><span><Landmark size={18}/></span><b>{place.status}</b></header><h3>{place.name}</h3><p>{place.type} · {place.neighborhood}</p><small><MapPin size={12}/>{place.address}</small><dl><div><dt>Última manutenção</dt><dd>{new Date(`${place.lastMaintenance}T12:00:00`).toLocaleDateString("pt-BR")}</dd></div><div><dt>Histórico</dt><dd>{place.history.length} registros</dd></div></dl><details><summary>Ver histórico</summary>{place.history.map((entry)=><p key={entry}>{entry}</p>)}</details></article>)}</div>
    </>}

    {tab==="Organograma"&&<>
      <div className="integrated-section-heading"><div><p className="eyebrow">ESTRUTURA MUNICIPAL</p><h2>Organograma e diretório interno</h2><p>Localize responsáveis, setores e contatos e entenda a cadeia de responsabilidade.</p></div></div>
      <article className="panel organogram"><div className="org-level executive"><span><Landmark size={19}/></span><strong>{department}</strong><small>Estrutura do setor selecionado</small></div><div className="org-connector"/><div className="org-grid">{offices.slice(0,10).map((office)=><article key={office.id}><span><Building2 size={16}/></span><strong>{office.name}</strong><small>{office.head}</small></article>)}</div></article>
      <article className="panel internal-directory"><header><div><h2>Diretório de pessoas</h2><p>Servidor, cargo e unidade</p></div><label><Search size={14}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar pessoa ou setor..." /></label></header><div>{users.filter((user)=>[user.fullName,user.department,user.role].join(" ").toLowerCase().includes(query.toLowerCase())).map((user)=><article key={user.id}><span>{user.initials||user.fullName.split(/\s+/).slice(0,2).map((p)=>p[0]).join("")}</span><div><strong>{user.fullName}</strong><small>{user.role} · {user.department}</small></div><button onClick={()=>notify(`Contato interno de ${user.fullName} aberto no diretório.`)}>Abrir <ChevronRight size={12}/></button></article>)}</div></article>
    </>}

    {tab==="IA Municipal"&&<>
      <article className="panel ai-hero"><span><Bot size={28}/></span><div><p className="eyebrow">INTELIGÊNCIA ARTIFICIAL APLICADA À GESTÃO</p><h2>Assistente de triagem e análise municipal</h2><p>Resume relatos extensos, sugere categoria e secretaria, sinaliza urgência para revisão humana, identifica padrões e gera resumo executivo.</p></div><b className={aiConfigured===false?"fallback":""}>{aiConfigured===false?"Modo regras de contingência":aiConfigured?"IA conectada":"Pronto para análise"}</b></article>
      <div className="ai-workbench"><article className="panel ai-input-card"><header><div><h3>Analisar uma demanda</h3><p>Cole um relato, chamado ou manifestação.</p></div><Sparkles size={18}/></header><label><span>Assunto</span><input value={aiSubject} onChange={(e)=>setAiSubject(e.target.value)} placeholder="Ex.: poste apagado com fio exposto" /></label><label><span>Bairro</span><input value={aiNeighborhood} onChange={(e)=>setAiNeighborhood(e.target.value)} placeholder="Opcional" /></label><label><span>Relato</span><textarea value={aiText} onChange={(e)=>setAiText(e.target.value)} placeholder="Cole aqui o texto que deseja resumir e classificar..." /></label><button className="button primary" disabled={aiBusy||(!aiText.trim()&&!aiSubject.trim())} onClick={analyzeAi}><Sparkles size={15}/>{aiBusy?"Analisando...":"Analisar com IA"}</button></article>
      <article className="panel ai-result-card"><header><div><h3>Triagem sugerida</h3><p>Resultado sempre sujeito à validação do servidor responsável.</p></div><ShieldCheck size={18}/></header>{aiResult?<><div className="ai-summary"><strong>Resumo</strong><p>{aiResult.summary}</p></div><dl><div><dt>Categoria</dt><dd>{aiResult.category}</dd></div><div><dt>Secretaria sugerida</dt><dd>{aiResult.suggestedDepartment}</dd></div><div><dt>Urgência</dt><dd className={`ai-urgency ${normalize(aiResult.urgency)}`}>{aiResult.urgency}</dd></div><div><dt>Motivo</dt><dd>{aiResult.urgencyReason}</dd></div></dl><div className="ai-tags">{aiResult.tags.map((tag)=><span key={tag}>{tag}</span>)}</div><aside><strong>Próxima ação sugerida</strong><p>{aiResult.recommendedAction}</p></aside>{similarToAi.length>0&&<div className="similar-demands"><strong>Demandas semelhantes encontradas no sistema</strong>{similarToAi.map(({ticket,score})=><button key={ticket.id} onClick={()=>notify(`${ticket.protocol}: ${ticket.title}`)}><span>{ticket.protocol}</span><p>{ticket.title}</p><b>{Math.round(score*100)}%</b></button>)}</div>}</>:<div className="integrated-empty"><Bot size={30}/><strong>Aguardando um relato</strong><p>A IA não executa ações sozinha; ela prepara a triagem para decisão humana.</p></div>}</article></div>
      <article className="panel weekly-ai"><header><div><p className="eyebrow">RELATÓRIO SETORIAL</p><h2>Resumo semanal inteligente</h2><p>Consolida somente tarefas, projetos, metas e volumes de {department}, sem expor dados de outros setores.</p></div><div className="weekly-ai-actions"><button className="button primary" disabled={aiBusy} onClick={generateWeekly}><RefreshCcw size={14}/>{aiBusy?"Gerando...":"Gerar agora"}</button></div></header>{weeklyReport?<pre>{weeklyReport}</pre>:<div className="weekly-placeholder"><Activity size={22}/><span><strong>Pronto para o acompanhamento do setor</strong><p>Gere um resumo quando precisar consolidar o cenário atual.</p></span></div>}</article>
      <article className="ai-safety-note"><ShieldCheck size={17}/><div><strong>Governança da IA</strong><p>A classificação é assistiva: urgência, encaminhamento e decisões continuam sob responsabilidade humana. Dados de contato não são necessários para a análise.</p></div></article>
    </>}

    {tab==="Saúde do sistema"&&<>
      <div className="integrated-section-heading"><div><p className="eyebrow">OPERAÇÃO E RESILIÊNCIA</p><h2>Saúde, backup e disponibilidade</h2><p>Verifique integrações críticas, operação offline e rotinas de segurança antes do uso em produção.</p></div><button className="button secondary" onClick={()=>{setHealth(null);fetch("/api/system-health",{cache:"no-store"}).then(async (r)=>{ if(!r.ok) throw new Error("Falha ao verificar a saúde do sistema"); return await r.json() as HealthPayload; }).then((payload)=>setHealth(payload)).catch(()=>undefined)}}><RefreshCcw size={14}/> Verificar agora</button></div>
      <div className="health-grid">{health?Object.entries(health.services).map(([key,service])=><article className="panel health-card" key={key}><span className={service.ok?"ok":"warning"}>{key==="storage"?<Database size={20}/>:key==="ai"?<Bot size={20}/>:key==="pwa"?<Cloud size={20}/>:<ShieldCheck size={20}/>}</span><div><small>{service.label}</small><strong>{service.ok?"Operacional":"Configuração pendente"}</strong>{service.model&&<p>Modelo: {service.model}</p>}</div></article>):<div className="panel health-loading">Verificando serviços...</div>}<article className="panel health-card"><span className={online?"ok":"warning"}>{online?<Wifi size={20}/>:<WifiOff size={20}/>}</span><div><small>Conectividade atual</small><strong>{online?"Online":"Modo offline"}</strong><p>Alterações persistentes usam cache de contingência e tentam sincronizar após a reconexão.</p></div></article></div>
      <div className="health-operations"><article className="panel backup-card"><span><ServerCog size={22}/></span><div><p className="eyebrow">BACKUP SOB DEMANDA</p><h3>Snapshot dos dados críticos</h3><p>Copia estados persistentes, manifestações e metadados para uma pasta versionada no armazenamento central.</p></div><button className="button primary" disabled={backupBusy} onClick={createBackup}>{backupBusy?"Criando backup...":"Executar backup agora"}</button></article><article className="panel production-checklist"><header><div><h3>Checklist de produção</h3><p>Controles já contemplados na arquitetura</p></div><FileCheck2 size={18}/></header>{["2FA por SMS quando configurado","Matriz granular de permissões","Auditoria e exportação de logs","Mascaramento e retenção LGPD","PWA e cache resiliente","Backup central versionado","IA com revisão humana"].map((item)=><div key={item}><CheckCircle2 size={14}/>{item}</div>)}</article></div>
    </>}

    {taskModal&&<IntegratedModal title="Nova tarefa ou solicitação interna" onClose={()=>setTaskModal(false)}><form className="integrated-form" onSubmit={createTask}><label className="full"><span>Título *</span><input name="title" required /></label><label className="full"><span>Descrição *</span><textarea name="description" required /></label><label><span>Tipo</span><select name="kind"><option>Tarefa</option><option>Solicitação interna</option><option>Vistoria</option></select></label><label><span>Prioridade</span><select name="priority"><option>Normal</option><option>Alta</option><option>Urgente</option><option>Baixa</option></select></label><label className="full"><span>Setor responsável</span><select name="department" defaultValue={department}>{departments.map((name)=><option key={name}>{name}</option>)}</select></label><label><span>Responsável</span><input name="assignee" placeholder="Pessoa ou equipe" /></label><label><span>SLA em horas</span><input name="slaHours" type="number" min="1" defaultValue="48" /></label><label><span>Prazo</span><input name="dueAt" type="datetime-local" /></label><label><span>Tags</span><input name="tags" placeholder="obra, urgente, vistoria" /></label><div className="integrated-form-actions"><button type="button" className="button secondary" onClick={()=>setTaskModal(false)}>Cancelar</button><button className="button primary"><Plus size={14}/> Criar e encaminhar</button></div></form></IntegratedModal>}
    {projectModal&&<IntegratedModal title="Novo projeto municipal" onClose={()=>setProjectModal(false)}><form className="integrated-form" onSubmit={createProject}><label className="full"><span>Nome do projeto *</span><input name="title" required /></label><label className="full"><span>Secretaria responsável</span><select name="department" defaultValue={department}>{departments.map((name)=><option key={name}>{name}</option>)}</select></label><label><span>Responsável</span><input name="owner" defaultValue={currentUser.fullName}/></label><label><span>Prazo *</span><input name="dueDate" type="date" required /></label><label className="full"><span>Etapas separadas por vírgula</span><input name="stages" defaultValue="Planejamento, Contratação, Execução, Validação, Entrega" /></label><div className="integrated-form-actions"><button type="button" className="button secondary" onClick={()=>setProjectModal(false)}>Cancelar</button><button className="button primary">Criar projeto</button></div></form></IntegratedModal>}
    {goalModal&&<IntegratedModal title="Nova meta da gestão" onClose={()=>setGoalModal(false)}><form className="integrated-form" onSubmit={createGoal}><label className="full"><span>Nome da meta *</span><input name="title" required placeholder="Ex.: Resolver 90% das demandas no prazo" /></label><label className="full"><span>Secretaria responsável</span><select name="department" defaultValue={department}>{departments.map((name)=><option key={name}>{name}</option>)}</select></label><label><span>Valor atual</span><input name="current" type="number" step="0.01" min="0" defaultValue="0" /></label><label><span>Meta *</span><input name="target" type="number" step="0.01" min="0.01" required defaultValue="100" /></label><label><span>Unidade</span><input name="unit" defaultValue="%" placeholder="%, escolas, horas..." /></label><label><span>Prazo *</span><input name="dueDate" type="date" required /></label><div className="integrated-form-actions"><button type="button" className="button secondary" onClick={()=>setGoalModal(false)}>Cancelar</button><button className="button primary"><Target size={14}/> Criar meta</button></div></form></IntegratedModal>}
    {placeModal&&<IntegratedModal title="Cadastrar local público" onClose={()=>setPlaceModal(false)}><form className="integrated-form" onSubmit={createPlace}><label className="full"><span>Nome *</span><input name="name" required /></label><label><span>Tipo</span><select name="type"><option>Escola</option><option>Unidade de Saúde</option><option>Praça</option><option>Prédio público</option><option>Ginásio</option><option>Ponte</option><option>Outro</option></select></label><label><span>Situação</span><select name="status"><option>Operacional</option><option>Em manutenção</option><option>Interditado</option><option>Em vistoria</option></select></label><label><span>Bairro *</span><input name="neighborhood" required /></label><label className="full"><span>Endereço *</span><input name="address" required placeholder="Rua, número, bairro — Várzea da Palma/MG" /></label><label><span>Latitude exata (opcional)</span><input name="latitude" inputMode="decimal" placeholder="-17.6005" /></label><label><span>Longitude exata (opcional)</span><input name="longitude" inputMode="decimal" placeholder="-44.7340" /></label><p className="integrated-map-coordinate-hint full"><MapPin size={13}/> Se informar latitude e longitude, o mapa usa a coordenada exata. Sem elas, o endereço será localizado automaticamente.</p><div className="integrated-form-actions"><button type="button" className="button secondary" onClick={()=>setPlaceModal(false)}>Cancelar</button><button className="button primary">Cadastrar local</button></div></form></IntegratedModal>}
    {selectedTask&&<IntegratedModal title={selectedTask.title} onClose={()=>setSelectedTask(null)}><div className="task-detail"><div className="task-detail-head"><span>{selectedTask.kind}</span><b>{selectedTask.priority}</b><i className={taskRisk(selectedTask).className}>{taskRisk(selectedTask).label}</i></div><p>{selectedTask.description}</p><dl><div><dt>Solicitante</dt><dd>{selectedTask.requesterDepartment}</dd></div><div><dt>Responsável</dt><dd>{selectedTask.department} · {selectedTask.assignee}</dd></div><div><dt>SLA</dt><dd>{selectedTask.slaHours}h · prazo {dateLabel(selectedTask.dueAt)}</dd></div><div><dt>Status</dt><dd><select value={selectedTask.status} onChange={(e)=>{moveTask(selectedTask.id,e.target.value as WorkStatus);setSelectedTask({...selectedTask,status:e.target.value as WorkStatus})}}>{WORK_COLUMNS.map((s)=><option key={s}>{s}</option>)}</select></dd></div></dl><section className="task-comments"><h3>Comentários internos e @menções</h3>{selectedTask.comments.map((comment)=><article key={comment.id}><strong>{comment.author}</strong><p>{comment.text}</p><small>{dateLabel(comment.createdAt)}</small></article>)}<form onSubmit={addComment}><textarea name="comment" placeholder="Ex.: @João verificar o local e retornar até 15h"/><button className="button primary">Adicionar comentário</button></form></section><section className="task-history"><h3>Linha do tempo</h3>{selectedTask.history.map((entry,index)=><div key={`${entry.at}-${index}`}><History size={13}/><span><strong>{entry.action}</strong><small>{dateLabel(entry.at)}</small></span></div>)}</section></div></IntegratedModal>}
  </section>;
}
