import { permissionFor, type DepartmentPermissionSettings, type PermissionModule } from './access-control';

export type RecordKind = 'ticket' | 'task' | 'process' | 'document' | 'event' | 'request';
export type RecordRef = { kind: RecordKind; id: string };
export type DirectoryRecord = RecordRef & { title: string; department: string; ownerId?: string; status?: string; dueAt?: string; reviewIds?: string[] };
export type OperationUser = { id: string; fullName: string; department: string; role: string; email?: string; status?: string };
export type OperationActor = OperationUser & { principal: string; manager: boolean; executive: boolean; settings?: DepartmentPermissionSettings };
export type ActivityEntry = { id: string; at: string; actorId: string; actorName: string; principal: string; department: string; action: string; text: string; internal?: boolean };
export type WorkCalendar = { department: string; weekdays: number[]; holidays: string[]; starts: string; ends: string; updatedAt: string };
export type Transfer = { id: string; ticketId: string; title: string; from: string; to: string; reason: string; status: 'Enviado' | 'Recebido' | 'Em atendimento' | 'Complemento solicitado' | 'Cancelado'; assigneeId?: string; dueAt?: string; createdAt: string; receivedAt?: string; response?: string };
export type TicketWork = { id: string; department: string; status?: string; dueDate?: string | null; assigneeId?: string; history: ActivityEntry[]; checklist: { id: string; label: string; done: boolean }[]; pause?: { at: string; reason: string }; pausedMs: number };
export type ServiceField = { id: string; label: string; required: boolean; type: 'text' | 'number' | 'date' };
export type ApprovalStage = { id: string; name: string; userId: string; requiredDocuments: string[]; conditionField?: string; conditionValue?: string };
export type ServiceDefinition = { id: string; title: string; description: string; department: string; fields: ServiceField[]; requiredDocuments: string[]; days: number; businessDays: boolean; stages: ApprovalStage[]; enabled: boolean; revision: number };
export type ServiceRequest = { id: string; title: string; serviceId: string; definition: ServiceDefinition; department: string; requesterId: string; values: Record<string,string>; documents: Record<string,string>; stages: ApprovalStage[]; stage: number; status: 'Em análise' | 'Complemento solicitado' | 'Aprovado' | 'Recusado'; dueAt: string; calendar: WorkCalendar; history: ActivityEntry[]; createdAt: string };
export type Delegation = { id: string; department: string; ownerId: string; substituteId: string; duties: ('approvals' | 'receipts' | 'reservations')[]; startsAt: string; endsAt: string; revokedAt?: string };
export type Resource = { id: string; name: string; department: string; kind: 'Sala' | 'Veículo' | 'Equipamento'; ownerId: string; approval: boolean; enabled: boolean };
export type Reservation = { id: string; resourceId: string; requesterId: string; department: string; startsAt: string; endsAt: string; purpose: string; status: 'Pendente' | 'Aprovada' | 'Recusada' | 'Cancelada'; history: ActivityEntry[] };
export type SavedFilter = { id: string; name: string; ownerId: string; department: string; shared: boolean; preferences: Record<string,unknown> };
export type RecordLink = { id: string; from: RecordRef; to: RecordRef; department: string; createdBy: string; createdAt: string };
export type OperationsState = { revision: number; tickets: Record<string,TicketWork>; transfers: Transfer[]; services: ServiceDefinition[]; requests: ServiceRequest[]; delegations: Delegation[]; resources: Resource[]; reservations: Reservation[]; calendars: WorkCalendar[]; filters: SavedFilter[]; links: RecordLink[]; audit: ActivityEntry[]; commands: string[] };
export type OperationContext = { actor: OperationActor; department: string; users: OperationUser[]; departments: string[]; records: DirectoryRecord[]; now: string };
export type OperationCommand = { id: string; type: string; data: Record<string,unknown> };
export const emptyOperations = (): OperationsState => ({ revision: 0, tickets: {}, transfers: [], services: [], requests: [], delegations: [], resources: [], reservations: [], calendars: [], filters: [], links: [], audit: [], commands: [] });
export const normalizeOperation = (v: string) => v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
export const sameSector = (a: string,b: string) => normalizeOperation(a) === normalizeOperation(b);
export class OperationError extends Error { constructor(message: string, public status = 400) { super(message); } }
function requireThat(value: unknown, message: string, status = 400): asserts value { if (!value) throw new OperationError(message,status); }
const text = (value: unknown, max = 3000) => typeof value === 'string' ? value.trim().slice(0,max) : '';
const values = (value: unknown) => Array.isArray(value) ? value : [];
function date(value: unknown) { const v = text(value,50); requireThat(v && Number.isFinite(Date.parse(v)), 'Informe uma data válida.'); return new Date(v).toISOString(); }
const sameRef = (a: RecordRef,b: RecordRef) => a.kind === b.kind && a.id === b.id;
export const recordKey = (r: RecordRef) => `${r.kind}:${r.id}`;
export function defaultCalendar(department: string): WorkCalendar { return {department, weekdays:[1,2,3,4,5], holidays:[], starts:'08:00', ends:'17:00', updatedAt:''}; }
// Municipal civil time. Fixed São Paulo UTC−03:00 is represented explicitly at the date boundary.
export function calculateDeadline(start: string, days: number, business: boolean, calendar: WorkCalendar) {
  requireThat(Number.isInteger(days) && days >= 0 && days <= 365, 'O prazo deve ser de 0 a 365 dias.');
  requireThat(calendar.weekdays.length > 0, 'Configure ao menos um dia de expediente.');
  const civil = new Date(Date.parse(start)-3*3600000).toISOString().slice(0,10);
  const cursor = new Date(`${civil}T12:00:00Z`);
  let remaining = days, guard = 0;
  const working = () => calendar.weekdays.includes(cursor.getUTCDay()) && !calendar.holidays.includes(cursor.toISOString().slice(0,10));
  while (remaining > 0 || (business && !working())) { requireThat(guard++ < 2000,'Não foi possível calcular o prazo. Revise o calendário.'); cursor.setUTCDate(cursor.getUTCDate()+1); if (!business || working()) remaining = Math.max(0,remaining-1); }
  let result = new Date(`${cursor.toISOString().slice(0,10)}T${calendar.ends}:00-03:00`).toISOString();
  if (Date.parse(result) < Date.parse(start)) { do { cursor.setUTCDate(cursor.getUTCDate()+1); } while (business && !working()); result = new Date(`${cursor.toISOString().slice(0,10)}T${calendar.ends}:00-03:00`).toISOString(); }
  return result;
}
export function intervalsOverlap(a: { startsAt: string; endsAt: string }, b: { startsAt: string; endsAt: string }) { return Date.parse(a.startsAt)<Date.parse(b.endsAt) && Date.parse(a.endsAt)>Date.parse(b.startsAt); }
export function delegationAllows(s: OperationsState, actor: OperationActor, ownerId: string, duty: Delegation['duties'][number], now: string) { return s.delegations.some(d=>d.ownerId===ownerId && d.substituteId===actor.id && sameSector(d.department,actor.department) && d.duties.includes(duty) && !d.revokedAt && Date.parse(d.startsAt)<=Date.parse(now) && Date.parse(now)<Date.parse(d.endsAt)); }
export function canOperate(actor: OperationActor, department: string, module: PermissionModule, action: 'view'|'register'|'edit') { return (sameSector(actor.department,department) || actor.executive && action==='view') && permissionFor(module,actor.manager,actor.id,actor.settings)[action]; }
function moduleFor(kind: RecordKind): PermissionModule { return ({ticket:'Chamados', task:'Central Integrada', process:'Processos Digitais', document:'Anexos e Arquivos', event:'Próximos Eventos', request:'Central Integrada'} as const)[kind]; }
export function visibleRecords(s: OperationsState,c: OperationContext) { return c.records.map(r=>r.kind==='ticket' && s.tickets[r.id] ? {...r,department:s.tickets[r.id].department,status:s.tickets[r.id].status??r.status,dueAt:s.tickets[r.id].dueDate??r.dueAt,ownerId:s.tickets[r.id].assigneeId??r.ownerId}:r).filter(r=>sameSector(r.department,c.department) && canOperate(c.actor,r.department,moduleFor(r.kind),'view')); }
export function scopedOperations(s: OperationsState,c: OperationContext): OperationsState {
  const sector=(d:string)=>sameSector(d,c.department); const manager=c.actor.manager;
  const records=visibleRecords(s,c); const ticketIds=new Set(records.filter(r=>r.kind==='ticket').map(r=>r.id));
  const requests=s.requests.filter(r=>sector(r.department)&&canOperate(c.actor,r.department,'Central Integrada','view'));
  const allowed=(r:RecordRef)=>r.kind==='request'?requests.some(x=>x.id===r.id):records.some(x=>sameRef(x,r));
  const central=canOperate(c.actor,c.department,'Central Integrada','view'),ticketAccess=canOperate(c.actor,c.department,'Chamados','view');
  return {...s,
    tickets:Object.fromEntries(Object.entries(s.tickets).filter(([id])=>ticketIds.has(id)).map(([id,w])=>[id,{...w,history:w.history.filter(h=>!h.internal||sector(h.department))}])),
    transfers:ticketAccess?s.transfers.filter(t=>sector(t.from)||sector(t.to)):[],
    services:central?s.services.filter(r=>sector(r.department)):[],requests,
    resources:central?s.resources.filter(r=>sector(r.department)):[],reservations:central?s.reservations.filter(r=>sector(r.department)):[],
    calendars:central?s.calendars.filter(r=>sector(r.department)):[],
    delegations:central?s.delegations.filter(d=>sector(d.department)&&(manager||d.ownerId===c.actor.id||d.substituteId===c.actor.id)):[],
    filters:ticketAccess?s.filters.filter(f=>sector(f.department)&&(f.shared||f.ownerId===c.actor.id)):[],
    links:s.links.filter(l=>allowed(l.from)&&allowed(l.to)),audit:manager?s.audit.filter(h=>sector(h.department)):[],commands:[]};
}
export function applyOperation(original: OperationsState, command: OperationCommand, c: OperationContext): OperationsState {
  requireThat(/^[a-zA-Z0-9-]{8,100}$/.test(command.id),'Identificador de ação inválido.');
  if(original.commands.includes(command.id)) return original;
  const s=structuredClone(original), d=command.data, a=c.actor;
  const uid=(suffix:string)=>`${command.id}-${suffix}`;
  const entry=(action:string,body:string,internal=false):ActivityEntry=>({id:uid(`h-${action}`),at:c.now,actorId:a.id,actorName:a.fullName,principal:a.principal,department:c.department,action,text:body,internal});
  const permit=(module:PermissionModule,action:'view'|'register'|'edit'='edit',department=c.department)=>requireThat(canOperate(a,department,module,action),'Seu perfil não pode executar esta ação neste setor.',403);
  const manage=()=>{permit('Central Integrada');requireThat(a.manager,'Somente a gestão do setor pode configurar esta rotina.',403);};
  const user=(id:unknown)=>{const u=c.users.find(u=>u.id===id && sameSector(u.department,c.department) && !['inactive','inativo','disabled'].includes(normalizeOperation(u.status||'')));requireThat(u,'Selecione uma pessoa ativa deste setor.');return u;};
  const findRecord=(ref:unknown):DirectoryRecord=>{const r=ref as RecordRef;requireThat(r&&typeof r.id==='string','Registro inválido.');const found=visibleRecords(s,c).find(x=>sameRef(x,r))??s.requests.filter(x=>sameSector(x.department,c.department)).map(x=>({kind:'request' as const,id:x.id,title:x.title,department:x.department})).find(x=>sameRef(x,r));requireThat(found,'Registro inexistente ou sem acesso.',404);return found;};
  const work=()=>{const r=findRecord({kind:'ticket',id:d.ticketId});permit('Chamados','edit',r.department);return s.tickets[r.id]??(s.tickets[r.id]={id:r.id,department:r.department,history:[],checklist:[],pausedMs:0});};
  let summary='';
  switch(command.type) {
    case 'ticket.note': {const w=work();const body=text(d.text);requireThat(body,'Escreva a mensagem.');w.history.push(entry(d.internal?'Anotação interna':'Mensagem',body,d.internal===true));summary='Atualização registrada no chamado.';break;}
    case 'ticket.checklist': {const w=work();requireThat(d.expectedHistoryLength===w.history.length,'O chamado recebeu outra atualização. Atualize antes de alterar o checklist.',409); const items=values(d.items);requireThat(items.length<=40,'Limite de 40 etapas.');w.checklist=items.map((v,i)=>{const x=v as {id?:string;label?:string;done?:boolean};const label=text(x.label,240);requireThat(label,'Nome da etapa obrigatório.');return{id:text(x.id,120)||uid(`check-${i}`),label,done:x.done===true};});w.history.push(entry('Checklist',`${w.checklist.filter(x=>x.done).length} de ${w.checklist.length} etapas concluídas.`));summary='Checklist atualizado.';break;}
    case 'ticket.status': {const w=work();const status=text(d.status,80);requireThat(['Recebido','Em análise','Aguardando aprovação','Em execução','Aguardando resposta','Concluído','Cancelado'].includes(status),'Etapa inválida.');requireThat(!w.pause || !['Concluído','Cancelado'].includes(status),'Retome o prazo antes de encerrar.');w.status=status;w.history.push(entry('Status',status));summary=`Chamado: ${status}.`;break;}
    case 'ticket.pause': {const w=work();requireThat(!w.pause,'O prazo já está pausado.',409);const reason=text(d.reason);requireThat(reason.length>=5,'Informe o motivo da pausa.');w.pause={at:c.now,reason};w.history.push(entry('Prazo pausado',reason));summary='Prazo pausado com justificativa.';break;}
    case 'ticket.resume': {const w=work();requireThat(w.pause,'O prazo não está pausado.',409);const elapsed=Math.max(0,Date.parse(c.now)-Date.parse(w.pause.at));const r=findRecord({kind:'ticket',id:w.id});const due=w.dueDate??r.dueAt;if(due)w.dueDate=new Date(Date.parse(due)+elapsed).toISOString();w.pausedMs+=elapsed;w.history.push(entry('Prazo retomado',`Pausa: ${Math.round(elapsed/60000)} minutos. ${w.pause.reason}`));delete w.pause;summary='Prazo retomado e compensado.';break;}
    case 'ticket.forward': {const w=work(); const to=c.departments.find(x=>sameSector(x,text(d.to)));requireThat(to&&!sameSector(to,w.department),'Selecione outro setor.');requireThat(!s.transfers.some(t=>t.ticketId===w.id&&['Enviado','Complemento solicitado','Recebido'].includes(t.status)),'Já existe um encaminhamento pendente.',409);const reason=text(d.reason);requireThat(reason.length>=5,'Informe o motivo do encaminhamento.');const r=findRecord({kind:'ticket',id:w.id});s.transfers.unshift({id:uid('transfer'),ticketId:w.id,title:r.title,from:w.department,to,reason,status:'Enviado',createdAt:c.now});w.history.push(entry('Encaminhamento enviado',`${to}: ${reason}`));summary='Encaminhamento enviado, aguardando recebimento.';break;}
    case 'transfer.respond': {permit('Chamados');requireThat(['accept','complement','start'].includes(String(d.decision)),'Decisão inválida.'); const t=s.transfers.find(t=>t.id===d.id);requireThat(t&&sameSector(t.to,c.department),'Encaminhamento não disponível neste setor.',404);requireThat(['Enviado','Complemento solicitado','Recebido'].includes(t.status),'Este encaminhamento já foi tratado.',409);const response=text(d.response);if(d.decision==='complement'){requireThat(t.status!=='Recebido','O chamado já foi recebido.');requireThat(response.length>=5,'Informe o complemento necessário.');t.status='Complemento solicitado';t.response=response;} else if(d.decision==='start'){requireThat(t.status==='Recebido','Confirme o recebimento primeiro.');t.status='Em atendimento';s.tickets[t.ticketId].status='Em execução';} else {requireThat(t.status!=='Recebido','Recebimento já confirmado.',409);const owner=user(d.assigneeId);t.assigneeId=owner.id;t.dueAt=date(d.dueAt);requireThat(Date.parse(t.dueAt)>Date.parse(c.now),'O prazo precisa ser futuro.');t.status='Recebido';t.receivedAt=c.now;const w=s.tickets[t.ticketId];w.department=t.to;w.assigneeId=owner.id;w.dueDate=t.dueAt;w.status='Recebido';}s.tickets[t.ticketId].history.push(entry(t.status,response||`${t.to} · ${t.assigneeId?c.users.find(u=>u.id===t.assigneeId)?.fullName:''}`));summary=`Encaminhamento: ${t.status}.`;break;}
    case 'transfer.supplement': {permit('Chamados');const t=s.transfers.find(t=>t.id===d.id&&sameSector(t.from,c.department));requireThat(t&&t.status==='Complemento solicitado','Não há pedido de complemento pendente.',409);const response=text(d.response);requireThat(response.length>=5,'Informe o complemento.');t.reason+=`\nComplemento: ${response}`;t.status='Enviado';t.response=undefined;s.tickets[t.ticketId].history.push(entry('Complemento enviado',response));summary='Complemento enviado ao destino.';break;}
    case 'filter.save': {permit('Chamados','register');const name=text(d.name,80);requireThat(name,'Dê um nome ao filtro.');const old=s.filters.find(f=>f.id===d.id);requireThat(!old||old.ownerId===a.id,'Apenas o autor pode editar o filtro.',403);const p=(d.preferences??{}) as Record<string,unknown>;requireThat(JSON.stringify(p).length<6000,'Filtro muito grande.');requireThat(typeof p.query==='string'&&p.query.length<=300,'Busca inválida.');requireThat(['board','table'].includes(String(p.viewMode)),'Visualização inválida.');requireThat(['Todos','Urgentes','Atrasados','Minha equipe','Sem responsável'].includes(String(p.savedView)),'Filtro rápido inválido.');requireThat(['Todas','Urgente','Alta','Média','Baixa'].includes(String(p.priority)),'Prioridade inválida.');requireThat(['Todos','Recebido','Em análise','Aguardando aprovação','Em execução','Aguardando resposta','Concluído','Cancelado'].includes(String(p.status)),'Status inválido.');requireThat(Array.isArray(p.columns)&&p.columns.length>0&&p.columns.every(v=>['protocol','department','status','due','assignee'].includes(v)),'Colunas inválidas.');const preferences={viewMode:p.viewMode,savedView:p.savedView,query:p.query,priority:p.priority,status:p.status,columns:[...new Set(p.columns)]};const value:SavedFilter={id:old?.id??uid('filter'),name,ownerId:a.id,department:c.department,shared:d.shared===true,preferences};s.filters=s.filters.filter(f=>f.id!==value.id);s.filters.push(value);summary='Visualização salva.';break;}
    case 'filter.delete': {permit('Chamados');const f=s.filters.find(f=>f.id===d.id);requireThat(f&&f.ownerId===a.id,'Filtro não disponível para exclusão.',403);s.filters=s.filters.filter(x=>x.id!==f.id);summary='Visualização removida.';break;}
    case 'calendar.save': {manage();const weekdays=values(d.weekdays).filter(v=>typeof v==='number'&&Number.isInteger(v)&&v>=0&&v<=6) as number[];requireThat(weekdays.length,'Selecione ao menos um dia.');const starts=text(d.starts),ends=text(d.ends);requireThat(/^([01]\d|2[0-3]):[0-5]\d$/.test(starts)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(ends)&&starts<ends&&ends<='23:59','Horário de expediente inválido.');const holidays=values(d.holidays).map(x=>text(x,10));requireThat(holidays.length<=370&&holidays.every(h=>/^\d{4}-\d{2}-\d{2}$/.test(h)&&Number.isFinite(Date.parse(`${h}T12:00:00Z`))&&new Date(`${h}T12:00:00Z`).toISOString().slice(0,10)===h),'Datas de feriados inválidas.');s.calendars=s.calendars.filter(x=>!sameSector(x.department,c.department));s.calendars.push({department:c.department,weekdays:[...new Set(weekdays)],holidays,starts,ends,updatedAt:c.now});summary='Calendário atualizado para os próximos registros.';break;}
    case 'service.save': {manage();const old=s.services.find(x=>x.id===d.id);requireThat(!old||sameSector(old.department,c.department),'Serviço fora do setor.',403);const title=text(d.title,150);requireThat(title.length>=3,'Nome do serviço obrigatório.');const fields=values(d.fields).slice(0,20).map((v,i)=>{const f=v as ServiceField;requireThat(text(f.label,120),'Nome do campo obrigatório.');return{id:text(f.id,80)||uid(`field-${i}`),label:text(f.label,120),required:f.required===true,type:['text','number','date'].includes(f.type)?f.type:'text'} as ServiceField;});const stages=values(d.stages).slice(0,10).map((v,i)=>{const f=v as ApprovalStage;user(f.userId);requireThat(text(f.name,120),'Nome da etapa obrigatório.');if(f.conditionField)requireThat(fields.some(x=>x.id===f.conditionField),'Campo da condição inválido.');return{id:uid(`stage-${i}`),name:text(f.name,120),userId:f.userId,requiredDocuments:values(f.requiredDocuments).map(x=>text(x,100)).filter(Boolean),conditionField:text(f.conditionField,80)||undefined,conditionValue:text(f.conditionValue,200)||undefined};});const days=Number(d.days);calculateDeadline(c.now,days,true,defaultCalendar(c.department));const value:ServiceDefinition={id:old?.id??uid('service'),title,description:text(d.description),department:c.department,fields,requiredDocuments:values(d.requiredDocuments).slice(0,20).map(x=>text(x,100)).filter(Boolean),days,businessDays:d.businessDays!==false,stages,enabled:d.enabled!==false,revision:(old?.revision??0)+1};s.services=s.services.filter(x=>x.id!==value.id);s.services.push(value);summary='Serviço e fluxo de aprovação salvos.';break;}
    case 'request.create': {permit('Central Integrada','register');const definition=s.services.find(x=>x.id===d.serviceId&&x.enabled&&sameSector(x.department,c.department));requireThat(definition,'Serviço indisponível.');const input=(d.values??{}) as Record<string,unknown>, submitted=Object.fromEntries(definition.fields.map(f=>{const value=text(input[f.id]);requireThat(!f.required||value,`Preencha: ${f.label}.`);if(value&&f.type==='number')requireThat(Number.isFinite(Number(value)),`Número inválido: ${f.label}.`);if(value&&f.type==='date')date(value);return[f.id,value];}));const docs=(d.documents??{}) as Record<string,string>;requireThat(typeof docs==='object'&&!Array.isArray(docs)&&Object.keys(docs).length<=30,'Documentos inválidos.');for(const documentId of Object.values(docs))findRecord({kind:'document',id:documentId});for(const label of definition.requiredDocuments){requireThat(docs[label],`Vincule o documento: ${label}.`);findRecord({kind:'document',id:docs[label]});}const stages=definition.stages.filter(x=>!x.conditionField||submitted[x.conditionField]===x.conditionValue);const calendar=s.calendars.find(x=>sameSector(x.department,c.department))??defaultCalendar(c.department);s.requests.unshift({id:uid('request'),title:text(d.title,180)||definition.title,serviceId:definition.id,definition:structuredClone(definition),department:c.department,requesterId:a.id,values:submitted,documents:docs,stages,stage:0,status:stages.length?'Em análise':'Aprovado',dueAt:calculateDeadline(c.now,definition.days,definition.businessDays,calendar),calendar:structuredClone(calendar),history:[entry('Solicitação registrada',definition.title)],createdAt:c.now});summary='Solicitação registrada com o fluxo e o calendário vigentes.';break;}
    case 'request.document': {permit('Central Integrada');const r=s.requests.find(x=>x.id===d.id&&sameSector(x.department,c.department));requireThat(r&&['Em análise','Complemento solicitado'].includes(r.status),'Solicitação encerrada ou indisponível.',409);findRecord({kind:'document',id:d.documentId});const label=text(d.label,100);requireThat(label,'Identifique o documento.');r.documents[label]=text(d.documentId,150);r.history.push(entry('Documento vinculado',label));summary='Documento vinculado.';break;}
    case 'request.decide': {permit('Central Integrada','view');const r=s.requests.find(x=>x.id===d.id&&sameSector(x.department,c.department));requireThat(r&&['Em análise','Complemento solicitado'].includes(r.status),'Solicitação já tratada ou indisponível.',409);const stage=r.stages[r.stage];requireThat(stage,'Etapa inválida.');requireThat(d.expectedStageId===stage.id,'A etapa foi atualizada por outra pessoa. Revise antes de decidir.',409);requireThat(stage.userId===a.id||delegationAllows(s,a,stage.userId,'approvals',c.now),'Esta etapa está atribuída a outra pessoa.',403);const note=text(d.note);requireThat(note.length>=3,'Registre o parecer da decisão.');if(d.decision==='approve'){for(const label of stage.requiredDocuments){requireThat(r.documents[label],`Documento pendente: ${label}.`);findRecord({kind:'document',id:r.documents[label]});}r.stage++;r.status=r.stage>=r.stages.length?'Aprovado':'Em análise';}else if(d.decision==='reject')r.status='Recusado';else if(d.decision==='complement')r.status='Complemento solicitado';else throw new OperationError('Decisão inválida.');r.history.push(entry(`${stage.name}: ${r.status}`,`${note}${stage.userId!==a.id?' · em substituição temporária':''}`));summary='Decisão registrada.';break;}
    case 'request.resubmit': {permit('Central Integrada');const r=s.requests.find(x=>x.id===d.id&&sameSector(x.department,c.department));requireThat(r&&r.status==='Complemento solicitado','Não há complemento solicitado.',409);const note=text(d.note);requireThat(note.length>=3,'Informe o complemento.');r.status='Em análise';r.history.push(entry('Complemento apresentado',note));summary='Solicitação devolvida à análise.';break;}
    case 'delegation.save': {manage();const owner=user(d.ownerId),sub=user(d.substituteId);requireThat(owner.id!==sub.id,'Escolha pessoas diferentes.');const startsAt=date(d.startsAt),endsAt=date(d.endsAt);requireThat(startsAt<endsAt&&Date.parse(endsAt)>Date.parse(c.now)&&Date.parse(endsAt)-Date.parse(startsAt)<=90*86400000,'A substituição deve ter término futuro e durar até 90 dias.');const duties=values(d.duties).filter(x=>['approvals','reservations'].includes(String(x))) as Delegation['duties'];requireThat(duties.length,'Escolha as atribuições.');requireThat(!s.delegations.some(x=>!x.revokedAt&&x.ownerId===owner.id&&intervalsOverlap(x,{startsAt,endsAt})),'Já existe uma substituição neste período.',409);s.delegations.push({id:uid('delegation'),department:c.department,ownerId:owner.id,substituteId:sub.id,duties,startsAt,endsAt});summary=`Substituição de ${owner.fullName} registrada.`;break;}
    case 'delegation.revoke': {manage();const item=s.delegations.find(x=>x.id===d.id&&sameSector(x.department,c.department));requireThat(item,'Substituição não encontrada.',404);item.revokedAt=c.now;summary='Substituição revogada.';break;}
    case 'resource.save': {manage();const owner=user(d.ownerId);const old=s.resources.find(x=>x.id===d.id);requireThat(!old||sameSector(old.department,c.department),'Recurso fora do setor.',403);const name=text(d.name,160);requireThat(name.length>=3,'Nome do recurso obrigatório.');requireThat(['Sala','Veículo','Equipamento'].includes(String(d.kind)),'Tipo inválido.');const item:Resource={id:old?.id??uid('resource'),name,department:c.department,kind:d.kind as Resource['kind'],ownerId:owner.id,approval:d.approval!==false,enabled:d.enabled!==false};s.resources=s.resources.filter(x=>x.id!==item.id);s.resources.push(item);summary='Recurso salvo.';break;}
    case 'reservation.create': {permit('Central Integrada','register');const r=s.resources.find(x=>x.id===d.resourceId&&x.enabled&&sameSector(x.department,c.department));requireThat(r,'Recurso indisponível.');const startsAt=date(d.startsAt),endsAt=date(d.endsAt);requireThat(startsAt<endsAt&&Date.parse(startsAt)>=Date.parse(c.now),'Informe um intervalo futuro válido.');const purpose=text(d.purpose);requireThat(purpose.length>=3,'Informe a finalidade.');requireThat(!s.reservations.some(x=>x.resourceId===r.id&&['Pendente','Aprovada'].includes(x.status)&&intervalsOverlap(x,{startsAt,endsAt})),'Este recurso já está reservado no período.',409);s.reservations.unshift({id:uid('reservation'),resourceId:r.id,requesterId:a.id,department:c.department,startsAt,endsAt,purpose,status:r.approval?'Pendente':'Aprovada',history:[entry('Reserva solicitada',purpose)]});summary=r.approval?'Reserva enviada para aprovação.':'Reserva confirmada.';break;}
    case 'reservation.decide': {permit('Central Integrada','view');const r=s.reservations.find(x=>x.id===d.id&&sameSector(x.department,c.department));requireThat(r,'Reserva não encontrada.',404);const resource=s.resources.find(x=>x.id===r.resourceId)!;if(d.decision==='cancel'){requireThat(r.requesterId===a.id||resource.ownerId===a.id,'Apenas solicitante ou responsável podem cancelar.',403);requireThat(['Pendente','Aprovada'].includes(r.status),'Reserva já encerrada.',409);r.status='Cancelada';}else {requireThat(resource.ownerId===a.id||delegationAllows(s,a,resource.ownerId,'reservations',c.now),'Aprovação atribuída ao responsável pelo recurso.',403);requireThat(r.status==='Pendente','Reserva já tratada.',409);requireThat(['approve','reject'].includes(String(d.decision)),'Decisão inválida.');if(d.decision==='approve')requireThat(!s.reservations.some(x=>x.id!==r.id&&x.resourceId===r.resourceId&&['Pendente','Aprovada'].includes(x.status)&&intervalsOverlap(x,r)),'Conflito de horário.',409);r.status=d.decision==='approve'?'Aprovada':'Recusada';}r.history.push(entry(`Reserva ${r.status.toLowerCase()}`,text(d.note)||r.purpose));summary=`Reserva ${r.status.toLowerCase()}.`;break;}
    case 'link.create': {permit('Central Integrada','register');const from=findRecord(d.from),to=findRecord(d.to);requireThat(!sameRef(from,to),'Escolha registros diferentes.');requireThat(!s.links.some(l=>sameRef(l.from,from)&&sameRef(l.to,to)||sameRef(l.from,to)&&sameRef(l.to,from)),'Registros já vinculados.',409);s.links.push({id:uid('link'),from:{kind:from.kind,id:from.id},to:{kind:to.kind,id:to.id},department:c.department,createdBy:a.id,createdAt:c.now});summary='Registros vinculados.';break;}
    case 'link.delete': {permit('Central Integrada');const l=s.links.find(x=>x.id===d.id);requireThat(l,'Vínculo não encontrado.',404);findRecord(l.from);findRecord(l.to);s.links=s.links.filter(x=>x.id!==l.id);summary='Vínculo removido.';break;}
    default: throw new OperationError('Ação desconhecida.');
  }
  s.revision=original.revision+1;s.commands.push(command.id);s.audit.push(entry(command.type,summary));return s;
}
