"use client";
import { useState, type FormEvent, type ReactNode } from 'react';
import { ArrowUpRight, Check, CheckCircle2, ClipboardList, Clock3, Copy, Link2, Plus, RefreshCw, Send, ShieldCheck, Sparkles, X } from 'lucide-react';
import { useOperations, recordHref } from './operations-context';
import { recordKey, type RecordRef } from './operations-model';
const kindLabel={ticket:'Chamado',task:'Tarefa',process:'Processo',document:'Documento',event:'Evento',request:'Solicitação'};
export const operationDate=(v?:string)=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}):'Sem prazo';
export const formValue=(f:FormData,k:string)=>String(f.get(k)||'').trim();
export function OperationsNotice(){const o=useOperations();return o.error?<div className="op-notice" role="alert"><ShieldCheck size={18}/><span>{o.error}</span><button type="button" onClick={()=>void o.refresh()}><RefreshCw size={14}/> Atualizar</button></div>:!o.ready?<p className="op-muted" role="status">Carregando registros compartilhados…</p>:null;}
export function OperationEmpty({children}:{children:ReactNode}){return <div className="op-empty"><CheckCircle2 size={24}/><p>{children}</p></div>;}
export function RecordActions({record, current=false}:{record:RecordRef;current?:boolean}){const o=useOperations();const[copied,setCopied]=useState(false);return <span className="op-actions">{!current&&<button type="button" onClick={()=>o.openRecord(record)}>Abrir <ArrowUpRight size={14}/></button>}<button type="button" aria-label="Copiar link interno" onClick={()=>void navigator.clipboard.writeText(recordHref(record,o.department)).then(()=>setCopied(true)).catch(()=>setCopied(false))}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copiado':'Copiar link'}</button></span>;}
export function RelatedRecords({record}:{record:RecordRef}){const o=useOperations();const[target,setTarget]=useState('');const all=[...o.records,...o.state.requests.map(r=>({kind:'request' as const,id:r.id,title:r.title,department:r.department}))];const related=o.state.links.filter(l=>recordKey(l.from)===recordKey(record)||recordKey(l.to)===recordKey(record));return <section className="op-related"><header><h3><Link2 size={17}/> Registros relacionados</h3></header>{related.map(l=>{const ref=recordKey(l.from)===recordKey(record)?l.to:l.from;const r=all.find(r=>recordKey(r)===recordKey(ref));return r?<div className="op-row" key={l.id}><span><small>{kindLabel[r.kind]}</small><strong>{r.title}</strong></span><RecordActions record={ref}/>{!o.readOnly&&<button type="button" aria-label={`Remover vínculo com ${r.title}`} disabled={o.busy} onClick={()=>void o.act('link.delete',{id:l.id})}><X size={14}/></button>}</div>:null;})}{!related.length&&<p className="op-muted">Nenhum vínculo neste registro.</p>}{!o.readOnly&&<form className="op-inline-form" onSubmit={async e=>{e.preventDefault();const r=all.find(r=>recordKey(r)===target);if(r&&await o.act('link.create',{from:record,to:{kind:r.kind,id:r.id}}))setTarget('');}}><label><span>Vincular registro</span><select value={target} onChange={e=>setTarget(e.target.value)} required><option value="">Selecione um registro do setor</option>{all.filter(r=>recordKey(r)!==recordKey(record)).map(r=><option key={recordKey(r)} value={recordKey(r)}>{r.title} · {kindLabel[r.kind]}</option>)}</select></label><button className="button secondary" disabled={!target||o.busy||!o.ready}><Link2 size={15}/> Vincular</button></form>}</section>;}
export function SavedTicketFilters({preferences,onApply}:{preferences:Record<string,unknown>;onApply:(p:Record<string,unknown>)=>void}){const o=useOperations();const[open,setOpen]=useState(false);const[name,setName]=useState(''),[shared,setShared]=useState(false);return <div className="op-saved-views"><div className="op-actions">{o.state.filters.map(f=><button type="button" key={f.id} title={f.shared?'Compartilhado com o setor':'Somente meu perfil'} onClick={()=>{const p=f.preferences;if(typeof p.query==='string'&&Array.isArray(p.columns)&&p.columns.every(c=>['protocol','department','status','due','assignee'].includes(String(c))))onApply(p);}}>{f.name}{f.shared&&<ShieldCheck size={12}/>}</button>)}<button type="button" onClick={()=>setOpen(!open)}><Plus size={14}/> Salvar visualização</button></div>{open&&<form className="op-inline-form" onSubmit={async e=>{e.preventDefault();if(await o.act('filter.save',{name,shared,preferences})){setOpen(false);setName('');}}}><label>Nome<input maxLength={80} required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Urgentes da equipe"/></label><label className="op-check"><input type="checkbox" checked={shared} onChange={e=>setShared(e.target.checked)}/> Compartilhar com o setor</label><button className="button primary" disabled={o.busy||!o.ready||o.readOnly}>Salvar filtros e colunas</button>{o.state.filters.filter(f=>f.ownerId===o.actorId).map(f=><button key={f.id} type="button" onClick={()=>void o.act('filter.delete',{id:f.id})}>Excluir “{f.name}”</button>)}</form>}</div>;}
type DetailTicket={id:string;protocol:string;title:string;description:string;department:string;requester:string;status:string;priority:string;dueDate:string|null;createdAt:string;assigneeName?:string;address?:string;neighborhood?:string};
export function OperationalTicketDetail({ticket,onClose}:{ticket:DetailTicket;onClose:()=>void}) {
  const o=useOperations(),w=o.state.tickets[ticket.id];const[note,setNote]=useState(''),[internal,setInternal]=useState(false),[step,setStep]=useState('');const[aiBusy,setAiBusy]=useState(false),[aiText,setAiText]=useState(''),[aiKind,setAiKind]=useState('summary'),[aiError,setAiError]=useState('');
  const locked=o.readOnly||!o.ready||o.busy;const checklist=w?.checklist??[];
  const ticketRecord=o.records.find(r=>r.kind==='ticket'&&r.id===ticket.id);const currentStatus=w?.status??ticket.status;
  const fullHistory=[{id:'created',at:ticket.createdAt,actorName:ticket.requester,action:'Chamado registrado',text:ticket.protocol,internal:false,department:ticket.department},...(w?.history??[])];
  async function ai(kind:'summary'|'reply'|'checklist'){setAiKind(kind);setAiBusy(true);setAiError('');try{const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation:kind==='summary'?'summarize':'draft',kind:kind==='checklist'?'checklist':'citizen_response',text:`${ticket.title}\n${ticket.description}\n${currentStatus}`,context:{protocol:ticket.protocol,department:ticket.department}})});const p=await r.json() as {text?:string};if(!r.ok||!p.text)throw new Error('Não foi possível obter a sugestão.');if(kind==='reply')setNote(p.text);else if(kind==='checklist'){setAiText(p.text);}else setAiText(p.text);}catch(e){setAiError(e instanceof Error?e.message:'IA indisponível.');}finally{setAiBusy(false);}}
  async function forward(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await o.act('ticket.forward',{ticketId:ticket.id,to:formValue(f,'to'),reason:formValue(f,'reason')}))form.reset();}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal op-ticket-modal" role="dialog" aria-modal="true" aria-labelledby="op-ticket-title" onKeyDown={e=>{if(e.key==='Escape')onClose();}}><header><div><p className="eyebrow">{ticket.protocol} · {ticket.requester}</p><h2 id="op-ticket-title">{ticket.title}</h2></div><button type="button" aria-label="Fechar chamado" onClick={onClose}><X size={20}/></button></header><div className="op-modal-body"><OperationsNotice/><div className="op-actions"><span className="op-badge">{currentStatus}</span><span className="op-badge">{ticket.priority}</span><RecordActions record={{kind:'ticket',id:ticket.id}} current/></div><p>{ticket.description}</p><div className="op-detail-facts"><div><small>Responsável</small><strong>{o.users.find(u=>u.id===w?.assigneeId)?.fullName||ticket.assigneeName||'A definir'}</strong></div><div><small>Prazo</small><strong>{w?.pause?'Prazo pausado':operationDate(w?.dueDate??ticket.dueDate??undefined)}</strong></div><div><small>Local</small><strong>{ticket.address||ticket.neighborhood||'Não informado'}</strong></div></div>
    <div className="op-actions"><button disabled={aiBusy} onClick={()=>void ai('summary')}><Sparkles size={15}/> Resumir</button><button disabled={aiBusy||locked} onClick={()=>void ai('reply')}><Sparkles size={15}/> Sugerir atualização</button><button disabled={aiBusy||locked} onClick={()=>void ai('checklist')}><Sparkles size={15}/> Sugerir checklist</button></div>{aiError&&<p role="alert">{aiError}</p>}{aiText&&<div className="op-ai-draft"><strong>Sugestão da IA · revise antes de usar</strong><p>{aiText}</p>{aiKind==='checklist'&&<button type="button" disabled={locked} onClick={async()=>{const items=aiText.split(/\n+/).map(x=>x.replace(/^\s*[-*•\d.)]+\s*/,'').trim()).filter(Boolean).slice(0,15).map((label,i)=>({id:`ai-${Date.now()}-${i}`,label,done:false}));if(await o.act('ticket.checklist',{ticketId:ticket.id,items:[...checklist,...items]}))setAiText('');}}>Adicionar como etapas</button>}</div>}
    <div className="op-two-columns"><article className="op-card"><h3><ClipboardList size={17}/> Checklist de execução</h3><p className="op-muted">{checklist.filter(i=>i.done).length} de {checklist.length} etapas concluídas</p>{checklist.map(i=><label className="op-check" key={i.id}><input type="checkbox" checked={i.done} disabled={locked} onChange={()=>void o.act('ticket.checklist',{ticketId:ticket.id,items:checklist.map(x=>x.id===i.id?{...x,done:!x.done}:x)})}/><span>{i.label}</span></label>)}<form className="op-inline-form" onSubmit={async e=>{e.preventDefault();if(await o.act('ticket.checklist',{ticketId:ticket.id,items:[...checklist,{id:crypto.randomUUID(),label:step,done:false}]}))setStep('');}}><label>Nova etapa<input value={step} onChange={e=>setStep(e.target.value)} maxLength={240} required/></label><button disabled={locked||!step.trim()} className="button secondary"><Plus size={15}/> Adicionar</button></form></article><article className="op-card"><h3>Encaminhamento com recebimento</h3><p className="op-muted">O setor atual acompanha o pedido até o destino confirmar o recebimento.</p><form className="op-form" onSubmit={forward}><label>Setor de destino<select name="to" required><option value="">Selecione</option>{o.departments.filter(d=>d!==ticket.department).map(d=><option key={d}>{d}</option>)}</select></label><label>Motivo<textarea name="reason" required minLength={5}/></label><button className="button secondary" disabled={locked}><Send size={15}/> Enviar encaminhamento</button></form>{o.state.transfers.filter(t=>t.ticketId===ticket.id).map(t=><div key={t.id} className="op-receipt"><strong>{t.status}</strong><p>{t.from} → {t.to}</p><small>{operationDate(t.receivedAt||t.createdAt)}{t.response?` · ${t.response}`:''}</small></div>)}</article></div>
    <article className="op-card"><h3>Histórico do atendimento</h3><div className="op-actions"><button type="button" aria-pressed={!internal} onClick={()=>setInternal(false)}>Mensagens e atividades</button><button type="button" aria-pressed={internal} onClick={()=>setInternal(true)}><ShieldCheck size={14}/> Anotações do setor</button></div><ol className="op-timeline">{fullHistory.filter(h=>internal?h.internal:!h.internal).map(h=><li key={h.id}><span className="op-timeline-dot"/><div><strong>{h.action}</strong><p>{h.text}</p><small>{h.actorName} · {operationDate(h.at)}</small></div></li>)}</ol>{internal&&!fullHistory.some(h=>h.internal)&&<p className="op-muted">Nenhuma anotação interna registrada.</p>}<form className="op-inline-form" onSubmit={async e=>{e.preventDefault();if(await o.act('ticket.note',{ticketId:ticket.id,text:note,internal}))setNote('');}}><label>{internal?'Nova anotação interna':'Nova atualização'}<textarea value={note} required onChange={e=>setNote(e.target.value)} maxLength={3000}/></label><button className="button primary" disabled={locked||!note.trim()}><Send size={15}/> Registrar</button></form></article>
    <RelatedRecords record={{kind:'ticket',id:ticket.id}}/>
    <details className="op-card"><summary><Clock3 size={16}/> Gestão do prazo</summary>{w?.pause?<><p>Pausado em {operationDate(w.pause.at)}: {w.pause.reason}</p><button disabled={locked} onClick={()=>void o.act('ticket.resume',{ticketId:ticket.id})}>Retomar e compensar o prazo</button></>:<form className="op-inline-form" onSubmit={e=>{e.preventDefault();void o.act('ticket.pause',{ticketId:ticket.id,reason:formValue(new FormData(e.currentTarget),'reason')});}}><label>Justificativa da pausa<input name="reason" required minLength={5}/></label><button disabled={locked} className="button secondary">Pausar prazo</button></form>}</details>
    </div><footer className="op-modal-footer"><label>Etapa atual<select value={currentStatus} disabled={locked||!ticketRecord} onChange={e=>void o.act('ticket.status',{ticketId:ticket.id,status:e.target.value})}>{['Recebido','Em análise','Aguardando aprovação','Em execução','Aguardando resposta','Concluído','Cancelado'].map(s=><option key={s}>{s}</option>)}</select></label><button type="button" className="button secondary" onClick={onClose}>Fechar</button></footer></section></div>;
}
