"use client";

import { FormEvent, useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BookOpenCheck,
  Building2,
  Check,
  CheckCircle2,
  ChevronRight,
  CalendarDays,
  TrendingUp,
  ArrowUpRight,
  ClipboardCheck,
  Clock3,
  CloudOff,
  FileText,
  Gauge,
  HeartHandshake,
  Layers3,
  ListChecks,
  LockKeyhole,
  MapPin,
  Navigation,
  Plus,
  Search,
  Send,
  ShieldCheck,
  Smartphone,
  Target,
  UsersRound,
  Wrench,
  CalendarClock,
  FileCheck2,
  Pencil,
  Save,
  Trash2,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useCurrentPermission } from "./permission-context";
import { persistenceKey, usePersistentState } from "./persistence";

type Notify = (message: string) => void;
type WorkspaceTab = "Painel setorial" | "Cadastros e formulários" | "Equipes de campo" | "Metas e indicadores" | "Encaminhamentos";
type Metric = [label: string, value: string, detail: string];
type RecordRow = [title: string, detail: string, status: string];
type SectorProfile = {
  title: string;
  mission: string;
  recordLabel: string;
  recordDescription: string;
  primaryField: string;
  secondaryField: string;
  privacy: string;
  metrics: Metric[];
  modules: string[];
  forms: string[];
  records: RecordRow[];
  mapLayers: string[];
  mapPoints: Array<[string, string, string]>;
  teams: Array<[string, string, string]>;
  goals: Array<[string, number, string]>;
};


type SectorPriority = "Urgente" | "Alta" | "Normal" | "Baixa";
type SectorRecord = { id:string; title:string; detail:string; status:string; priority:SectorPriority; owner:string; dueDate:string; category:string; updatedAt:string };
type SectorReferral = { id:string; destination:string; subject:string; scope:string; dueDate:string; status:string; note:string; createdAt:string };
type SectorGoal = { id:string; title:string; progress:number; target:string; owner:string };
type SectorActivity = { id:string; team:string; type:string; location:string; status:string; notes:string; createdAt:string };
type SectorWorkspaceState = { records:SectorRecord[]; referrals:SectorReferral[]; goals:SectorGoal[]; activities:SectorActivity[] };

const DEFAULT_PROFILE: SectorProfile = {
  title: "Gestão setorial",
  mission: "Organize os serviços, os atendimentos, as equipes e as prioridades específicas desta unidade municipal.",
  recordLabel: "registro setorial", recordDescription: "Novo registro operacional", primaryField: "Assunto principal", secondaryField: "Local ou interessado",
  privacy: "Os registros seguem as permissões do setor e preservam informações restritas.",
  metrics: [["Registros ativos","24","6 atualizados hoje"],["Dentro do prazo","91%","Meta: 90%"],["Ações de campo","8","3 em andamento"],["Concluídos no mês","42","+11% sobre julho"]],
  modules: ["Atendimentos","Planejamento","Equipes","Documentos","Agenda","Indicadores"],
  forms: ["Registro geral","Visita técnica","Relatório de atividade","Solicitação interna"],
  records: [["Demanda setorial em acompanhamento","Registro atualizado pela equipe","Em andamento"],["Planejamento mensal da unidade","Responsáveis e prazos definidos","Planejado"],["Relatório de atividade de campo","Evidências anexadas","Concluído"]],
  mapLayers: ["Atendimentos","Equipes","Equipamentos"],
  mapPoints: [["Centro","Atendimento em execução","Em andamento"],["Planalto","Visita técnica agendada","Agendado"],["Pinlar","Serviço concluído","Concluído"]],
  teams: [["Equipe de atendimento","3 servidores","Disponível"],["Equipe técnica","4 servidores","Em campo"],["Apoio administrativo","2 servidores","Na unidade"]],
  goals: [["Concluir demandas dentro do prazo",91,"Meta 90%"],["Atualizar registros prioritários",74,"Meta 85%"],["Executar agenda de campo",68,"Meta 80%"]],
};

const PROFILES: Record<string, SectorProfile> = {
  "Secretaria de Desenvolvimento Social": {
    title:"Proteção e acompanhamento social", mission:"Acompanhe famílias, benefícios, visitas e encaminhamentos, com cuidado especial para situações de vulnerabilidade.", recordLabel:"atendimento familiar", recordDescription:"Cadastrar atendimento ou acompanhamento", primaryField:"Família ou pessoa atendida", secondaryField:"Bairro, unidade ou território", privacy:"Prontuários e dados de vulnerabilidade são restritos aos profissionais autorizados; indicadores usam dados agregados.",
    metrics:[["Famílias acompanhadas","284","19 com prioridade"],["Visitas agendadas","18","7 para esta semana"],["Benefícios em análise","31","9 aguardam documento"],["Encaminhamentos","46","12 sem retorno"]],
    modules:["Prontuário familiar","Avaliação de vulnerabilidade","Visitas domiciliares","Benefícios e auxílios","Encaminhamentos","Plano de acompanhamento"],
    forms:["Atendimento familiar","Visita domiciliar","Concessão de benefício","Encaminhamento protegido","Atualização do prontuário"],
    records:[["Família 2026-0148 · acompanhamento","Visita realizada no bairro Planalto","Acompanhamento"],["Solicitação de benefício eventual","Documentação em conferência","Em análise"],["Encaminhamento para rede de saúde","Compartilhamento mínimo autorizado","Aguardando retorno"]],
    mapLayers:["Famílias acompanhadas","Visitas programadas","Unidades da rede"], mapPoints:[["Planalto","5 visitas domiciliares","Prioridade"],["Pinlar I","CRAS · 18 atendimentos hoje","Ativo"],["Barra do Guaicuí","Ação comunitária agendada","Agendado"]],
    teams:[["Equipe de referência CRAS","5 profissionais","Em atendimento"],["Equipe de visitas","3 profissionais","Em campo"],["Cadastro e benefícios","4 profissionais","Na unidade"]], goals:[["Atualizar prontuários prioritários",82,"Meta 90%"],["Obter retorno dos encaminhamentos",61,"Meta 80%"],["Executar visitas programadas",76,"Meta 85%"]],
  },
  "Secretaria de Saúde": {
    title:"Coordenação da rede municipal de saúde", mission:"Acompanhe regulação, campanhas, transportes, insumos e ocorrências das unidades sem expor dados clínicos indevidamente.", recordLabel:"registro de saúde", recordDescription:"Cadastrar ação, solicitação ou ocorrência", primaryField:"Pessoa, unidade ou campanha", secondaryField:"Unidade, destino ou território", privacy:"Dados pessoais e clínicos recebem acesso restrito; o painel gerencial apresenta somente informações agregadas.",
    metrics:[["Regulação pendente","67","14 com prioridade"],["Transportes agendados","22","6 para amanhã"],["Campanhas ativas","4","9 pontos de atendimento"],["Insumos críticos","3","Reposição solicitada"]], modules:["Regulação de consultas","Transporte para tratamento","Campanhas de saúde","Visitas domiciliares","Medicamentos e insumos","Ocorrências das unidades"], forms:["Solicitação de regulação","Transporte sanitário","Visita domiciliar","Ocorrência de unidade","Reposição de insumo"], records:[["Campanha de vacinação de agosto","Calendário em aprovação","Planejado"],["Transporte regional · rota 18/08","8 passageiros confirmados","Agendado"],["Reposição de material na UBS Norte","Pedido encaminhado ao almoxarifado","Em atendimento"]], mapLayers:["Unidades de saúde","Campanhas","Rotas sanitárias"], mapPoints:[["UBS Norte","Vacinação · 86 atendimentos","Ativo"],["Centro","Rota de transporte 03","Em deslocamento"],["Planalto","Visitas domiciliares","Agendado"]], teams:[["Equipe de regulação","4 profissionais","Na unidade"],["Atenção domiciliar","5 profissionais","Em campo"],["Transporte sanitário","3 motoristas","Em rota"]], goals:[["Reduzir pendências de regulação",73,"Meta 85%"],["Cumprir rotas agendadas",94,"Meta 95%"],["Manter insumos acima do mínimo",88,"Meta 98%"]],
  },
  "Secretaria de Educação": {
    title:"Gestão da rede municipal de ensino", mission:"Centralize matrículas, transporte escolar, calendário, manutenção, alimentação e solicitações das unidades.", recordLabel:"registro educacional", recordDescription:"Cadastrar solicitação ou acompanhamento escolar", primaryField:"Aluno, turma ou unidade", secondaryField:"Escola, rota ou comunidade", privacy:"Dados de estudantes e responsáveis ficam restritos às equipes autorizadas e às finalidades educacionais.",
    metrics:[["Matrículas em análise","38","12 transferências"],["Rotas escolares","17","2 exigem ajuste"],["Manutenções abertas","11","4 prioritárias"],["Frequência monitorada","96%","23 alertas ativos"]], modules:["Matrículas e transferências","Transporte escolar","Calendário letivo","Manutenção das escolas","Merenda e materiais","Acompanhamento de frequência"], forms:["Matrícula ou transferência","Alteração de rota","Pedido de manutenção","Solicitação de material","Alerta de frequência"], records:[["Transferência para Escola Municipal Norte","Documentos conferidos","Em análise"],["Rota escolar Zona Norte","Novo itinerário em validação","Aguardando aprovação"],["Reparo no telhado da Escola Central","Vistoria técnica anexada","Em execução"]], mapLayers:["Escolas municipais","Rotas escolares","Manutenções"], mapPoints:[["Escola Central","Reparo no telhado","Em execução"],["Zona Norte","Rota 07 · ajuste solicitado","Atenção"],["Barra do Guaicuí","Entrega de material didático","Agendado"]], teams:[["Gestão escolar","5 servidores","Na secretaria"],["Transporte escolar","8 profissionais","Em rota"],["Manutenção das unidades","4 servidores","Em campo"]], goals:[["Concluir matrículas no prazo",89,"Meta 95%"],["Regularizar rotas escolares",82,"Meta 100%"],["Atender manutenções prioritárias",71,"Meta 90%"]],
  },
  "Secretaria de Infraestrutura e Transporte": {
    title:"Manutenção urbana e mobilidade", mission:"Gerencie ordens georreferenciadas de iluminação, pavimentação, drenagem, limpeza e sinalização.", recordLabel:"ordem de serviço", recordDescription:"Abrir ordem de manutenção urbana", primaryField:"Tipo de serviço ou ocorrência", secondaryField:"Endereço e referência", privacy:"Localizações de serviços são operacionais; dados do solicitante permanecem protegidos.",
    metrics:[["Ordens abertas","53","14 prioritárias"],["Equipes em campo","6","21 servidores"],["Iluminação pendente","18","7 para hoje"],["Dentro do SLA","87%","Meta: 90%"]], modules:["Iluminação pública","Pavimentação e buracos","Drenagem","Limpeza urbana","Sinalização","Estradas e acessos"], forms:["Reparo em iluminação","Operação tapa-buraco","Limpeza ou retirada","Vistoria de drenagem","Implantação de sinalização"], records:[["Iluminação da Praça Central","Equipe elétrica no local","Em execução"],["Buraco na Rua Dr. Ensch","Área sinalizada para reparo","Programado"],["Limpeza de canal no Planalto","Máquina e equipe designadas","Em execução"]], mapLayers:["Ordens de serviço","Iluminação","Drenagem e pavimento"], mapPoints:[["Praça Central","Revisão de luminárias","Em execução"],["Rua Dr. Ensch","Reparo de pavimento","Programado"],["Bairro Planalto","Limpeza de drenagem","Em campo"]], teams:[["Elétrica e iluminação","4 servidores","Em campo"],["Pavimentação","7 servidores","Em execução"],["Drenagem e limpeza","6 servidores","Em campo"]], goals:[["Atender ordens dentro do SLA",87,"Meta 90%"],["Reduzir pontos sem iluminação",78,"Meta 95%"],["Executar manutenção preventiva",64,"Meta 80%"]],
  },
  "Secretaria de Administração e Finanças": {
    title:"Administração, orçamento e suprimentos", mission:"Acompanhe compras, contratos, pagamentos, patrimônio, estoque e autorizações administrativas.", recordLabel:"processo administrativo-financeiro", recordDescription:"Cadastrar solicitação administrativa", primaryField:"Objeto, fornecedor ou despesa", secondaryField:"Unidade solicitante ou centro de custo", privacy:"Valores e documentos seguem o nível de publicidade do processo; dados pessoais e bancários são restritos.",
    metrics:[["Compras em andamento","19","6 em cotação"],["Pagamentos previstos","27","R$ 486 mil"],["Contratos a vencer","3","Até 45 dias"],["Execução acompanhada","74%","Referência anual"]], modules:["Solicitações de compra","Fornecedores e cotações","Contratos e pagamentos","Execução orçamentária","Patrimônio","Almoxarifado"], forms:["Solicitação de compra","Pesquisa de preços","Ordem de pagamento","Movimentação patrimonial","Requisição ao almoxarifado"], records:[["Aquisição de material escolar","Pesquisa de preços concluída","Em aprovação"],["Pagamento do contrato CT-2026-041","Liquidação conferida","Programado"],["Transferência de projetor patrimonial","Destino validado","Em andamento"]], mapLayers:["Unidades requisitantes","Bens patrimoniais","Almoxarifados"], mapPoints:[["Paço Municipal","12 processos financeiros","Ativo"],["Almoxarifado Central","Inventário mensal","Em execução"],["Secretaria de Educação","Entrega programada","Agendado"]], teams:[["Compras e licitações","5 servidores","Em análise"],["Finanças e tesouraria","4 servidores","Na unidade"],["Patrimônio e estoque","6 servidores","Em inventário"]], goals:[["Concluir compras planejadas",69,"Meta 85%"],["Evitar vencimento contratual",91,"Meta 100%"],["Atualizar inventário patrimonial",77,"Meta 90%"]],
  },
  "Secretaria de Governo": {
    title:"Coordenação estratégica do governo", mission:"Acompanhe prioridades, projetos intersetoriais, decisões, agendas e compromissos assumidos pelas secretarias.", recordLabel:"prioridade de governo", recordDescription:"Cadastrar prioridade, decisão ou compromisso", primaryField:"Projeto, decisão ou compromisso", secondaryField:"Secretarias envolvidas", privacy:"Decisões internas permanecem restritas até sua formalização ou publicação.",
    metrics:[["Prioridades ativas","26","7 intersetoriais"],["Decisões pendentes","8","3 para hoje"],["Projetos estratégicos","12","68% de avanço médio"],["Compromissos no prazo","89%","Meta 92%"]], modules:["Prioridades de governo","Projetos intersetoriais","Decisões administrativas","Agenda estratégica","Compromissos","Monitoramento de metas"], forms:["Nova prioridade","Decisão administrativa","Pauta intersetorial","Compromisso de governo","Atualização de projeto"], records:[["Operação Volta às Aulas","Educação e Transporte alinhados","Em andamento"],["Revitalização do Centro","Próxima decisão em 18/08","Aguardando decisão"],["Plano de atendimento regional","Metas consolidadas","Em monitoramento"]], mapLayers:["Projetos estratégicos","Compromissos territoriais","Equipamentos públicos"], mapPoints:[["Centro","Projeto de revitalização","Em andamento"],["Zona Norte","Compromisso de mobilidade","Planejado"],["Barra do Guaicuí","Agenda territorial","Agendado"]], teams:[["Coordenação de projetos","4 servidores","Na unidade"],["Articulação intersetorial","3 servidores","Em reunião"],["Monitoramento de metas","2 servidores","Atualizando dados"]], goals:[["Cumprir compromissos estratégicos",89,"Meta 92%"],["Atualizar projetos semanalmente",78,"Meta 100%"],["Resolver decisões pendentes",63,"Meta 85%"]],
  },
  "Gabinete do Prefeito": {
    title:"Agenda e compromissos do Executivo", mission:"Organize audiências, visitas, despachos, demandas da população e compromissos assumidos pelo gabinete.", recordLabel:"demanda do gabinete", recordDescription:"Registrar audiência, demanda ou compromisso", primaryField:"Cidadão, entidade ou compromisso", secondaryField:"Local, comunidade ou secretaria", privacy:"Audiências e dados pessoais têm acesso controlado; compromissos públicos podem ser divulgados após validação.",
    metrics:[["Audiências agendadas","14","5 nesta semana"],["Demandas recebidas","32","11 encaminhadas"],["Despachos pendentes","6","2 prioritários"],["Compromissos cumpridos","86%","No mês"]], modules:["Agenda institucional","Audiências com cidadãos","Demandas recebidas","Visitas oficiais","Despachos","Compromissos do Executivo"], forms:["Solicitação de audiência","Registro de demanda","Agenda oficial","Despacho do gabinete","Compromisso público"], records:[["Audiência com associação comercial","Pauta confirmada para 19/08","Agendado"],["Demanda comunitária da Zona Norte","Encaminhada à Infraestrutura","Em atendimento"],["Visita à UBS Norte","Equipe e cerimonial confirmados","Planejado"]], mapLayers:["Visitas oficiais","Demandas territoriais","Agenda pública"], mapPoints:[["UBS Norte","Visita oficial","Agendado"],["Centro","Audiência comunitária","Confirmado"],["Barra do Guaicuí","Agenda territorial","Planejado"]], teams:[["Agenda e cerimonial","3 servidores","Na unidade"],["Atendimento ao cidadão","4 servidores","Em atendimento"],["Assessoria institucional","3 servidores","Em agenda externa"]], goals:[["Responder demandas do gabinete",84,"Meta 90%"],["Cumprir agenda confirmada",96,"Meta 98%"],["Acompanhar encaminhamentos",72,"Meta 85%"]],
  },
  "Secretaria de Comunicação e Eventos": {
    title:"Comunicação pública e eventos", mission:"Organize pedidos de conteúdo, aprovações, calendário editorial, cobertura, imprensa, cerimonial e acervo de mídia.", recordLabel:"pedido de comunicação", recordDescription:"Cadastrar peça, cobertura ou evento", primaryField:"Campanha, peça ou evento", secondaryField:"Secretaria solicitante ou local", privacy:"Conteúdos internos e dados de participantes permanecem restritos até aprovação e publicação.",
    metrics:[["Pedidos em produção","17","6 para hoje"],["Conteúdos em aprovação","8","3 prioritários"],["Eventos próximos","5","2 com cobertura"],["Acervo no mês","286","Fotos e vídeos"]], modules:["Pedidos de arte","Produção de conteúdo","Calendário editorial","Aprovação e publicação","Cobertura de eventos","Imprensa e cerimonial"], forms:["Solicitação de arte","Pedido de cobertura","Nota institucional","Evento e cerimonial","Autorização de publicação"], records:[["Campanha de vacinação","Cards em aprovação","Aguardando aprovação"],["Feira do produtor","Equipe de cobertura definida","Agendado"],["Boletim semanal da prefeitura","Textos recebidos dos setores","Em produção"]], mapLayers:["Eventos municipais","Locais de cobertura","Equipamentos culturais"], mapPoints:[["Praça Central","Feira do produtor","Agendado"],["Auditório Municipal","Coletiva de imprensa","Confirmado"],["Estação Ferroviária","Evento cultural","Planejado"]], teams:[["Criação e design","3 profissionais","Em produção"],["Imprensa e conteúdo","4 profissionais","Na unidade"],["Eventos e cerimonial","5 profissionais","Em preparação"]], goals:[["Entregar pedidos no prazo",88,"Meta 92%"],["Aprovar calendário editorial",75,"Meta 90%"],["Organizar acervo de mídia",67,"Meta 80%"]],
  },
  "Secretaria Municipal de Desenvolvimento Econômico, Agricultura e Meio Ambiente": {
    title:"Desenvolvimento, produção rural e meio ambiente", mission:"Acompanhe produtores, empreendedores, visitas técnicas, feiras, licenças e ocorrências ambientais.", recordLabel:"atendimento produtivo ou ambiental", recordDescription:"Cadastrar produtor, empresa, visita ou ocorrência", primaryField:"Produtor, empreendimento ou ocorrência", secondaryField:"Propriedade, endereço ou comunidade", privacy:"Dados econômicos e pessoais permanecem restritos; informações ambientais públicas passam por validação.",
    metrics:[["Produtores atendidos","146","18 neste mês"],["Visitas técnicas","21","8 agendadas"],["Licenças em análise","13","4 aguardam documento"],["Ocorrências ambientais","9","3 prioritárias"]], modules:["Cadastro de produtores","Apoio ao empreendedor","Visitas técnicas","Feiras e programas","Licenciamento","Ocorrências ambientais"], forms:["Cadastro de produtor","Visita técnica rural","Atendimento ao empreendedor","Ocorrência ambiental","Inscrição em feira"], records:[["Produtor rural · comunidade Lagoa","Visita técnica agendada","Agendado"],["Feira municipal de agosto","32 expositores inscritos","Em preparação"],["Descarte irregular no acesso norte","Vistoria ambiental solicitada","Prioridade"]], mapLayers:["Propriedades atendidas","Ocorrências ambientais","Feiras e empreendimentos"], mapPoints:[["Comunidade Lagoa","Visita agronômica","Agendado"],["Acesso Norte","Ocorrência ambiental","Prioridade"],["Praça Central","Feira de produtores","Confirmado"]], teams:[["Assistência técnica rural","4 profissionais","Em campo"],["Desenvolvimento econômico","3 profissionais","Em atendimento"],["Fiscalização ambiental","3 profissionais","Em vistoria"]], goals:[["Ampliar assistência aos produtores",72,"Meta 85%"],["Concluir licenças no prazo",81,"Meta 90%"],["Responder ocorrências ambientais",67,"Meta 88%"]],
  },
  "Secretaria de Cultura e Turismo": {
    title:"Cultura, memória e turismo", mission:"Gerencie artistas, grupos, editais, eventos, espaços culturais, oficinas, roteiros turísticos e projetos.", recordLabel:"projeto cultural ou turístico", recordDescription:"Cadastrar artista, evento, espaço ou projeto", primaryField:"Artista, projeto, evento ou roteiro", secondaryField:"Espaço, localidade ou proponente", privacy:"Dados de proponentes são protegidos; resultados e agendas públicas dependem de aprovação.",
    metrics:[["Agentes culturais","218","17 cadastros novos"],["Projetos em análise","24","8 de edital"],["Eventos próximos","7","3 nesta semana"],["Espaços reservados","11","76% de ocupação"]], modules:["Cadastro cultural","Editais e projetos","Calendário de eventos","Reserva de espaços","Oficinas","Roteiros turísticos"], forms:["Cadastro de artista ou grupo","Inscrição em edital","Reserva de espaço","Proposta de evento","Cadastro turístico"], records:[["Mostra de cultura popular","Programação em aprovação","Em análise"],["Oficina de fotografia","28 inscritos confirmados","Agendado"],["Roteiro histórico da Estação","Conteúdo em revisão","Em produção"]], mapLayers:["Espaços culturais","Pontos turísticos","Eventos"], mapPoints:[["Estação Ferroviária","Roteiro histórico","Ativo"],["Casa da Cultura","Oficina de fotografia","Agendado"],["Praça Central","Mostra cultural","Planejado"]], teams:[["Produção cultural","4 profissionais","Em preparação"],["Turismo e roteiros","3 profissionais","Em campo"],["Gestão de espaços","3 profissionais","Na unidade"]], goals:[["Executar calendário cultural",78,"Meta 90%"],["Atualizar cadastro de agentes",66,"Meta 80%"],["Ampliar ocupação dos espaços",76,"Meta 85%"]],
  },
  "Controle Interno": {
    title:"Auditoria, riscos e conformidade", mission:"Planeje auditorias, registre achados, recomendações, responsáveis, evidências e planos de ação.", recordLabel:"trabalho de auditoria", recordDescription:"Cadastrar auditoria, achado ou recomendação", primaryField:"Objeto, processo ou recomendação", secondaryField:"Unidade auditada ou responsável", privacy:"Papéis de trabalho e apurações têm acesso restrito; relatórios seguem a classificação definida.",
    metrics:[["Auditorias em curso","7","3 na fase de campo"],["Recomendações abertas","22","8 vencem no mês"],["Planos de ação","15","73% de execução"],["Riscos críticos","4","Monitoramento ativo"]], modules:["Plano anual de auditoria","Matriz de riscos","Achados e evidências","Recomendações","Planos de ação","Conformidade"], forms:["Nova auditoria","Registro de achado","Recomendação","Plano de ação","Teste de conformidade"], records:[["Auditoria de contratos de manutenção","Amostra documental concluída","Em execução"],["Recomendação CI-2026-018","Prazo de resposta em 20/08","Aguardando resposta"],["Matriz de riscos de compras","Riscos críticos revisados","Concluído"]], mapLayers:["Unidades auditadas","Ações de campo","Riscos territoriais"], mapPoints:[["Paço Municipal","Auditoria de contratos","Em execução"],["Almoxarifado","Teste de inventário","Agendado"],["Obras","Verificação em campo","Planejado"]], teams:[["Auditoria administrativa","3 servidores","Em análise"],["Auditoria de campo","2 servidores","Em vistoria"],["Monitoramento de recomendações","2 servidores","Na unidade"]], goals:[["Executar plano anual",71,"Meta 85%"],["Reduzir recomendações vencidas",64,"Meta 90%"],["Monitorar riscos críticos",92,"Meta 100%"]],
  },
  "Departamento de Execução de Obras": {
    title:"Execução e fiscalização de obras", mission:"Centralize diário de obra, medições, contratos, equipes, materiais, fotos, custos e progresso físico.", recordLabel:"registro de obra", recordDescription:"Cadastrar obra, medição ou diário de campo", primaryField:"Obra, serviço ou medição", secondaryField:"Local, contrato ou frente de trabalho", privacy:"Medições e documentos contratuais seguem o nível de acesso do processo vinculado.",
    metrics:[["Obras em execução","9","2 com atenção"],["Medições pendentes","6","R$ 318 mil"],["Equipes em campo","5","24 trabalhadores"],["Avanço médio","63%","Sem atraso geral"]], modules:["Diário de obra","Medições","Contratos vinculados","Equipes e materiais","Fiscalização","Fotos e progresso"], forms:["Diário de obra","Nova medição","Vistoria técnica","Uso de material","Ocorrência da obra"], records:[["Revitalização da Praça Central","68% de avanço físico","Em execução"],["Reforma da UBS Norte","Medição nº 04 em conferência","Medição"],["Drenagem do bairro Planalto","Ordem de início preparada","Planejado"]], mapLayers:["Obras ativas","Frentes de trabalho","Vistorias"], mapPoints:[["Praça Central","Revitalização · 68%","Em execução"],["UBS Norte","Reforma · 42%","Em execução"],["Bairro Planalto","Drenagem pluvial","Planejado"]], teams:[["Fiscalização de obras","4 profissionais","Em campo"],["Equipe de execução 01","8 trabalhadores","Praça Central"],["Equipe de drenagem","6 trabalhadores","Em preparação"]], goals:[["Cumprir cronogramas",82,"Meta 90%"],["Conferir medições no prazo",73,"Meta 95%"],["Atualizar diários de obra",88,"Meta 100%"]],
  },
  "Departamento de Transportes": {
    title:"Frota, viagens e logística municipal", mission:"Controle reservas, motoristas, rotas, abastecimentos, quilometragem, manutenção, documentos e disponibilidade.", recordLabel:"movimentação de transporte", recordDescription:"Cadastrar viagem, reserva ou manutenção", primaryField:"Veículo, viagem ou serviço", secondaryField:"Destino, motorista ou setor solicitante", privacy:"Dados de passageiros e rotas sensíveis ficam disponíveis somente aos responsáveis autorizados.",
    metrics:[["Veículos disponíveis","18","De 24 ativos"],["Viagens agendadas","16","7 para amanhã"],["Manutenções abertas","4","1 prioritária"],["Documentos a vencer","2","Próximos 30 dias"]], modules:["Reserva de veículos","Motoristas e escalas","Rotas e viagens","Abastecimentos","Manutenção","Documentos e seguros"], forms:["Reserva de veículo","Ordem de viagem","Abastecimento","Solicitação de manutenção","Ocorrência de transporte"], records:[["Micro-ônibus Saúde · rota regional","Motorista e passageiros confirmados","Agendado"],["Caminhão compactador RTA-3C92","Manutenção do sistema hidráulico","Em manutenção"],["Veículo PVE-2041","Revisão preventiva programada","Planejado"]], mapLayers:["Veículos em rota","Garagens","Destinos agendados"], mapPoints:[["Garagem Municipal","18 veículos disponíveis","Ativo"],["Rota Regional","Micro-ônibus Saúde","Em deslocamento"],["Oficina credenciada","Caminhão em manutenção","Em atendimento"]], teams:[["Operação de frota","4 servidores","Na garagem"],["Motoristas escalados","11 motoristas","Em rota"],["Manutenção e documentos","3 servidores","Na unidade"]], goals:[["Cumprir viagens agendadas",94,"Meta 98%"],["Executar manutenção preventiva",79,"Meta 90%"],["Manter documentos regulares",92,"Meta 100%"]],
  },
  "Departamento de Esporte e Lazer / Subseção de Esportes": {
    title:"Esporte, lazer e escolinhas municipais", mission:"Organize modalidades, turmas, participantes, competições, espaços, frequência e materiais esportivos.", recordLabel:"atividade esportiva", recordDescription:"Cadastrar turma, evento ou atendimento esportivo", primaryField:"Modalidade, turma ou competição", secondaryField:"Espaço, professor ou comunidade", privacy:"Dados de participantes, especialmente menores, ficam restritos aos profissionais e responsáveis autorizados.",
    metrics:[["Participantes ativos","486","18 novas inscrições"],["Turmas em andamento","24","8 modalidades"],["Espaços reservados","17","82% de ocupação"],["Competições próximas","4","3 equipes inscritas"]], modules:["Inscrições e participantes","Turmas e frequência","Modalidades","Campeonatos","Reserva de espaços","Materiais esportivos"], forms:["Inscrição em atividade","Lista de presença","Reserva de quadra","Cadastro de campeonato","Empréstimo de material"], records:[["Escolinha de futsal Sub-13","28 participantes ativos","Em andamento"],["Campeonato Municipal 2026","Tabela de jogos em revisão","Em preparação"],["Quadra do Planalto","Reserva para treinamento","Confirmado"]], mapLayers:["Espaços esportivos","Turmas","Competições"], mapPoints:[["Ginásio Municipal","Treino de futsal","Em atividade"],["Quadra do Planalto","Turma de vôlei","Agendado"],["Campo da Barra","Campeonato amador","Planejado"]], teams:[["Professores e monitores","8 profissionais","Em atividade"],["Eventos esportivos","4 servidores","Em preparação"],["Gestão de espaços","3 servidores","Na unidade"]], goals:[["Manter frequência das turmas",86,"Meta 90%"],["Executar calendário esportivo",74,"Meta 88%"],["Atualizar materiais e espaços",69,"Meta 85%"]],
  },
  "Departamento de Vigilância Sanitária": {
    title:"Fiscalização e vigilância sanitária", mission:"Acompanhe estabelecimentos, inspeções, risco, licenças, notificações, denúncias e prazos de adequação.", recordLabel:"ação sanitária", recordDescription:"Cadastrar inspeção, licença ou denúncia", primaryField:"Estabelecimento ou ocorrência", secondaryField:"Endereço, atividade ou responsável", privacy:"Denunciantes e dados pessoais recebem proteção; autos e licenças seguem a publicidade aplicável.",
    metrics:[["Inspeções programadas","18","7 nesta semana"],["Licenças em análise","23","6 aguardam documento"],["Adequações pendentes","14","4 vencem no mês"],["Denúncias recebidas","7","2 prioritárias"]], modules:["Cadastro de estabelecimentos","Inspeções","Classificação de risco","Licenças","Notificações e autos","Denúncias sanitárias"], forms:["Inspeção sanitária","Pedido de licença","Notificação de adequação","Auto sanitário","Denúncia protegida"], records:[["Restaurante Centro · inspeção periódica","Checklist sanitário programado","Agendado"],["Farmácia Planalto · renovação de licença","Documentação em análise","Em análise"],["Denúncia VS-2026-041","Identidade do denunciante protegida","Prioridade"]], mapLayers:["Estabelecimentos","Inspeções programadas","Ocorrências sanitárias"], mapPoints:[["Centro","5 inspeções programadas","Agendado"],["Planalto","Renovação de licença","Em análise"],["Pinlar I","Ocorrência sanitária","Prioridade"]], teams:[["Inspeção de alimentos","3 fiscais","Em campo"],["Licenciamento sanitário","3 servidores","Na unidade"],["Atendimento a denúncias","2 fiscais","Em vistoria"]], goals:[["Cumprir plano de inspeções",81,"Meta 90%"],["Concluir licenças no prazo",76,"Meta 90%"],["Monitorar adequações vencidas",68,"Meta 95%"]],
  },
  "Seção de Controle e Avaliação": {
    title:"Controle, regulação e avaliação de serviços", mission:"Acompanhe autorizações, filas, capacidade, produção das unidades, solicitações pendentes e auditoria dos atendimentos.", recordLabel:"controle ou avaliação", recordDescription:"Cadastrar autorização, análise ou avaliação", primaryField:"Serviço, autorização ou unidade", secondaryField:"Usuário, prestador ou referência", privacy:"Registros individualizados ficam restritos; relatórios gerenciais usam informações consolidadas.",
    metrics:[["Autorizações pendentes","41","9 prioritárias"],["Fila monitorada","128","-8% no mês"],["Unidades avaliadas","12","4 neste ciclo"],["Produção conferida","93%","Referência mensal"]], modules:["Autorizações","Filas de atendimento","Capacidade dos serviços","Produção das unidades","Auditoria de atendimentos","Indicadores"], forms:["Solicitação de autorização","Avaliação de unidade","Conferência de produção","Registro de fila","Auditoria de atendimento"], records:[["Autorizações do período 13/08","31 itens conferidos","Em análise"],["Avaliação da Unidade Norte","Indicadores consolidados","Em execução"],["Fila de especialidade regional","Prioridades atualizadas","Monitoramento"]], mapLayers:["Unidades avaliadas","Capacidade regional","Filas por território"], mapPoints:[["Unidade Norte","Avaliação de capacidade","Em execução"],["Centro","Produção em conferência","Em análise"],["Barra do Guaicuí","Demanda regional","Monitoramento"]], teams:[["Controle de autorizações","4 servidores","Na unidade"],["Avaliação e auditoria","3 servidores","Em análise"],["Monitoramento de filas","2 servidores","Atualizando dados"]], goals:[["Analisar autorizações no prazo",84,"Meta 92%"],["Atualizar filas semanalmente",91,"Meta 100%"],["Concluir ciclo de avaliação",68,"Meta 85%"]],
  },
  "Subseção de Patrimônio Histórico e Cultura": {
    title:"Patrimônio histórico e acervo cultural", mission:"Inventarie bens, documente conservação, acompanhe intervenções, pedidos de reforma e o acervo histórico digital.", recordLabel:"bem ou registro histórico", recordDescription:"Cadastrar bem, intervenção ou documento", primaryField:"Bem, imóvel, acervo ou intervenção", secondaryField:"Localização, proprietário ou responsável", privacy:"Acervos públicos podem ser consultados após curadoria; dados pessoais e laudos internos têm acesso restrito.",
    metrics:[["Bens inventariados","96","8 em revisão"],["Vistorias previstas","12","5 no mês"],["Intervenções em análise","7","2 prioritárias"],["Itens digitalizados","1.284","74% do acervo"]], modules:["Inventário de bens","Estado de conservação","Vistorias","Intervenções","Acervo fotográfico","Documentação histórica"], forms:["Cadastro de bem histórico","Vistoria de conservação","Pedido de intervenção","Registro fotográfico","Digitalização de acervo"], records:[["Estação Ferroviária","Vistoria de conservação concluída","Monitoramento"],["Casa da Cultura","Pedido de intervenção em análise","Em análise"],["Acervo fotográfico municipal","86 imagens digitalizadas no mês","Em execução"]], mapLayers:["Bens inventariados","Vistorias","Intervenções"], mapPoints:[["Estação Ferroviária","Bem inventariado","Monitoramento"],["Casa da Cultura","Intervenção proposta","Em análise"],["Centro Histórico","Roteiro de vistoria","Agendado"]], teams:[["Inventário e pesquisa","3 profissionais","Em documentação"],["Conservação e vistoria","2 profissionais","Em campo"],["Acervo digital","3 profissionais","Na unidade"]], goals:[["Revisar inventário municipal",72,"Meta 85%"],["Digitalizar acervo prioritário",74,"Meta 90%"],["Vistoriar bens críticos",83,"Meta 100%"]],
  },
  "Subprefeitura da Barra do Guaicuí": {
    title:"Gestão territorial da Barra do Guaicuí", mission:"Centralize demandas comunitárias, manutenção local, estradas, iluminação, limpeza, agenda e visitas às comunidades.", recordLabel:"demanda territorial", recordDescription:"Cadastrar atendimento ou serviço local", primaryField:"Demanda, serviço ou comunidade", secondaryField:"Endereço, estrada ou ponto de referência", privacy:"Dados dos moradores permanecem protegidos; a situação dos serviços pode ser divulgada de forma agregada.",
    metrics:[["Demandas locais","29","8 prioritárias"],["Serviços em campo","7","3 equipes"],["Estradas monitoradas","12","2 com atenção"],["Atendimentos no mês","84","18 nesta semana"]], modules:["Atendimento comunitário","Manutenção local","Estradas e acessos","Iluminação e limpeza","Agenda comunitária","Visitas territoriais"], forms:["Demanda comunitária","Vistoria de estrada","Reparo de iluminação","Limpeza local","Visita à comunidade"], records:[["Acesso à comunidade Ribeirinha","Vistoria de estrada programada","Agendado"],["Iluminação da Rua São Pedro","Equipe acionada","Em atendimento"],["Reunião comunitária de agosto","Pauta aberta para contribuições","Confirmado"]], mapLayers:["Demandas locais","Estradas","Equipamentos públicos"], mapPoints:[["Rua São Pedro","Reparo de iluminação","Em atendimento"],["Estrada Ribeirinha","Vistoria programada","Agendado"],["Sede da Subprefeitura","Atendimento comunitário","Ativo"]], teams:[["Atendimento local","3 servidores","Na unidade"],["Manutenção territorial","5 servidores","Em campo"],["Apoio comunitário","2 servidores","Em visita"]], goals:[["Responder demandas prioritárias",79,"Meta 90%"],["Vistoriar estradas monitoradas",67,"Meta 85%"],["Executar agenda comunitária",88,"Meta 95%"]],
  },
};

const TAB_META: Record<WorkspaceTab,{icon:LucideIcon;label:string}> = {
  "Painel setorial":{icon:Layers3,label:"Painel setorial"},
  "Cadastros e formulários":{icon:FileText,label:"Cadastros"},
  "Equipes de campo":{icon:Smartphone,label:"Campo"},
  "Metas e indicadores":{icon:Target,label:"Metas"},
  "Encaminhamentos":{icon:Send,label:"Encaminhamentos"},
};

function profileFor(department:string):SectorProfile {
  return PROFILES[department] ?? DEFAULT_PROFILE;
}

function toneFor(status:string) {
  const value=status.toLowerCase();
  if(value.includes("concl")||value.includes("confirm")||value.includes("ativo")||value.includes("disponível")) return "success";
  if(value.includes("prior")||value.includes("atenção")) return "danger";
  if(value.includes("aguard")||value.includes("análise")||value.includes("planej")||value.includes("agend")) return "warning";
  return "info";
}


export function SectorWorkspaceSection({department,userName,userRole,departments,notify}:{department:string;userName:string;userRole:string;departments:string[];notify:Notify}) {
  const access=useCurrentPermission();
  const profile=profileFor(department);
  const initialState=useMemo<SectorWorkspaceState>(()=>({
    records:profile.records.map(([title,detail,status],index)=>({id:`seed-record-${index}`,title,detail,status,priority:index===0?"Alta":"Normal",owner:index===0?userName:profile.teams[index%profile.teams.length]?.[0]??userName,dueDate:["2026-08-19","2026-08-22","2026-08-26"][index]??"2026-08-30",category:profile.forms[index%profile.forms.length]??"Registro geral",updatedAt:"2026-08-18T12:00:00.000Z"})),
    referrals:[
      {id:"seed-ref-1",destination:"Secretaria de Administração e Finanças",subject:"Solicitação de apoio administrativo",scope:"Somente dados necessários",dueDate:"2026-08-21",status:"Aguardando retorno",note:"Providência encaminhada ao setor responsável.",createdAt:"2026-08-18T10:00:00.000Z"},
      {id:"seed-ref-2",destination:"Secretaria de Comunicação e Eventos",subject:"Divulgação de ação do setor",scope:"Informações institucionais",dueDate:"2026-08-24",status:"Recebido",note:"Material institucional em preparação.",createdAt:"2026-08-17T15:30:00.000Z"},
    ],
    goals:profile.goals.map(([title,progress,target],index)=>({id:`seed-goal-${index}`,title,progress,target,owner:index===0?userName:profile.teams[index%profile.teams.length]?.[0]??userName})),
    activities:[],
  }),[profile,userName]);
  const [state,setState,saveStatus,ready]=usePersistentState<SectorWorkspaceState>(persistenceKey("sector-workspace",department,"v3"),initialState);
  const [tab,setTab]=useState<WorkspaceTab>("Painel setorial");
  const [query,setQuery]=useState("");
  const [statusFilter,setStatusFilter]=useState("Todos os status");
  const [recordModal,setRecordModal]=useState<{mode:"create"|"edit";record?:SectorRecord}|null>(null);
  const [detailRecord,setDetailRecord]=useState<SectorRecord|null>(null);
  const [fieldModal,setFieldModal]=useState(false);
  const [selectedForm,setSelectedForm]=useState(profile.forms[0]);

  const today=new Date().toISOString().slice(0,10);
  const visibleRecords=useMemo(()=>state.records.filter(item=>[item.title,item.detail,item.owner,item.category,item.status].join(" ").toLowerCase().includes(query.toLowerCase())&&(statusFilter==="Todos os status"||item.status===statusFilter)),[state.records,query,statusFilter]);
  const urgentRecords=state.records.filter(item=>item.priority==="Urgente"||item.priority==="Alta"||Boolean(item.dueDate&&item.dueDate<=today&&item.status!=="Concluído"));
  const completed=state.records.filter(item=>toneFor(item.status)==="success").length;
  const completion=state.records.length?Math.round((completed/state.records.length)*100):0;
  const averageGoal=state.goals.length?Math.round(state.goals.reduce((sum,item)=>sum+item.progress,0)/state.goals.length):0;
  const statusOptions=Array.from(new Set(state.records.map(item=>item.status)));

  function makeId(prefix:string){return globalThis.crypto?.randomUUID?.()??`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;}
  function openRecord(form=profile.forms[0],record?:SectorRecord){if(record&&!access.edit){setDetailRecord(record);return;}if(!record&&!access.register){notify("Seu perfil possui acesso de consulta nesta área.");return;}setSelectedForm(record?.category??form);setRecordModal(record?{mode:"edit",record}:{mode:"create"});}
  function saveRecord(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const base=recordModal?.record;const record:SectorRecord={id:base?.id??makeId("record"),title:String(form.get("title")||""),detail:String(form.get("detail")||""),status:String(form.get("status")||"Recebido"),priority:String(form.get("priority")||"Normal") as SectorPriority,owner:String(form.get("owner")||userName),dueDate:String(form.get("dueDate")||""),category:String(form.get("category")||selectedForm),updatedAt:new Date().toISOString()};setState(current=>({...current,records:base?current.records.map(item=>item.id===base.id?record:item):[record,...current.records]}));setDetailRecord(current=>current?.id===record.id?record:current);setRecordModal(null);notify(base?"Registro atualizado e salvo.":"Registro criado e salvo na central do setor.");}
  function deleteRecord(record:SectorRecord){if(!access.edit){notify("Seu perfil não pode excluir registros.");return;}setState(current=>({...current,records:current.records.filter(item=>item.id!==record.id)}));setDetailRecord(null);notify("Registro removido da área do setor.");}
  function quickStatus(record:SectorRecord,status:string){if(!access.edit){notify("Seu perfil está em modo de consulta.");return;}const next={...record,status,updatedAt:new Date().toISOString()};setState(current=>({...current,records:current.records.map(item=>item.id===record.id?next:item)}));setDetailRecord(next);notify(`Situação atualizada para “${status}”.`);}
  function createFieldRecord(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!access.register)return;const form=new FormData(event.currentTarget);const activity:SectorActivity={id:makeId("field"),team:String(form.get("team")||profile.teams[0]?.[0]||"Equipe"),type:String(form.get("type")||profile.forms[0]),location:String(form.get("location")||""),status:String(form.get("status")||"Em andamento"),notes:String(form.get("notes")||""),createdAt:new Date().toISOString()};const record:SectorRecord={id:makeId("record"),title:activity.type,detail:`${activity.location}${activity.notes?` · ${activity.notes}`:""}`,status:activity.status,priority:"Normal",owner:activity.team,dueDate:"",category:"Atividade de campo",updatedAt:activity.createdAt};setState(current=>({...current,activities:[activity,...current.activities],records:[record,...current.records]}));setFieldModal(false);notify("Atividade de campo registrada e salva na fila do setor.");}
  function createReferral(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!access.register)return;const form=new FormData(event.currentTarget);const referral:SectorReferral={id:makeId("ref"),destination:String(form.get("destination")||""),subject:String(form.get("subject")||""),scope:String(form.get("scope")||"Somente dados necessários"),dueDate:String(form.get("due")||""),status:"Aguardando retorno",note:String(form.get("note")||""),createdAt:new Date().toISOString()};setState(current=>({...current,referrals:[referral,...current.referrals]}));event.currentTarget.reset();notify(`Encaminhamento registrado para ${referral.destination}.`);}
  function updateReferral(id:string,status:string){if(!access.edit){notify("Seu perfil não pode alterar encaminhamentos.");return;}setState(current=>({...current,referrals:current.referrals.map(item=>item.id===id?{...item,status}:item)}));notify(`Encaminhamento atualizado para “${status}”.`);}
  function adjustGoal(id:string,delta:number){if(!access.edit){notify("Seu perfil não pode alterar metas.");return;}setState(current=>({...current,goals:current.goals.map(item=>item.id===id?{...item,progress:Math.min(100,Math.max(0,item.progress+delta))}:item)}));}

  return <section className="sector-workspace sector-workspace-v3">
    <article className="sector-hero sector-hero-v2 sector-hero-compact">
      <span className="sector-hero-icon"><Building2 size={26}/></span>
      <div className="sector-hero-copy"><p className="eyebrow">CENTRAL OPERACIONAL DO SETOR</p><h2>{profile.title}</h2><p>{profile.mission}</p><div className="sector-context-row"><span><ShieldCheck size={13}/>{department}</span><span><UsersRound size={13}/>{userRole}</span><span><CalendarDays size={13}/>Dados compartilhados com a equipe autorizada</span></div></div>
      <div className="sector-hero-actions"><span className={`sync-inline ${saveStatus}`}>{!ready?"Carregando…":saveStatus==="salvando"?"Salvando…":saveStatus==="offline"?"Aguardando conexão":"Tudo salvo"}</span>{access.register&&<><button className="button secondary" onClick={()=>setFieldModal(true)}><Navigation size={15}/> Atividade externa</button><button className="button primary" onClick={()=>openRecord()}><Plus size={15}/> Novo registro</button></>}</div>
    </article>

    <div className="sector-kpi-strip">
      <article><span><ListChecks size={18}/></span><div><small>Registros ativos</small><strong>{state.records.length-completed}</strong></div></article>
      <article><span><AlertTriangle size={18}/></span><div><small>Prioridades</small><strong>{urgentRecords.length}</strong></div></article>
      <article><span><CheckCircle2 size={18}/></span><div><small>Concluídos</small><strong>{completion}%</strong></div></article>
      <article><span><Target size={18}/></span><div><small>Metas</small><strong>{averageGoal}%</strong></div></article>
    </div>

    <nav className="sector-tabs sector-tabs-v2" aria-label="Navegação da área do setor">{(Object.keys(TAB_META) as WorkspaceTab[]).map(item=>{const Icon=TAB_META[item].icon;const badge=item==="Encaminhamentos"?state.referrals.filter(ref=>ref.status!=="Concluído").length:item==="Equipes de campo"?state.activities.length:0;return <button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}><Icon size={16}/><span>{TAB_META[item].label}</span>{badge>0&&<b>{badge}</b>}</button>})}</nav>

    {tab==="Painel setorial"&&<div className="sector-overview-v3">
      <article className="panel sector-today-board"><header><div><p className="eyebrow">FILA DE TRABALHO</p><h3>O que exige atenção agora</h3><p>Prioridade, prazo e responsável em uma única leitura.</p></div><button onClick={()=>setTab("Cadastros e formulários")}>Ver todos <ArrowRight size={13}/></button></header><div>{[...state.records].sort((a,b)=>(a.dueDate||"9999").localeCompare(b.dueDate||"9999")).slice(0,5).map(record=><button key={record.id} onClick={()=>setDetailRecord(record)}><span className={`priority-dot ${record.priority.toLowerCase()}`}/><span><strong>{record.title}</strong><small>{record.owner} · {record.category}</small></span><span className="sector-record-deadline"><small>{record.dueDate?new Date(`${record.dueDate}T12:00:00`).toLocaleDateString("pt-BR"):"Sem prazo"}</small><i className={toneFor(record.status)}>{record.status}</i></span><ChevronRight size={14}/></button>)}</div></article>
      <aside className="sector-quick-actions panel"><header><p className="eyebrow">AÇÕES RÁPIDAS</p><h3>Registrar sem perder tempo</h3></header>{profile.forms.slice(0,5).map((form,index)=><button key={form} onClick={()=>openRecord(form)} disabled={!access.register}><span>{index+1}</span><span><strong>{form}</strong><small>Abrir ficha preparada para o setor</small></span><Plus size={14}/></button>)}</aside>
      <article className="panel sector-team-status"><header><div><p className="eyebrow">EQUIPE</p><h3>Distribuição operacional</h3></div><UsersRound size={18}/></header><div>{profile.teams.map(([team,size,status])=><button key={team} onClick={()=>setTab("Equipes de campo")}><span><strong>{team}</strong><small>{size}</small></span><i className={toneFor(status)}>{status}</i></button>)}</div></article>
      <article className="panel sector-referral-summary"><header><div><p className="eyebrow">ENCAMINHAMENTOS</p><h3>Retornos entre setores</h3></div><Send size={18}/></header>{state.referrals.slice(0,3).map(item=><button key={item.id} onClick={()=>setTab("Encaminhamentos")}><span><strong>{item.subject}</strong><small>{item.destination}</small></span><i className={toneFor(item.status)}>{item.status}</i></button>)}{!state.referrals.length&&<p>Nenhum encaminhamento registrado.</p>}</article>
    </div>}

    {tab==="Cadastros e formulários"&&<div className="sector-record-layout sector-record-layout-v3"><aside className="panel sector-form-catalog"><header><BookOpenCheck size={19}/><div><h3>Fichas do setor</h3><p>Modelos adaptados à rotina da unidade.</p></div></header>{profile.forms.map((form,index)=><button key={form} onClick={()=>openRecord(form)} disabled={!access.register}><span>{String(index+1).padStart(2,"0")}</span><strong>{form}</strong><ChevronRight size={13}/></button>)}</aside><article className="panel sector-records sector-records-v3"><div className="module-toolbar"><label className="module-search"><Search size={15}/><input aria-label="Buscar nos registros do setor" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar assunto, responsável ou categoria..."/></label><select aria-label="Filtrar registros" value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option>Todos os status</option>{statusOptions.map(item=><option key={item}>{item}</option>)}</select>{access.register&&<button className="button primary" onClick={()=>openRecord()}><Plus size={15}/> Novo registro</button>}</div><div className="sector-record-list-v3">{visibleRecords.map(record=><article key={record.id}><button className="sector-record-main" onClick={()=>setDetailRecord(record)}><span className="sector-record-icon"><FileText size={16}/></span><span><strong>{record.title}</strong><small>{record.detail}</small><em>{record.category} · {record.owner}</em></span></button><span className={`priority-label ${record.priority.toLowerCase()}`}>{record.priority}</span><i className={toneFor(record.status)}>{record.status}</i>{access.edit&&<button className="sector-record-edit" aria-label={`Editar ${record.title}`} onClick={()=>openRecord(record.category,record)}><Pencil size={14}/></button>}</article>)}{!visibleRecords.length&&<div className="sector-empty"><Search size={22}/><strong>Nenhum registro encontrado</strong><p>Revise a busca ou selecione outro status.</p></div>}</div></article></div>}

    {tab==="Equipes de campo"&&<div className="sector-field-v3"><article className="field-app-banner"><span><Smartphone size={24}/></span><div><p className="eyebrow">OPERAÇÃO EM CAMPO</p><h3>Registre a atividade assim que ela acontecer</h3><p>Equipe, tipo de serviço, endereço, situação e observações ficam associados ao histórico do setor.</p></div>{access.register&&<button className="button primary" onClick={()=>setFieldModal(true)}>Nova atividade</button>}</article><div className="field-team-grid">{profile.teams.map(([team,size,status],index)=><article className="panel" key={team}><header><span>{index+1}</span><i className={toneFor(status)}>{status}</i></header><h3>{team}</h3><p><UsersRound size={14}/>{size}</p><button onClick={()=>access.register?setFieldModal(true):notify(`Histórico de ${team} aberto para consulta.`)}>{access.register?"Registrar atividade":"Consultar atividades"}<ArrowRight size={13}/></button></article>)}</div><article className="panel sector-activity-history"><header><div><h3>Atividades recentes</h3><p>Registros feitos pelas equipes do setor.</p></div><Navigation size={18}/></header>{state.activities.slice(0,8).map(item=><div key={item.id}><span><strong>{item.type}</strong><small>{item.team} · {item.location}</small></span><span><i className={toneFor(item.status)}>{item.status}</i><small>{new Date(item.createdAt).toLocaleString("pt-BR")}</small></span></div>)}{!state.activities.length&&<div className="sector-empty"><Navigation size={22}/><strong>Nenhuma atividade registrada</strong><p>As atividades externas aparecerão aqui.</p></div>}</article></div>}

    {tab==="Metas e indicadores"&&<div className="sector-goals-layout"><article className="panel sector-goals"><header><div><h3>Metas de {department}</h3><p>Atualize o avanço conforme as entregas forem confirmadas.</p></div><span className={`sync-inline ${saveStatus}`}>{saveStatus==="offline"?"Aguardando conexão":"Metas sincronizadas"}</span></header>{state.goals.map((goal,index)=><div className="goal-row goal-row-editable" key={goal.id}><span className="goal-number">{index+1}</span><span><strong>{goal.title}</strong><small>Responsável: {goal.owner}</small><i><b style={{width:`${goal.progress}%`}}/></i></span><span><strong>{goal.progress}%</strong><small>{goal.target}</small></span>{access.edit?<div className="goal-adjust"><button onClick={()=>adjustGoal(goal.id,-5)}>-5</button><button onClick={()=>adjustGoal(goal.id,5)}>+5</button></div>:<ChevronRight size={14}/>}</div>)}</article><aside className="sector-goal-side"><article className="panel goal-score"><Gauge size={27}/><strong>{averageGoal}%</strong><p>execução média das metas</p></article><article className="panel indicator-rules"><h3>Indicadores próprios</h3><p>Os indicadores consideram a natureza do trabalho do setor.</p>{profile.metrics.map(item=><span key={item[0]}><Check size={12}/>{item[0]}</span>)}</article></aside></div>}

    {tab==="Encaminhamentos"&&<div className="sector-referral-layout"><article className="panel referral-form"><header><span><HeartHandshake size={20}/></span><div><h3>Novo encaminhamento</h3><p>Registre a providência, o destino e o prazo esperado de retorno.</p></div></header>{access.register?<form onSubmit={createReferral}><label><span>Setor de destino *</span><select name="destination" required defaultValue=""><option value="" disabled>Selecione o setor responsável</option>{departments.filter(item=>item!==department).map(item=><option key={item}>{item}</option>)}</select></label><label><span>Assunto *</span><input name="subject" required placeholder="Descreva o apoio ou serviço solicitado"/></label><label><span>Escopo dos dados *</span><select name="scope" required defaultValue="Somente dados necessários"><option>Somente dados necessários</option><option>Informações institucionais</option><option>Documentos selecionados</option><option>Dados pessoais autorizados</option></select></label><label><span>Prazo para retorno</span><input type="date" name="due"/></label><label className="full"><span>Contexto e providência</span><textarea name="note" placeholder="Informe o contexto mínimo para que o outro setor possa atender."/></label><p className="referral-privacy"><ShieldCheck size={14}/><span><strong>Compartilhamento mínimo</strong> Envie apenas as informações necessárias para a providência.</span></p><button className="button primary"><Send size={14}/>Registrar encaminhamento</button></form>:<div className="sector-readonly-card"><LockKeyhole size={22}/><h4>Consulta de encaminhamentos</h4><p>Seu perfil pode acompanhar o histórico, mas não criar novos encaminhamentos.</p></div>}</article><aside className="panel referral-list referral-list-v3"><header><div><h3>Encaminhamentos</h3><p>Acompanhe retorno, prazo e situação.</p></div><ListChecks size={18}/></header>{state.referrals.map(item=><div className="referral-manage-row" key={item.id}><span className="referral-status"><i/></span><span><strong>{item.subject}</strong><small>{item.destination} · {item.scope}{item.dueDate?` · prazo ${new Date(`${item.dueDate}T12:00:00`).toLocaleDateString("pt-BR")}`:""}</small></span>{access.edit?<select value={item.status} onChange={event=>updateReferral(item.id,event.target.value)}><option>Aguardando retorno</option><option>Recebido</option><option>Em atendimento</option><option>Concluído</option></select>:<i className={toneFor(item.status)}>{item.status}</i>}</div>)}</aside></div>}

    {recordModal&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setRecordModal(null)}}><section className="modal sector-modal sector-record-modal-v3" role="dialog" aria-modal="true" aria-labelledby="sector-record-modal-title"><header><div><p className="eyebrow">{department.toUpperCase()}</p><h2 id="sector-record-modal-title">{recordModal.mode==="edit"?"Editar registro":profile.recordDescription}</h2></div><button type="button" aria-label="Fechar" onClick={()=>setRecordModal(null)}><X size={18}/></button></header><form onSubmit={saveRecord}><label className="field full"><span>Modelo / categoria</span><select name="category" value={selectedForm} onChange={event=>setSelectedForm(event.target.value)}>{Array.from(new Set([selectedForm,...profile.forms])).map(item=><option key={item}>{item}</option>)}</select></label><label className="field full"><span>{profile.primaryField} *</span><input name="title" required autoFocus defaultValue={recordModal.record?.title??""} placeholder={`Informe ${profile.primaryField.toLowerCase()}`}/></label><label className="field full"><span>{profile.secondaryField} / descrição *</span><textarea name="detail" required defaultValue={recordModal.record?.detail??""} placeholder="Registre o local, contexto e a providência necessária."/></label><label className="field"><span>Prioridade</span><select name="priority" defaultValue={recordModal.record?.priority??"Normal"}><option>Urgente</option><option>Alta</option><option>Normal</option><option>Baixa</option></select></label><label className="field"><span>Situação</span><input name="status" defaultValue={recordModal.record?.status??"Recebido"}/></label><label className="field"><span>Responsável</span><input name="owner" defaultValue={recordModal.record?.owner??userName}/></label><label className="field"><span>Prazo</span><input name="dueDate" type="date" defaultValue={recordModal.record?.dueDate??""}/></label><p className="sector-modal-privacy"><LockKeyhole size={14}/>{profile.privacy}</p><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setRecordModal(null)}>Cancelar</button><button className="button primary"><Save size={15}/>{recordModal.mode==="edit"?"Salvar alterações":"Cadastrar registro"}</button></div></form></section></div>}

    {detailRecord&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setDetailRecord(null)}}><section className="modal sector-detail-modal" role="dialog" aria-modal="true" aria-labelledby="sector-detail-title"><header><div><p className="eyebrow">{detailRecord.category}</p><h2 id="sector-detail-title">{detailRecord.title}</h2></div><button onClick={()=>setDetailRecord(null)} aria-label="Fechar"><X size={18}/></button></header><div className="sector-detail-content"><div className="sector-detail-tags"><span className={`priority-label ${detailRecord.priority.toLowerCase()}`}>{detailRecord.priority}</span><i className={toneFor(detailRecord.status)}>{detailRecord.status}</i></div><p>{detailRecord.detail}</p><dl><div><dt>Responsável</dt><dd>{detailRecord.owner}</dd></div><div><dt>Prazo</dt><dd>{detailRecord.dueDate?new Date(`${detailRecord.dueDate}T12:00:00`).toLocaleDateString("pt-BR"):"Sem prazo definido"}</dd></div><div><dt>Atualização</dt><dd>{new Date(detailRecord.updatedAt).toLocaleString("pt-BR")}</dd></div><div><dt>Setor</dt><dd>{department}</dd></div></dl>{access.edit&&<div className="sector-detail-actions"><button className="button secondary" onClick={()=>quickStatus(detailRecord,"Em andamento")}>Em andamento</button><button className="button secondary" onClick={()=>quickStatus(detailRecord,"Concluído")}>Concluir</button><button className="button primary" onClick={()=>{openRecord(detailRecord.category,detailRecord);setDetailRecord(null)}}><Pencil size={14}/>Editar</button><button className="button secondary danger-outline" onClick={()=>deleteRecord(detailRecord)}><Trash2 size={14}/>Excluir</button></div>}</div></section></div>}

    {fieldModal&&access.register&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setFieldModal(false)}}><section className="modal sector-modal" role="dialog" aria-modal="true" aria-labelledby="field-modal-title"><header><div><p className="eyebrow">ATIVIDADE EXTERNA</p><h2 id="field-modal-title">Registro da equipe de campo</h2></div><button type="button" aria-label="Fechar" onClick={()=>setFieldModal(false)}><X size={18}/></button></header><form onSubmit={createFieldRecord}><label className="field"><span>Equipe *</span><select name="team" required>{profile.teams.map(item=><option key={item[0]}>{item[0]}</option>)}</select></label><label className="field"><span>Tipo de atividade *</span><select name="type" required>{profile.forms.slice(0,4).map(item=><option key={item}>{item}</option>)}</select></label><label className="field full"><span>Rua, endereço ou referência *</span><input name="location" required placeholder="Informe onde a atividade foi realizada"/></label><label className="field"><span>Situação</span><select name="status"><option>Em andamento</option><option>Concluído</option><option>Requer retorno</option><option>Impedimento encontrado</option></select></label><label className="field full"><span>Observações</span><textarea name="notes" placeholder="Descreva o serviço, resultados e pendências."/></label><p className="offline-form-note"><ShieldCheck size={14}/>O registro será sincronizado no armazenamento central e ficará disponível para a equipe autorizada.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setFieldModal(false)}>Cancelar</button><button className="button primary"><MapPin size={15}/>Registrar atividade</button></div></form></section></div>}
  </section>;
}

