"use client";

import { FormEvent, useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BookOpenCheck,
  Building2,
  Check,
  CheckCircle2,
  ChevronRight,
  ClipboardCheck,
  Clock3,
  CloudOff,
  FileText,
  Gauge,
  HeartHandshake,
  Layers3,
  ListChecks,
  LockKeyhole,
  Map,
  MapPin,
  Navigation,
  Plus,
  Search,
  Send,
  ShieldCheck,
  Smartphone,
  Target,
  UsersRound,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

type Notify = (message: string) => void;
type WorkspaceTab = "Painel setorial" | "Cadastros e formulários" | "Mapa municipal" | "Equipes de campo" | "Metas e indicadores" | "Encaminhamentos";
type Metric = [label: string, value: string, detail: string];
type RecordRow = [title: string, detail: string, status: string];

type SectorProfile = {
  title: string;
  mission: string;
  recordLabel: string;
  recordDescription: string;
  primaryField: string;
  secondaryField: string;
  privacy: string;
  metrics: Metric[];
  modules: string[];
  forms: string[];
  records: RecordRow[];
  mapLayers: string[];
  mapPoints: Array<[string, string, string]>;
  teams: Array<[string, string, string]>;
  goals: Array<[string, number, string]>;
};

const DEFAULT_PROFILE: SectorProfile = {
  title: "Gestão setorial",
  mission: "Organize os serviços, os atendimentos, as equipes e as prioridades específicas desta unidade municipal.",
  recordLabel: "registro setorial", recordDescription: "Novo registro operacional", primaryField: "Assunto principal", secondaryField: "Local ou interessado",
  privacy: "Os registros seguem as permissões do setor e preservam informações restritas.",
  metrics: [["Registros ativos","24","6 atualizados hoje"],["Dentro do prazo","91%","Meta: 90%"],["Ações de campo","8","3 em andamento"],["Concluídos no mês","42","+11% sobre julho"]],
  modules: ["Atendimentos","Planejamento","Equipes","Documentos","Agenda","Indicadores"],
  forms: ["Registro geral","Visita técnica","Relatório de atividade","Solicitação interna"],
  records: [["Demanda setorial em acompanhamento","Registro atualizado pela equipe","Em andamento"],["Planejamento mensal da unidade","Responsáveis e prazos definidos","Planejado"],["Relatório de atividade de campo","Evidências anexadas","Concluído"]],
  mapLayers: ["Atendimentos","Equipes","Equipamentos"],
  mapPoints: [["Centro","Atendimento em execução","Em andamento"],["Planalto","Visita técnica agendada","Agendado"],["Pinlar","Serviço concluído","Concluído"]],
  teams: [["Equipe de atendimento","3 servidores","Disponível"],["Equipe técnica","4 servidores","Em campo"],["Apoio administrativo","2 servidores","Na unidade"]],
  goals: [["Concluir demandas dentro do prazo",91,"Meta 90%"],["Atualizar registros prioritários",74,"Meta 85%"],["Executar agenda de campo",68,"Meta 80%"]],
};

const PROFILES: Record<string, SectorProfile> = {
  "Secretaria de Desenvolvimento Social": {
    title:"Proteção e acompanhamento social", mission:"Acompanhe famílias, benefícios, visitas e encaminhamentos, com cuidado especial para situações de vulnerabilidade.", recordLabel:"atendimento familiar", recordDescription:"Cadastrar atendimento ou acompanhamento", primaryField:"Família ou pessoa atendida", secondaryField:"Bairro, unidade ou território", privacy:"Prontuários e dados de vulnerabilidade são restritos aos profissionais autorizados; indicadores usam dados agregados.",
    metrics:[["Famílias acompanhadas","284","19 com prioridade"],["Visitas agendadas","18","7 para esta semana"],["Benefícios em análise","31","9 aguardam documento"],["Encaminhamentos","46","12 sem retorno"]],
    modules:["Prontuário familiar","Avaliação de vulnerabilidade","Visitas domiciliares","Benefícios e auxílios","Encaminhamentos","Plano de acompanhamento"],
    forms:["Atendimento familiar","Visita domiciliar","Concessão de benefício","Encaminhamento protegido","Atualização do prontuário"],
    records:[["Família 2026-0148 · acompanhamento","Visita realizada no bairro Planalto","Acompanhamento"],["Solicitação de benefício eventual","Documentação em conferência","Em análise"],["Encaminhamento para rede de saúde","Compartilhamento mínimo autorizado","Aguardando retorno"]],
    mapLayers:["Famílias acompanhadas","Visitas programadas","Unidades da rede"], mapPoints:[["Planalto","5 visitas domiciliares","Prioridade"],["Pinlar I","CRAS · 18 atendimentos hoje","Ativo"],["Barra do Guaicuí","Ação comunitária agendada","Agendado"]],
    teams:[["Equipe de referência CRAS","5 profissionais","Em atendimento"],["Equipe de visitas","3 profissionais","Em campo"],["Cadastro e benefícios","4 profissionais","Na unidade"]], goals:[["Atualizar prontuários prioritários",82,"Meta 90%"],["Obter retorno dos encaminhamentos",61,"Meta 80%"],["Executar visitas programadas",76,"Meta 85%"]],
  },
  "Secretaria de Saúde": {
    title:"Coordenação da rede municipal de saúde", mission:"Acompanhe regulação, campanhas, transportes, insumos e ocorrências das unidades sem expor dados clínicos indevidamente.", recordLabel:"registro de saúde", recordDescription:"Cadastrar ação, solicitação ou ocorrência", primaryField:"Pessoa, unidade ou campanha", secondaryField:"Unidade, destino ou território", privacy:"Dados pessoais e clínicos recebem acesso restrito; o painel gerencial apresenta somente informações agregadas.",
    metrics:[["Regulação pendente","67","14 com prioridade"],["Transportes agendados","22","6 para amanhã"],["Campanhas ativas","4","9 pontos de atendimento"],["Insumos críticos","3","Reposição solicitada"]], modules:["Regulação de consultas","Transporte para tratamento","Campanhas de saúde","Visitas domiciliares","Medicamentos e insumos","Ocorrências das unidades"], forms:["Solicitação de regulação","Transporte sanitário","Visita domiciliar","Ocorrência de unidade","Reposição de insumo"], records:[["Campanha de vacinação de agosto","Calendário em aprovação","Planejado"],["Transporte regional · rota 18/08","8 passageiros confirmados","Agendado"],["Reposição de material na UBS Norte","Pedido encaminhado ao almoxarifado","Em atendimento"]], mapLayers:["Unidades de saúde","Campanhas","Rotas sanitárias"], mapPoints:[["UBS Norte","Vacinação · 86 atendimentos","Ativo"],["Centro","Rota de transporte 03","Em deslocamento"],["Planalto","Visitas domiciliares","Agendado"]], teams:[["Equipe de regulação","4 profissionais","Na unidade"],["Atenção domiciliar","5 profissionais","Em campo"],["Transporte sanitário","3 motoristas","Em rota"]], goals:[["Reduzir pendências de regulação",73,"Meta 85%"],["Cumprir rotas agendadas",94,"Meta 95%"],["Manter insumos acima do mínimo",88,"Meta 98%"]],
  },
  "Secretaria de Educação": {
    title:"Gestão da rede municipal de ensino", mission:"Centralize matrículas, transporte escolar, calendário, manutenção, alimentação e solicitações das unidades.", recordLabel:"registro educacional", recordDescription:"Cadastrar solicitação ou acompanhamento escolar", primaryField:"Aluno, turma ou unidade", secondaryField:"Escola, rota ou comunidade", privacy:"Dados de estudantes e responsáveis ficam restritos às equipes autorizadas e às finalidades educacionais.",
    metrics:[["Matrículas em análise","38","12 transferências"],["Rotas escolares","17","2 exigem ajuste"],["Manutenções abertas","11","4 prioritárias"],["Frequência monitorada","96%","23 alertas ativos"]], modules:["Matrículas e transferências","Transporte escolar","Calendário letivo","Manutenção das escolas","Merenda e materiais","Acompanhamento de frequência"], forms:["Matrícula ou transferência","Alteração de rota","Pedido de manutenção","Solicitação de material","Alerta de frequência"], records:[["Transferência para Escola Municipal Norte","Documentos conferidos","Em análise"],["Rota escolar Zona Norte","Novo itinerário em validação","Aguardando aprovação"],["Reparo no telhado da Escola Central","Vistoria técnica anexada","Em execução"]], mapLayers:["Escolas municipais","Rotas escolares","Manutenções"], mapPoints:[["Escola Central","Reparo no telhado","Em execução"],["Zona Norte","Rota 07 · ajuste solicitado","Atenção"],["Barra do Guaicuí","Entrega de material didático","Agendado"]], teams:[["Gestão escolar","5 servidores","Na secretaria"],["Transporte escolar","8 profissionais","Em rota"],["Manutenção das unidades","4 servidores","Em campo"]], goals:[["Concluir matrículas no prazo",89,"Meta 95%"],["Regularizar rotas escolares",82,"Meta 100%"],["Atender manutenções prioritárias",71,"Meta 90%"]],
  },
  "Secretaria de Infraestrutura e Transporte": {
    title:"Manutenção urbana e mobilidade", mission:"Gerencie ordens georreferenciadas de iluminação, pavimentação, drenagem, limpeza e sinalização.", recordLabel:"ordem de serviço", recordDescription:"Abrir ordem de manutenção urbana", primaryField:"Tipo de serviço ou ocorrência", secondaryField:"Endereço e referência", privacy:"Localizações de serviços são operacionais; dados do solicitante permanecem protegidos.",
    metrics:[["Ordens abertas","53","14 prioritárias"],["Equipes em campo","6","21 servidores"],["Iluminação pendente","18","7 para hoje"],["Dentro do SLA","87%","Meta: 90%"]], modules:["Iluminação pública","Pavimentação e buracos","Drenagem","Limpeza urbana","Sinalização","Estradas e acessos"], forms:["Reparo em iluminação","Operação tapa-buraco","Limpeza ou retirada","Vistoria de drenagem","Implantação de sinalização"], records:[["Iluminação da Praça Central","Equipe elétrica no local","Em execução"],["Buraco na Rua Dr. Ensch","Área sinalizada para reparo","Programado"],["Limpeza de canal no Planalto","Máquina e equipe designadas","Em execução"]], mapLayers:["Ordens de serviço","Iluminação","Drenagem e pavimento"], mapPoints:[["Praça Central","Revisão de luminárias","Em execução"],["Rua Dr. Ensch","Reparo de pavimento","Programado"],["Bairro Planalto","Limpeza de drenagem","Em campo"]], teams:[["Elétrica e iluminação","4 servidores","Em campo"],["Pavimentação","7 servidores","Em execução"],["Drenagem e limpeza","6 servidores","Em campo"]], goals:[["Atender ordens dentro do SLA",87,"Meta 90%"],["Reduzir pontos sem iluminação",78,"Meta 95%"],["Executar manutenção preventiva",64,"Meta 80%"]],
  },
  "Secretaria de Administração e Finanças": {
    title:"Administração, orçamento e suprimentos", mission:"Acompanhe compras, contratos, pagamentos, patrimônio, estoque e autorizações administrativas.", recordLabel:"processo administrativo-financeiro", recordDescription:"Cadastrar solicitação administrativa", primaryField:"Objeto, fornecedor ou despesa", secondaryField:"Unidade solicitante ou centro de custo", privacy:"Valores e documentos seguem o nível de publicidade do processo; dados pessoais e bancários são restritos.",
    metrics:[["Compras em andamento","19","6 em cotação"],["Pagamentos previstos","27","R$ 486 mil"],["Contratos a vencer","3","Até 45 dias"],["Execução acompanhada","74%","Referência anual"]], modules:["Solicitações de compra","Fornecedores e cotações","Contratos e pagamentos","Execução orçamentária","Patrimônio","Almoxarifado"], forms:["Solicitação de compra","Pesquisa de preços","Ordem de pagamento","Movimentação patrimonial","Requisição ao almoxarifado"], records:[["Aquisição de material escolar","Pesquisa de preços concluída","Em aprovação"],["Pagamento do contrato CT-2026-041","Liquidação conferida","Programado"],["Transferência de projetor patrimonial","Destino validado","Em andamento"]], mapLayers:["Unidades requisitantes","Bens patrimoniais","Almoxarifados"], mapPoints:[["Paço Municipal","12 processos financeiros","Ativo"],["Almoxarifado Central","Inventário mensal","Em execução"],["Secretaria de Educação","Entrega programada","Agendado"]], teams:[["Compras e licitações","5 servidores","Em análise"],["Finanças e tesouraria","4 servidores","Na unidade"],["Patrimônio e estoque","6 servidores","Em inventário"]], goals:[["Concluir compras planejadas",69,"Meta 85%"],["Evitar vencimento contratual",91,"Meta 100%"],["Atualizar inventário patrimonial",77,"Meta 90%"]],
  },
  "Secretaria de Governo": {
    title:"Coordenação estratégica do governo", mission:"Acompanhe prioridades, projetos intersetoriais, decisões, agendas e compromissos assumidos pelas secretarias.", recordLabel:"prioridade de governo", recordDescription:"Cadastrar prioridade, decisão ou compromisso", primaryField:"Projeto, decisão ou compromisso", secondaryField:"Secretarias envolvidas", privacy:"Decisões internas permanecem restritas até sua formalização ou publicação.",
    metrics:[["Prioridades ativas","26","7 intersetoriais"],["Decisões pendentes","8","3 para hoje"],["Projetos estratégicos","12","68% de avanço médio"],["Compromissos no prazo","89%","Meta 92%"]], modules:["Prioridades de governo","Projetos intersetoriais","Decisões administrativas","Agenda estratégica","Compromissos","Monitoramento de metas"], forms:["Nova prioridade","Decisão administrativa","Pauta intersetorial","Compromisso de governo","Atualização de projeto"], records:[["Operação Volta às Aulas","Educação e Transporte alinhados","Em andamento"],["Revitalização do Centro","Próxima decisão em 18/08","Aguardando decisão"],["Plano de atendimento regional","Metas consolidadas","Em monitoramento"]], mapLayers:["Projetos estratégicos","Compromissos territoriais","Equipamentos públicos"], mapPoints:[["Centro","Projeto de revitalização","Em andamento"],["Zona Norte","Compromisso de mobilidade","Planejado"],["Barra do Guaicuí","Agenda territorial","Agendado"]], teams:[["Coordenação de projetos","4 servidores","Na unidade"],["Articulação intersetorial","3 servidores","Em reunião"],["Monitoramento de metas","2 servidores","Atualizando dados"]], goals:[["Cumprir compromissos estratégicos",89,"Meta 92%"],["Atualizar projetos semanalmente",78,"Meta 100%"],["Resolver decisões pendentes",63,"Meta 85%"]],
  },
  "Gabinete do Prefeito": {
    title:"Agenda e compromissos do Executivo", mission:"Organize audiências, visitas, despachos, demandas da população e compromissos assumidos pelo gabinete.", recordLabel:"demanda do gabinete", recordDescription:"Registrar audiência, demanda ou compromisso", primaryField:"Cidadão, entidade ou compromisso", secondaryField:"Local, comunidade ou secretaria", privacy:"Audiências e dados pessoais têm acesso controlado; compromissos públicos podem ser divulgados após validação.",
    metrics:[["Audiências agendadas","14","5 nesta semana"],["Demandas recebidas","32","11 encaminhadas"],["Despachos pendentes","6","2 prioritários"],["Compromissos cumpridos","86%","No mês"]], modules:["Agenda institucional","Audiências com cidadãos","Demandas recebidas","Visitas oficiais","Despachos","Compromissos do Executivo"], forms:["Solicitação de audiência","Registro de demanda","Agenda oficial","Despacho do gabinete","Compromisso público"], records:[["Audiência com associação comercial","Pauta confirmada para 19/08","Agendado"],["Demanda comunitária da Zona Norte","Encaminhada à Infraestrutura","Em atendimento"],["Visita à UBS Norte","Equipe e cerimonial confirmados","Planejado"]], mapLayers:["Visitas oficiais","Demandas territoriais","Agenda pública"], mapPoints:[["UBS Norte","Visita oficial","Agendado"],["Centro","Audiência comunitária","Confirmado"],["Barra do Guaicuí","Agenda territorial","Planejado"]], teams:[["Agenda e cerimonial","3 servidores","Na unidade"],["Atendimento ao cidadão","4 servidores","Em atendimento"],["Assessoria institucional","3 servidores","Em agenda externa"]], goals:[["Responder demandas do gabinete",84,"Meta 90%"],["Cumprir agenda confirmada",96,"Meta 98%"],["Acompanhar encaminhamentos",72,"Meta 85%"]],
  },
  "Secretaria de Comunicação e Eventos": {
    title:"Comunicação pública e eventos", mission:"Organize pedidos de conteúdo, aprovações, calendário editorial, cobertura, imprensa, cerimonial e acervo de mídia.", recordLabel:"pedido de comunicação", recordDescription:"Cadastrar peça, cobertura ou evento", primaryField:"Campanha, peça ou evento", secondaryField:"Secretaria solicitante ou local", privacy:"Conteúdos internos e dados de participantes permanecem restritos até aprovação e publicação.",
    metrics:[["Pedidos em produção","17","6 para hoje"],["Conteúdos em aprovação","8","3 prioritários"],["Eventos próximos","5","2 com cobertura"],["Acervo no mês","286","Fotos e vídeos"]], modules:["Pedidos de arte","Produção de conteúdo","Calendário editorial","Aprovação e publicação","Cobertura de eventos","Imprensa e cerimonial"], forms:["Solicitação de arte","Pedido de cobertura","Nota institucional","Evento e cerimonial","Autorização de publicação"], records:[["Campanha de vacinação","Cards em aprovação","Aguardando aprovação"],["Feira do produtor","Equipe de cobertura definida","Agendado"],["Boletim semanal da prefeitura","Textos recebidos dos setores","Em produção"]], mapLayers:["Eventos municipais","Locais de cobertura","Equipamentos culturais"], mapPoints:[["Praça Central","Feira do produtor","Agendado"],["Auditório Municipal","Coletiva de imprensa","Confirmado"],["Estação Ferroviária","Evento cultural","Planejado"]], teams:[["Criação e design","3 profissionais","Em produção"],["Imprensa e conteúdo","4 profissionais","Na unidade"],["Eventos e cerimonial","5 profissionais","Em preparação"]], goals:[["Entregar pedidos no prazo",88,"Meta 92%"],["Aprovar calendário editorial",75,"Meta 90%"],["Organizar acervo de mídia",67,"Meta 80%"]],
  },
  "Secretaria Municipal de Desenvolvimento Econômico, Agricultura e Meio Ambiente": {
    title:"Desenvolvimento, produção rural e meio ambiente", mission:"Acompanhe produtores, empreendedores, visitas técnicas, feiras, licenças e ocorrências ambientais.", recordLabel:"atendimento produtivo ou ambiental", recordDescription:"Cadastrar produtor, empresa, visita ou ocorrência", primaryField:"Produtor, empreendimento ou ocorrência", secondaryField:"Propriedade, endereço ou comunidade", privacy:"Dados econômicos e pessoais permanecem restritos; informações ambientais públicas passam por validação.",
    metrics:[["Produtores atendidos","146","18 neste mês"],["Visitas técnicas","21","8 agendadas"],["Licenças em análise","13","4 aguardam documento"],["Ocorrências ambientais","9","3 prioritárias"]], modules:["Cadastro de produtores","Apoio ao empreendedor","Visitas técnicas","Feiras e programas","Licenciamento","Ocorrências ambientais"], forms:["Cadastro de produtor","Visita técnica rural","Atendimento ao empreendedor","Ocorrência ambiental","Inscrição em feira"], records:[["Produtor rural · comunidade Lagoa","Visita técnica agendada","Agendado"],["Feira municipal de agosto","32 expositores inscritos","Em preparação"],["Descarte irregular no acesso norte","Vistoria ambiental solicitada","Prioridade"]], mapLayers:["Propriedades atendidas","Ocorrências ambientais","Feiras e empreendimentos"], mapPoints:[["Comunidade Lagoa","Visita agronômica","Agendado"],["Acesso Norte","Ocorrência ambiental","Prioridade"],["Praça Central","Feira de produtores","Confirmado"]], teams:[["Assistência técnica rural","4 profissionais","Em campo"],["Desenvolvimento econômico","3 profissionais","Em atendimento"],["Fiscalização ambiental","3 profissionais","Em vistoria"]], goals:[["Ampliar assistência aos produtores",72,"Meta 85%"],["Concluir licenças no prazo",81,"Meta 90%"],["Responder ocorrências ambientais",67,"Meta 88%"]],
  },
  "Secretaria de Cultura e Turismo": {
    title:"Cultura, memória e turismo", mission:"Gerencie artistas, grupos, editais, eventos, espaços culturais, oficinas, roteiros turísticos e projetos.", recordLabel:"projeto cultural ou turístico", recordDescription:"Cadastrar artista, evento, espaço ou projeto", primaryField:"Artista, projeto, evento ou roteiro", secondaryField:"Espaço, localidade ou proponente", privacy:"Dados de proponentes são protegidos; resultados e agendas públicas dependem de aprovação.",
    metrics:[["Agentes culturais","218","17 cadastros novos"],["Projetos em análise","24","8 de edital"],["Eventos próximos","7","3 nesta semana"],["Espaços reservados","11","76% de ocupação"]], modules:["Cadastro cultural","Editais e projetos","Calendário de eventos","Reserva de espaços","Oficinas","Roteiros turísticos"], forms:["Cadastro de artista ou grupo","Inscrição em edital","Reserva de espaço","Proposta de evento","Cadastro turístico"], records:[["Mostra de cultura popular","Programação em aprovação","Em análise"],["Oficina de fotografia","28 inscritos confirmados","Agendado"],["Roteiro histórico da Estação","Conteúdo em revisão","Em produção"]], mapLayers:["Espaços culturais","Pontos turísticos","Eventos"], mapPoints:[["Estação Ferroviária","Roteiro histórico","Ativo"],["Casa da Cultura","Oficina de fotografia","Agendado"],["Praça Central","Mostra cultural","Planejado"]], teams:[["Produção cultural","4 profissionais","Em preparação"],["Turismo e roteiros","3 profissionais","Em campo"],["Gestão de espaços","3 profissionais","Na unidade"]], goals:[["Executar calendário cultural",78,"Meta 90%"],["Atualizar cadastro de agentes",66,"Meta 80%"],["Ampliar ocupação dos espaços",76,"Meta 85%"]],
  },
  "Controle Interno": {
    title:"Auditoria, riscos e conformidade", mission:"Planeje auditorias, registre achados, recomendações, responsáveis, evidências e planos de ação.", recordLabel:"trabalho de auditoria", recordDescription:"Cadastrar auditoria, achado ou recomendação", primaryField:"Objeto, processo ou recomendação", secondaryField:"Unidade auditada ou responsável", privacy:"Papéis de trabalho e apurações têm acesso restrito; relatórios seguem a classificação definida.",
    metrics:[["Auditorias em curso","7","3 na fase de campo"],["Recomendações abertas","22","8 vencem no mês"],["Planos de ação","15","73% de execução"],["Riscos críticos","4","Monitoramento ativo"]], modules:["Plano anual de auditoria","Matriz de riscos","Achados e evidências","Recomendações","Planos de ação","Conformidade"], forms:["Nova auditoria","Registro de achado","Recomendação","Plano de ação","Teste de conformidade"], records:[["Auditoria de contratos de manutenção","Amostra documental concluída","Em execução"],["Recomendação CI-2026-018","Prazo de resposta em 20/08","Aguardando resposta"],["Matriz de riscos de compras","Riscos críticos revisados","Concluído"]], mapLayers:["Unidades auditadas","Ações de campo","Riscos territoriais"], mapPoints:[["Paço Municipal","Auditoria de contratos","Em execução"],["Almoxarifado","Teste de inventário","Agendado"],["Obras","Verificação em campo","Planejado"]], teams:[["Auditoria administrativa","3 servidores","Em análise"],["Auditoria de campo","2 servidores","Em vistoria"],["Monitoramento de recomendações","2 servidores","Na unidade"]], goals:[["Executar plano anual",71,"Meta 85%"],["Reduzir recomendações vencidas",64,"Meta 90%"],["Monitorar riscos críticos",92,"Meta 100%"]],
  },
  "Departamento de Execução de Obras": {
    title:"Execução e fiscalização de obras", mission:"Centralize diário de obra, medições, contratos, equipes, materiais, fotos, custos e progresso físico.", recordLabel:"registro de obra", recordDescription:"Cadastrar obra, medição ou diário de campo", primaryField:"Obra, serviço ou medição", secondaryField:"Local, contrato ou frente de trabalho", privacy:"Medições e documentos contratuais seguem o nível de acesso do processo vinculado.",
    metrics:[["Obras em execução","9","2 com atenção"],["Medições pendentes","6","R$ 318 mil"],["Equipes em campo","5","24 trabalhadores"],["Avanço médio","63%","Sem atraso geral"]], modules:["Diário de obra","Medições","Contratos vinculados","Equipes e materiais","Fiscalização","Fotos e progresso"], forms:["Diário de obra","Nova medição","Vistoria técnica","Uso de material","Ocorrência da obra"], records:[["Revitalização da Praça Central","68% de avanço físico","Em execução"],["Reforma da UBS Norte","Medição nº 04 em conferência","Medição"],["Drenagem do bairro Planalto","Ordem de início preparada","Planejado"]], mapLayers:["Obras ativas","Frentes de trabalho","Vistorias"], mapPoints:[["Praça Central","Revitalização · 68%","Em execução"],["UBS Norte","Reforma · 42%","Em execução"],["Bairro Planalto","Drenagem pluvial","Planejado"]], teams:[["Fiscalização de obras","4 profissionais","Em campo"],["Equipe de execução 01","8 trabalhadores","Praça Central"],["Equipe de drenagem","6 trabalhadores","Em preparação"]], goals:[["Cumprir cronogramas",82,"Meta 90%"],["Conferir medições no prazo",73,"Meta 95%"],["Atualizar diários de obra",88,"Meta 100%"]],
  },
  "Departamento de Transportes": {
    title:"Frota, viagens e logística municipal", mission:"Controle reservas, motoristas, rotas, abastecimentos, quilometragem, manutenção, documentos e disponibilidade.", recordLabel:"movimentação de transporte", recordDescription:"Cadastrar viagem, reserva ou manutenção", primaryField:"Veículo, viagem ou serviço", secondaryField:"Destino, motorista ou setor solicitante", privacy:"Dados de passageiros e rotas sensíveis ficam disponíveis somente aos responsáveis autorizados.",
    metrics:[["Veículos disponíveis","18","De 24 ativos"],["Viagens agendadas","16","7 para amanhã"],["Manutenções abertas","4","1 prioritária"],["Documentos a vencer","2","Próximos 30 dias"]], modules:["Reserva de veículos","Motoristas e escalas","Rotas e viagens","Abastecimentos","Manutenção","Documentos e seguros"], forms:["Reserva de veículo","Ordem de viagem","Abastecimento","Solicitação de manutenção","Ocorrência de transporte"], records:[["Micro-ônibus Saúde · rota regional","Motorista e passageiros confirmados","Agendado"],["Caminhão compactador RTA-3C92","Manutenção do sistema hidráulico","Em manutenção"],["Veículo PVE-2041","Revisão preventiva programada","Planejado"]], mapLayers:["Veículos em rota","Garagens","Destinos agendados"], mapPoints:[["Garagem Municipal","18 veículos disponíveis","Ativo"],["Rota Regional","Micro-ônibus Saúde","Em deslocamento"],["Oficina credenciada","Caminhão em manutenção","Em atendimento"]], teams:[["Operação de frota","4 servidores","Na garagem"],["Motoristas escalados","11 motoristas","Em rota"],["Manutenção e documentos","3 servidores","Na unidade"]], goals:[["Cumprir viagens agendadas",94,"Meta 98%"],["Executar manutenção preventiva",79,"Meta 90%"],["Manter documentos regulares",92,"Meta 100%"]],
  },
  "Departamento de Esporte e Lazer / Subseção de Esportes": {
    title:"Esporte, lazer e escolinhas municipais", mission:"Organize modalidades, turmas, participantes, competições, espaços, frequência e materiais esportivos.", recordLabel:"atividade esportiva", recordDescription:"Cadastrar turma, evento ou atendimento esportivo", primaryField:"Modalidade, turma ou competição", secondaryField:"Espaço, professor ou comunidade", privacy:"Dados de participantes, especialmente menores, ficam restritos aos profissionais e responsáveis autorizados.",
    metrics:[["Participantes ativos","486","18 novas inscrições"],["Turmas em andamento","24","8 modalidades"],["Espaços reservados","17","82% de ocupação"],["Competições próximas","4","3 equipes inscritas"]], modules:["Inscrições e participantes","Turmas e frequência","Modalidades","Campeonatos","Reserva de espaços","Materiais esportivos"], forms:["Inscrição em atividade","Lista de presença","Reserva de quadra","Cadastro de campeonato","Empréstimo de material"], records:[["Escolinha de futsal Sub-13","28 participantes ativos","Em andamento"],["Campeonato Municipal 2026","Tabela de jogos em revisão","Em preparação"],["Quadra do Planalto","Reserva para treinamento","Confirmado"]], mapLayers:["Espaços esportivos","Turmas","Competições"], mapPoints:[["Ginásio Municipal","Treino de futsal","Em atividade"],["Quadra do Planalto","Turma de vôlei","Agendado"],["Campo da Barra","Campeonato amador","Planejado"]], teams:[["Professores e monitores","8 profissionais","Em atividade"],["Eventos esportivos","4 servidores","Em preparação"],["Gestão de espaços","3 servidores","Na unidade"]], goals:[["Manter frequência das turmas",86,"Meta 90%"],["Executar calendário esportivo",74,"Meta 88%"],["Atualizar materiais e espaços",69,"Meta 85%"]],
  },
  "Departamento de Vigilância Sanitária": {
    title:"Fiscalização e vigilância sanitária", mission:"Acompanhe estabelecimentos, inspeções, risco, licenças, notificações, denúncias e prazos de adequação.", recordLabel:"ação sanitária", recordDescription:"Cadastrar inspeção, licença ou denúncia", primaryField:"Estabelecimento ou ocorrência", secondaryField:"Endereço, atividade ou responsável", privacy:"Denunciantes e dados pessoais recebem proteção; autos e licenças seguem a publicidade aplicável.",
    metrics:[["Inspeções programadas","18","7 nesta semana"],["Licenças em análise","23","6 aguardam documento"],["Adequações pendentes","14","4 vencem no mês"],["Denúncias recebidas","7","2 prioritárias"]], modules:["Cadastro de estabelecimentos","Inspeções","Classificação de risco","Licenças","Notificações e autos","Denúncias sanitárias"], forms:["Inspeção sanitária","Pedido de licença","Notificação de adequação","Auto sanitário","Denúncia protegida"], records:[["Restaurante Centro · inspeção periódica","Checklist sanitário programado","Agendado"],["Farmácia Planalto · renovação de licença","Documentação em análise","Em análise"],["Denúncia VS-2026-041","Identidade do denunciante protegida","Prioridade"]], mapLayers:["Estabelecimentos","Inspeções programadas","Ocorrências sanitárias"], mapPoints:[["Centro","5 inspeções programadas","Agendado"],["Planalto","Renovação de licença","Em análise"],["Pinlar I","Ocorrência sanitária","Prioridade"]], teams:[["Inspeção de alimentos","3 fiscais","Em campo"],["Licenciamento sanitário","3 servidores","Na unidade"],["Atendimento a denúncias","2 fiscais","Em vistoria"]], goals:[["Cumprir plano de inspeções",81,"Meta 90%"],["Concluir licenças no prazo",76,"Meta 90%"],["Monitorar adequações vencidas",68,"Meta 95%"]],
  },
  "Seção de Controle e Avaliação": {
    title:"Controle, regulação e avaliação de serviços", mission:"Acompanhe autorizações, filas, capacidade, produção das unidades, solicitações pendentes e auditoria dos atendimentos.", recordLabel:"controle ou avaliação", recordDescription:"Cadastrar autorização, análise ou avaliação", primaryField:"Serviço, autorização ou unidade", secondaryField:"Usuário, prestador ou referência", privacy:"Registros individualizados ficam restritos; relatórios gerenciais usam informações consolidadas.",
    metrics:[["Autorizações pendentes","41","9 prioritárias"],["Fila monitorada","128","-8% no mês"],["Unidades avaliadas","12","4 neste ciclo"],["Produção conferida","93%","Referência mensal"]], modules:["Autorizações","Filas de atendimento","Capacidade dos serviços","Produção das unidades","Auditoria de atendimentos","Indicadores"], forms:["Solicitação de autorização","Avaliação de unidade","Conferência de produção","Registro de fila","Auditoria de atendimento"], records:[["Autorizações do período 13/08","31 itens conferidos","Em análise"],["Avaliação da Unidade Norte","Indicadores consolidados","Em execução"],["Fila de especialidade regional","Prioridades atualizadas","Monitoramento"]], mapLayers:["Unidades avaliadas","Capacidade regional","Filas por território"], mapPoints:[["Unidade Norte","Avaliação de capacidade","Em execução"],["Centro","Produção em conferência","Em análise"],["Barra do Guaicuí","Demanda regional","Monitoramento"]], teams:[["Controle de autorizações","4 servidores","Na unidade"],["Avaliação e auditoria","3 servidores","Em análise"],["Monitoramento de filas","2 servidores","Atualizando dados"]], goals:[["Analisar autorizações no prazo",84,"Meta 92%"],["Atualizar filas semanalmente",91,"Meta 100%"],["Concluir ciclo de avaliação",68,"Meta 85%"]],
  },
  "Subseção de Patrimônio Histórico e Cultura": {
    title:"Patrimônio histórico e acervo cultural", mission:"Inventarie bens, documente conservação, acompanhe intervenções, pedidos de reforma e o acervo histórico digital.", recordLabel:"bem ou registro histórico", recordDescription:"Cadastrar bem, intervenção ou documento", primaryField:"Bem, imóvel, acervo ou intervenção", secondaryField:"Localização, proprietário ou responsável", privacy:"Acervos públicos podem ser consultados após curadoria; dados pessoais e laudos internos têm acesso restrito.",
    metrics:[["Bens inventariados","96","8 em revisão"],["Vistorias previstas","12","5 no mês"],["Intervenções em análise","7","2 prioritárias"],["Itens digitalizados","1.284","74% do acervo"]], modules:["Inventário de bens","Estado de conservação","Vistorias","Intervenções","Acervo fotográfico","Documentação histórica"], forms:["Cadastro de bem histórico","Vistoria de conservação","Pedido de intervenção","Registro fotográfico","Digitalização de acervo"], records:[["Estação Ferroviária","Vistoria de conservação concluída","Monitoramento"],["Casa da Cultura","Pedido de intervenção em análise","Em análise"],["Acervo fotográfico municipal","86 imagens digitalizadas no mês","Em execução"]], mapLayers:["Bens inventariados","Vistorias","Intervenções"], mapPoints:[["Estação Ferroviária","Bem inventariado","Monitoramento"],["Casa da Cultura","Intervenção proposta","Em análise"],["Centro Histórico","Roteiro de vistoria","Agendado"]], teams:[["Inventário e pesquisa","3 profissionais","Em documentação"],["Conservação e vistoria","2 profissionais","Em campo"],["Acervo digital","3 profissionais","Na unidade"]], goals:[["Revisar inventário municipal",72,"Meta 85%"],["Digitalizar acervo prioritário",74,"Meta 90%"],["Vistoriar bens críticos",83,"Meta 100%"]],
  },
  "Subprefeitura da Barra do Guaicuí": {
    title:"Gestão territorial da Barra do Guaicuí", mission:"Centralize demandas comunitárias, manutenção local, estradas, iluminação, limpeza, agenda e visitas às comunidades.", recordLabel:"demanda territorial", recordDescription:"Cadastrar atendimento ou serviço local", primaryField:"Demanda, serviço ou comunidade", secondaryField:"Endereço, estrada ou ponto de referência", privacy:"Dados dos moradores permanecem protegidos; a situação dos serviços pode ser divulgada de forma agregada.",
    metrics:[["Demandas locais","29","8 prioritárias"],["Serviços em campo","7","3 equipes"],["Estradas monitoradas","12","2 com atenção"],["Atendimentos no mês","84","18 nesta semana"]], modules:["Atendimento comunitário","Manutenção local","Estradas e acessos","Iluminação e limpeza","Agenda comunitária","Visitas territoriais"], forms:["Demanda comunitária","Vistoria de estrada","Reparo de iluminação","Limpeza local","Visita à comunidade"], records:[["Acesso à comunidade Ribeirinha","Vistoria de estrada programada","Agendado"],["Iluminação da Rua São Pedro","Equipe acionada","Em atendimento"],["Reunião comunitária de agosto","Pauta aberta para contribuições","Confirmado"]], mapLayers:["Demandas locais","Estradas","Equipamentos públicos"], mapPoints:[["Rua São Pedro","Reparo de iluminação","Em atendimento"],["Estrada Ribeirinha","Vistoria programada","Agendado"],["Sede da Subprefeitura","Atendimento comunitário","Ativo"]], teams:[["Atendimento local","3 servidores","Na unidade"],["Manutenção territorial","5 servidores","Em campo"],["Apoio comunitário","2 servidores","Em visita"]], goals:[["Responder demandas prioritárias",79,"Meta 90%"],["Vistoriar estradas monitoradas",67,"Meta 85%"],["Executar agenda comunitária",88,"Meta 95%"]],
  },
};

const TAB_META: Record<WorkspaceTab,{icon:LucideIcon;label:string}> = {
  "Painel setorial":{icon:Layers3,label:"Painel setorial"},
  "Cadastros e formulários":{icon:FileText,label:"Cadastros"},
  "Mapa municipal":{icon:Map,label:"Mapa"},
  "Equipes de campo":{icon:Smartphone,label:"Campo"},
  "Metas e indicadores":{icon:Target,label:"Metas"},
  "Encaminhamentos":{icon:Send,label:"Encaminhamentos"},
};

function profileFor(department:string):SectorProfile {
  return PROFILES[department] ?? DEFAULT_PROFILE;
}

function toneFor(status:string) {
  const value=status.toLowerCase();
  if(value.includes("concl")||value.includes("confirm")||value.includes("ativo")||value.includes("disponível")) return "success";
  if(value.includes("prior")||value.includes("atenção")) return "danger";
  if(value.includes("aguard")||value.includes("análise")||value.includes("planej")||value.includes("agend")) return "warning";
  return "info";
}

export function SectorWorkspaceSection({department,userName,userRole,departments,notify}:{department:string;userName:string;userRole:string;departments:string[];notify:Notify}) {
  const profile=profileFor(department);
  const [tab,setTab]=useState<WorkspaceTab>("Painel setorial");
  const [records,setRecords]=useState<RecordRow[]>(profile.records);
  const [recordModal,setRecordModal]=useState(false);
  const [fieldModal,setFieldModal]=useState(false);
  const [query,setQuery]=useState("");
  const [layer,setLayer]=useState("Todas as camadas");
  const [selectedPoint,setSelectedPoint]=useState(profile.mapPoints[0]);
  const [referrals,setReferrals]=useState<Array<[string,string,string]>>([["Secretaria de Administração e Finanças","Solicitação de apoio administrativo","Somente dados necessários"],["Secretaria de Comunicação e Eventos","Divulgação de ação do setor","Informações institucionais"]]);

  const visibleRecords=useMemo(()=>records.filter(item=>item.join(" ").toLowerCase().includes(query.toLowerCase())),[records,query]);

  function createRecord(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const item:RecordRow=[String(form.get("primary")),`${String(form.get("secondary"))} · ${String(form.get("notes"))||"Registro criado pela equipe"}`,"Cadastrado"];setRecords(current=>[item,...current]);setRecordModal(false);notify(`${profile.recordLabel[0].toUpperCase()+profile.recordLabel.slice(1)} cadastrado na área de ${department}.`);}
  function createFieldRecord(event:FormEvent<HTMLFormElement>){event.preventDefault();setFieldModal(false);notify("Atividade de campo registrada com localização, checklist e evidências simuladas.");}
  function createReferral(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const destination=String(form.get("destination"));const subject=String(form.get("subject"));const scope=String(form.get("scope"));setReferrals(current=>[[destination,subject,scope],...current]);event.currentTarget.reset();notify(`Encaminhamento preparado para ${destination} com compartilhamento controlado.`);}

  return <section className="sector-workspace">
    <article className="sector-hero">
      <span className="sector-hero-icon"><Building2 size={26}/></span>
      <div><p className="eyebrow">ÁREA ESPECÍFICA DO SETOR</p><h2>{profile.title}</h2><p>{profile.mission}</p><small><ShieldCheck size={13}/>{department} · {userRole} · acesso conforme o perfil</small></div>
      <div className="sector-hero-actions"><button className="button secondary" onClick={()=>setFieldModal(true)}><Navigation size={15}/> Registrar atividade externa</button><button className="button primary" onClick={()=>setRecordModal(true)}><Plus size={15}/> Cadastrar {profile.recordLabel}</button></div>
    </article>

    <nav className="sector-tabs" aria-label="Navegação da área do setor">{(Object.keys(TAB_META) as WorkspaceTab[]).map(item=>{const Icon=TAB_META[item].icon;return <button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}><Icon size={16}/><span>{TAB_META[item].label}</span></button>})}</nav>

    {tab==="Painel setorial"&&<>
      <div className="sector-metrics">{profile.metrics.map(([label,value,detail],index)=><article className="panel" key={label}><span className={["teal","blue","amber","green"][index]}>{[<Activity key="a" size={19}/>,<Clock3 key="b" size={19}/>,<AlertTriangle key="c" size={19}/>,<CheckCircle2 key="d" size={19}/>][index]}</span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article>)}</div>
      <div className="sector-overview-grid"><article className="panel sector-modules"><header><div><h3>Ferramentas de {profile.title.toLowerCase()}</h3><p>Recursos disponíveis somente para este contexto setorial.</p></div><Layers3 size={18}/></header><div>{profile.modules.map((module,index)=><button key={module} onClick={()=>{setTab("Cadastros e formulários");notify(`${module}: registros e formulários disponíveis.`)}}><span>{index+1}</span><strong>{module}</strong><ChevronRight size={14}/></button>)}</div></article><aside className="sector-side-stack"><article className="panel sector-priority"><header><AlertTriangle size={17}/><span><strong>Prioridades do setor</strong><small>Atualizadas hoje</small></span></header>{profile.records.slice(0,3).map(([title,detail,status])=><button key={title} onClick={()=>setTab("Cadastros e formulários")}><span><strong>{title}</strong><small>{detail}</small></span><i className={toneFor(status)}>{status}</i></button>)}</article><article className="panel sector-privacy"><LockKeyhole size={18}/><div><strong>Proteção e finalidade</strong><p>{profile.privacy}</p></div></article></aside></div>
    </>}

    {tab==="Cadastros e formulários"&&<div className="sector-record-layout"><aside className="panel sector-form-catalog"><header><BookOpenCheck size={19}/><div><h3>Formulários do setor</h3><p>Campos e checklists adaptados à atividade.</p></div></header>{profile.forms.map((form,index)=><button key={form} onClick={()=>setRecordModal(true)}><span>{String(index+1).padStart(2,"0")}</span><strong>{form}</strong><ChevronRight size={13}/></button>)}</aside><article className="panel sector-records"><div className="module-toolbar"><label className="module-search"><Search size={15}/><input aria-label="Buscar nos registros do setor" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar registros específicos..."/></label><select aria-label="Filtrar registros"><option>Todos os status</option><option>Prioridade</option><option>Em andamento</option><option>Concluídos</option></select><button className="button primary" onClick={()=>setRecordModal(true)}><Plus size={15}/> Novo registro</button></div><div className="sector-record-list">{visibleRecords.map(([title,detail,status],index)=><button key={`${title}-${index}`} onClick={()=>notify(`Ficha de “${title}” aberta com histórico, documentos e responsáveis.`)}><span className="sector-record-icon"><FileText size={16}/></span><span><strong>{title}</strong><small>{detail}</small></span><i className={toneFor(status)}>{status}</i><ChevronRight size={14}/></button>)}</div></article></div>}

    {tab==="Mapa municipal"&&<div className="sector-map-layout"><article className="panel sector-map-panel"><header><div><h3>Mapa operacional de {department}</h3><p>Camadas e pontos relacionados ao trabalho deste setor.</p></div><select aria-label="Camada do mapa" value={layer} onChange={event=>setLayer(event.target.value)}><option>Todas as camadas</option>{profile.mapLayers.map(item=><option key={item}>{item}</option>)}</select></header><div className="sector-map-canvas"><span className="map-road road-a"/><span className="map-road road-b"/><span className="map-road road-c"/><span className="map-river"/><small className="map-label label-center">Centro</small><small className="map-label label-planalto">Planalto</small><small className="map-label label-guaicui">Barra do Guaicuí</small>{profile.mapPoints.map((point,index)=><button aria-label={`${point[0]}: ${point[1]}`} key={point[0]} className={`map-point point-${index+1} ${selectedPoint[0]===point[0]?"selected":""}`} onClick={()=>setSelectedPoint(point)}><MapPin size={20}/><span>{index+1}</span></button>)}</div><footer>{profile.mapLayers.map((item,index)=><span key={item}><i className={`layer-${index+1}`}/>{item}</span>)}</footer></article><aside className="panel map-detail-card"><span className="map-detail-icon"><MapPin size={22}/></span><p className="eyebrow">PONTO SELECIONADO</p><h3>{selectedPoint[0]}</h3><p>{selectedPoint[1]}</p><i className={toneFor(selectedPoint[2])}>{selectedPoint[2]}</i><dl><div><dt>Setor responsável</dt><dd>{department}</dd></div><div><dt>Última atualização</dt><dd>Hoje, 14:36</dd></div><div><dt>Coordenadas</dt><dd>Localização operacional registrada</dd></div></dl><button className="button primary" onClick={()=>notify(`Ficha territorial de ${selectedPoint[0]} aberta.`)}>Abrir ficha territorial</button></aside></div>}

    {tab==="Equipes de campo"&&<><article className="field-app-banner"><span><Smartphone size={24}/></span><div><p className="eyebrow">APLICATIVO DE CAMPO</p><h3>Registro móvel com funcionamento temporariamente offline</h3><p>Localização, fotos, checklist, horário, materiais, assinatura e observações são sincronizados quando houver conexão.</p></div><span className="offline-badge"><CloudOff size={14}/>Modo offline disponível no protótipo</span><button className="button primary" onClick={()=>setFieldModal(true)}>Nova atividade de campo</button></article><div className="field-team-grid">{profile.teams.map(([team,size,status],index)=><article className="panel" key={team}><header><span>{index+1}</span><i className={toneFor(status)}>{status}</i></header><h3>{team}</h3><p><UsersRound size={14}/>{size}</p><div className="team-progress"><span><i style={{width:`${[74,92,61][index]}%`}}/></span><small>{["3 atividades hoje","Rota atualizada","2 pendências"][index]}</small></div><button onClick={()=>setFieldModal(true)}>Registrar atividade <ArrowRight size={13}/></button></article>)}</div></>}

    {tab==="Metas e indicadores"&&<div className="sector-goals-layout"><article className="panel sector-goals"><header><div><h3>Metas de {department}</h3><p>Responsáveis, resultado atual e prazo de acompanhamento.</p></div><button className="button primary" onClick={()=>notify("Formulário de nova meta setorial aberto para o responsável.")}><Plus size={14}/>Nova meta</button></header>{profile.goals.map(([goal,progress,target],index)=><div className="goal-row" key={goal}><span className="goal-number">{index+1}</span><span><strong>{goal}</strong><small>Responsável: {index===0?userName:profile.teams[index]?.[0]??"Equipe setorial"}</small><i><b style={{width:`${progress}%`}}/></i></span><span><strong>{progress}%</strong><small>{target}</small></span><button onClick={()=>notify(`Detalhamento da meta “${goal}” aberto.`)}><ChevronRight size={14}/></button></div>)}</article><aside className="sector-goal-side"><article className="panel goal-score"><Gauge size={27}/><strong>{Math.round(profile.goals.reduce((sum,item)=>sum+item[1],0)/profile.goals.length)}%</strong><p>execução média das metas</p></article><article className="panel indicator-rules"><h3>Indicadores próprios</h3><p>Os indicadores consideram a natureza do trabalho do setor e não comparam atividades incompatíveis.</p>{profile.metrics.map(item=><span key={item[0]}><Check size={12}/>{item[0]}</span>)}</article></aside></div>}

    {tab==="Encaminhamentos"&&<div className="sector-referral-layout"><article className="panel referral-form"><header><span><HeartHandshake size={20}/></span><div><h3>Encaminhamento controlado</h3><p>Compartilhe apenas as informações necessárias para o atendimento solicitado.</p></div></header><form onSubmit={createReferral}><label><span>Setor de destino *</span><select name="destination" required defaultValue=""><option value="" disabled>Selecione o setor responsável</option>{departments.filter(item=>item!==department).map(item=><option key={item}>{item}</option>)}</select></label><label><span>Assunto do encaminhamento *</span><input name="subject" required placeholder="Descreva o apoio ou serviço solicitado"/></label><label><span>Escopo dos dados compartilhados *</span><select name="scope" required defaultValue="Somente dados necessários"><option>Somente dados necessários</option><option>Informações institucionais</option><option>Documentos selecionados</option><option>Dados pessoais autorizados</option></select></label><label><span>Prazo para retorno</span><input type="date" name="due"/></label><label className="full"><span>Contexto e providência solicitada</span><textarea placeholder="Informe o contexto mínimo para que o outro setor possa atender."/></label><p className="referral-privacy"><ShieldCheck size={14}/><span><strong>Compartilhamento mínimo</strong> O prontuário ou cadastro completo permanece no setor de origem. O destino recebe apenas o conteúdo selecionado.</span></p><button className="button primary"><Send size={14}/>Registrar encaminhamento</button></form></article><aside className="panel referral-list"><header><div><h3>Encaminhamentos recentes</h3><p>Histórico visível ao setor de origem.</p></div><ListChecks size={18}/></header>{referrals.map(([destination,subject,scope],index)=><button key={`${destination}-${index}`} onClick={()=>notify(`Histórico do encaminhamento para ${destination} aberto.`)}><span className="referral-status"><i/></span><span><strong>{subject}</strong><small>{destination} · {scope}</small></span><i>{index===0?"Aguardando retorno":"Recebido"}</i><ChevronRight size={13}/></button>)}</aside></div>}

    {recordModal&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setRecordModal(false)}}><section className="modal sector-modal" role="dialog" aria-modal="true" aria-labelledby="sector-record-modal-title"><header><div><p className="eyebrow">{department.toUpperCase()}</p><h2 id="sector-record-modal-title">{profile.recordDescription}</h2></div><button type="button" aria-label="Fechar" onClick={()=>setRecordModal(false)}><X size={18}/></button></header><form onSubmit={createRecord}><label className="field full"><span>Modelo do formulário</span><select defaultValue={profile.forms[0]}>{profile.forms.map(item=><option key={item}>{item}</option>)}</select></label><label className="field full"><span>{profile.primaryField} *</span><input name="primary" required autoFocus placeholder={`Informe ${profile.primaryField.toLowerCase()}`}/></label><label className="field full"><span>{profile.secondaryField} *</span><input name="secondary" required placeholder={`Informe ${profile.secondaryField.toLowerCase()}`}/></label><label className="field"><span>Prioridade</span><select defaultValue="Normal"><option>Urgente</option><option>Alta</option><option>Normal</option><option>Baixa</option></select></label><label className="field"><span>Responsável</span><input defaultValue={userName}/></label><label className="field full"><span>Descrição e providências</span><textarea name="notes" placeholder="Registre somente as informações necessárias para este atendimento."/></label><p className="sector-modal-privacy"><LockKeyhole size={14}/>{profile.privacy}</p><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setRecordModal(false)}>Cancelar</button><button className="button primary"><ClipboardCheck size={15}/>Cadastrar registro</button></div></form></section></div>}

    {fieldModal&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setFieldModal(false)}}><section className="modal sector-modal" role="dialog" aria-modal="true" aria-labelledby="field-modal-title"><header><div><p className="eyebrow">ATIVIDADE EXTERNA</p><h2 id="field-modal-title">Registro da equipe de campo</h2></div><button type="button" aria-label="Fechar" onClick={()=>setFieldModal(false)}><X size={18}/></button></header><form onSubmit={createFieldRecord}><label className="field"><span>Equipe *</span><select required>{profile.teams.map(item=><option key={item[0]}>{item[0]}</option>)}</select></label><label className="field"><span>Tipo de atividade *</span><select required>{profile.forms.slice(0,4).map(item=><option key={item}>{item}</option>)}</select></label><label className="field full"><span>Localização *</span><input required placeholder="Endereço, comunidade ou ponto de referência"/></label><label className="field"><span>Horário de chegada</span><input type="time"/></label><label className="field"><span>Situação</span><select><option>Em andamento</option><option>Concluída</option><option>Requer retorno</option><option>Impedimento encontrado</option></select></label><fieldset className="field-checklist"><legend>Checklist do registro</legend>{["Localização confirmada","Fotografias registradas","Materiais utilizados informados","Responsável no local identificado"].map((item,index)=><label key={item}><input type="checkbox" defaultChecked={index<2}/><span>{item}</span></label>)}</fieldset><label className="field full"><span>Observações</span><textarea placeholder="Descreva o serviço, os resultados e as pendências."/></label><p className="offline-form-note"><CloudOff size={14}/>Se a conexão cair, este protótipo mantém o preenchimento na tela até o envio ser concluído.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setFieldModal(false)}>Cancelar</button><button className="button primary"><MapPin size={15}/>Registrar atividade</button></div></form></section></div>}
  </section>
}
