'use client';
import {Fragment,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,Check,CheckCheck,ShieldCheck,MapPin,Clock3,Info,Search,UserRound,ClipboardList,ChevronRight,LockKeyhole,ExternalLink,RotateCcw} from 'lucide-react';
import {Header,Footer,CandidatePhoto} from './components';
import {compareCandidates,isFeaturedCandidate,hasFeaturedCandidates} from '@/lib/ballot';
import {localityQuestion} from '@/lib/locality';
import {steps,specialOptions,defaults,normalize,choiceLabel,type Candidate,type SurveySettings} from '@/lib/survey';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function SurveyApp(){
 const [candidates,setCandidates]=useState<Candidate[]>([]),[settings,setSettings]=useState<SurveySettings>(defaults),[loading,setLoading]=useState(true),[error,setError]=useState(''),[token,setToken]=useState(''),[phase,setPhase]=useState<'intro'|'survey'|'review'|'done'>('intro'),[demo,setDemo]=useState(false),[index,setIndex]=useState(0),[localVote,setLocalVote]=useState<'yes'|'no'|''>(''),[consent,setConsent]=useState(false),[privacy,setPrivacy]=useState(false),[choices,setChoices]=useState<Record<string,string>>({}),[search,setSearch]=useState(''),[limit,setLimit]=useState(30),[saving,setSaving]=useState(false);
 const [testMode,setTestMode]=useState(false),[databaseReady,setDatabaseReady]=useState(false),[savedMode,setSavedMode]=useState('real');
 const submitting=useRef(false);
 const load=()=>{setLoading(true);setError('');fetch('/api/survey').then(r=>r.json()).then((d:any)=>{if(d.error)throw Error(d.error);setCandidates(d.candidates);setSettings(d.settings);setTestMode(d.testMode===true);setDatabaseReady(d.databaseReady===true);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setToken(params.get('convite')||'');load();},[]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool||!candidates.length)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'find_candidates',title:'Consultar candidaturas',description:'Consulta os candidatos da mesma base exibida no questionário, sem selecionar ou enviar respostas.',inputSchema:{type:'object',properties:{office:{type:'string',enum:['federal','estadual','senador','governador','presidente']},query:{type:'string',maxLength:100}},required:['office'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const a=input as {office?:string;query?:string};if(!a||!['federal','estadual','senador','governador','presidente'].includes(a.office||'')||(a.query!==undefined&&(typeof a.query!=='string'||a.query.length>100)))throw Error('Cargo ou busca inválidos.');const found=candidates.filter(c=>c.office===a.office&&normalize(c.name+' '+c.number+' '+c.party).includes(normalize(a.query||''))).sort(compareCandidates);return {total:found.length,candidates:found.slice(0,20).map(({id,name,number,party,office,uf})=>({id,name,number,party,office,uf}))};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[candidates]);
 const step=steps[index];const value=choices[step.key]||'';
 const officeCandidates=useMemo(()=>candidates.filter(c=>c.office===step.office).sort(compareCandidates),[candidates,step.office]);
 const filtered=useMemo(()=>officeCandidates.filter(c=>normalize(c.name+' '+c.number+' '+c.party).includes(normalize(search))),[officeCandidates,search]);
 const selected=candidates.find(c=>'candidate:'+c.id===value);
 const parties=Array.from(new Set(officeCandidates.map(c=>c.party))).sort();
 const go=(n:number)=>{setIndex(n);setSearch('');setLimit(30);setError('');setPhase('survey');window.scrollTo({top:0,behavior:'smooth'});};
 function start(isDemo:boolean){if(loading||!candidates.length)return;if(localVote===''){setError('Responda se você vota em Várzea da Palma para continuar.');return;}if(!isDemo&&!consent){setError('Leia e aceite o consentimento para participar.');return;}setDemo(isDemo);setPhase('survey');setError('');window.scrollTo({top:0,behavior:'smooth'});}
 async function submit(){
  if(submitting.current)return;setError('');if(demo){setPhase('done');return;}
  submitting.current=true;setSaving(true);
  try{
   let activeToken=token;
   if(testMode&&!activeToken){const sessionResponse=await fetch('/api/test-session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const session=await sessionResponse.json();if(!sessionResponse.ok)throw Error(session.error||'Não foi possível iniciar o teste.');activeToken=session.token;setToken(activeToken);}
   const r=await fetch('/api/respond',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:activeToken,votesInVarzeaDaPalma:localVote==='yes',choices,consent,consentVersion:settings.consentVersion})});const d=await r.json();if(!r.ok)throw Error(d.error);setSavedMode(d.mode||'real');setPhase('done');setChoices({});
  }catch(e){setError(e instanceof Error?e.message:'Falha ao salvar. Tente novamente.');}finally{submitting.current=false;setSaving(false);}
 }
 const canParticipate=(testMode&&databaseReady)||(settings.status==='open'&&!!token);
 return <div className="app"><Header/><main className="page-shell">
  {testMode&&<div className="test-banner"><Info size={20}/><div><strong>Ambiente de teste</strong><p>{databaseReady?'As respostas enviadas são salvas como teste no painel e não entram nos resultados públicos.':'Conecte o banco de dados para salvar respostas. Por enquanto, você pode conhecer o questionário sem gravar.'}</p></div></div>}
  <div className="page-eyebrow"><span><MapPin size={14}/> MINAS GERAIS</span><span>Eleições 2026</span></div>
  {phase==='intro'?<div className="intro-grid"><section className="intro-story"><div className="section-kicker">PESQUISA DE INTENÇÃO DE VOTO</div><h1>Minas tem voz.<br/><span>A sua também.</span></h1><p className="lead">Compartilhe suas escolhas para o futuro de Minas Gerais e do Brasil.</p><div className="intro-facts"><span><Clock3 size={18}/> Cerca de 3 minutos</span><span><ClipboardList size={18}/> 6 escolhas</span></div><div className="ballot-overview"><div className="overview-heading"><span>O que você vai responder</span><span>01—06</span></div>{steps.map((s,i)=><div key={s.key} className="overview-row"><span className="overview-index">0{i+1}</span><span>{s.label}</span><span className="scope-tag">{s.office==='presidente'?'BRASIL':'MG'}</span></div>)}</div><p className="trust-note"><ShieldCheck size={20}/><span>Sua participação é voluntária. Você pode indicar indecisão ou preferir não responder em qualquer cargo.</span></p></section>
  <section className="start-card"><div className="card-accent"/><div className="card-top-label"><span className="small-icon"><MapPin size={21}/></span><span>SEU PONTO DE PARTIDA</span></div><h2>Vamos começar?</h2><p>Responda à pergunta abaixo para começar.</p>
   {loading?<div className="loading-line" role="status">Carregando candidaturas…</div>:<><h3 className="locality-question" id="locality-question">{localityQuestion}</h3><RadioGroup value={localVote} onValueChange={value=>{if(value==='yes'||value==='no')setLocalVote(value);setError('');}} aria-labelledby="locality-question" className="locality-options"><label className={'locality-option '+(localVote==='yes'?'selected':'')}><RadioGroupItem value="yes"/>Sim</label><label className={'locality-option '+(localVote==='no'?'selected':'')}><RadioGroupItem value="no"/>Não</label></RadioGroup><p className="field-help">Selecione uma opção para continuar.</p>
   {canParticipate?<><label className="check-line consent-line"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>Autorizo o tratamento das minhas respostas, incluindo opinião política, para esta pesquisa. <button className="text-button" onClick={()=>setPrivacy(true)}>Ler consentimento</button></span></label><button className="primary-button full" onClick={()=>start(false)}>{testMode?'Responder teste':'Participar da pesquisa'} <ArrowRight size={19}/></button></>:<><div className="notice"><Info size={18}/><span>{settings.status==='closed'?'A coleta desta pesquisa foi encerrada. Você ainda pode conhecer o questionário.':settings.status==='open'?'Para enviar sua resposta, abra o link individual recebido no convite.':'O questionário está disponível para demonstração. A coleta de respostas ainda não começou.'}</span></div><button className="primary-button full" onClick={()=>start(true)}>Conhecer o questionário <ArrowRight size={19}/></button><p className="button-caption">Na demonstração, nenhuma resposta é gravada.</p></>}
   </>}{error&&<div role="alert" className="error-box">{error}{!candidates.length&&<button onClick={load}>Tentar novamente</button>}</div>}
   <div className="card-bottom"><LockKeyhole size={16}/><span>{testMode?'Respostas de teste com acesso restrito ao painel':'Participação por convite individual'}</span></div><button className="text-button privacy-link" onClick={()=>setPrivacy(true)}>Privacidade e informações da pesquisa <ExternalLink size={13}/></button>
  </section></div>:phase==='done'?<section className="completion panel"><span className="completion-icon"><CheckCheck size={40}/></span><div className="section-kicker">{demo?'DEMONSTRAÇÃO CONCLUÍDA':savedMode==='test'?'TESTE SALVO':'PARTICIPAÇÃO CONCLUÍDA'}</div><h1>{demo?'Você conheceu a pesquisa.':savedMode==='test'?'Seu teste foi salvo.':'Obrigado por participar.'}</h1><p>{demo?'Suas escolhas de demonstração não foram gravadas nem incluídas nos resultados.':savedMode==='test'?'A resposta está disponível na aba Respostas do painel. Ela permanece salva no banco e não será publicada como resultado da pesquisa.':'Sua resposta foi registrada com sucesso. Este convite não poderá ser utilizado novamente.'}</p>{!demo&&savedMode==='test'?<a className="primary-button" href="/painel">Abrir painel <ArrowRight size={18}/></a>:<a className="primary-button" href="/resultados">Acompanhar resultados <ArrowRight size={18}/></a>}<a className="text-button" href="/">Voltar ao início</a></section>:<>
   <div className="survey-heading"><div><div className="section-kicker">{demo?'DEMONSTRAÇÃO · SEM GRAVAÇÃO':testMode?'TESTE · RESPOSTAS SALVAS NO PAINEL':'PESQUISA ELEITORAL 2026'}</div><h1>{phase==='review'?'Revise suas escolhas.':'Cada escolha conta.'}</h1></div><div className="municipality-badge"><MapPin size={16}/>Vota em Várzea da Palma: {localVote==='yes'?'Sim':'Não'}</div></div>
   <div className="question-layout"><aside className="journey"><div className="journey-title">SEU QUESTIONÁRIO</div>{steps.map((s,i)=><button key={s.key} disabled={i>index&&!choices[s.key]} onClick={()=>go(i)} className={'journey-step '+(phase==='survey'&&index===i?'current ':'')+(choices[s.key]?'answered':'')}><span className="step-circle">{choices[s.key]?<Check size={15}/>:i+1}</span><span>{s.short}<small>{s.office==='presidente'?'Candidatura nacional':'Candidaturas de MG'}</small></span>{phase==='survey'&&index===i&&<ChevronRight size={16}/>}</button>)}<div className="journey-tip"><ShieldCheck size={21}/><p>Sem escolha obrigatória de candidato. Sua opinião é respeitada.</p></div></aside>
   <section className="question-card panel">{phase==='review'?<><div className="question-meta"><span>ÚLTIMA ETAPA</span><span>Revisão</span></div><h2>Tudo certo com suas respostas?</h2><p className="muted">Você pode editar qualquer escolha antes de concluir.</p><div className="review-list"><div><span><small>{localityQuestion}</small><strong>{localVote==='yes'?'Sim':'Não'}</strong></span><button className="text-button" onClick={()=>setPhase('intro')}>Editar</button></div>{steps.map((s,i)=><div key={s.key}><span><small>{s.label}</small><strong>{choiceLabel(choices[s.key],candidates)}</strong></span><button className="text-button" onClick={()=>go(i)}>Editar</button></div>)}</div>{error&&<p role="alert" className="error-box">{error}</p>}<div className="question-actions"><button className="secondary-button" onClick={()=>go(5)}><ArrowLeft size={17}/> Voltar</button><button className="primary-button" disabled={saving} onClick={submit}>{saving?'Enviando…':demo?'Concluir demonstração':testMode?'Salvar resposta de teste':'Enviar minhas respostas'}<Check size={18}/></button></div></>:<>
    <div className="question-meta"><span>ESCOLHA {String(index+1).padStart(2,'0')} DE 06</span><span>{Math.round(index/6*100)}% concluído</span></div><Progress value={index/6*100} aria-label="Progresso do questionário"/><div className="question-title"><div><h2>{step.label}</h2><p>Se a eleição fosse hoje, qual seria sua escolha?</p></div><span className="office-scope">{step.office==='presidente'?'BRASIL':'MINAS GERAIS'}</span></div>
    {step.office==='senador'&&<div className="inline-info"><Info size={17}/>{index===3?'Agora escolha outro nome. O candidato da primeira escolha fica indisponível.':'Em 2026, são duas escolhas para o Senado. Comece por um candidato.'}</div>}
    <label className="search-box"><Search size={19}/><input value={search} onChange={e=>{setSearch(e.target.value);setLimit(30);}} placeholder="Buscar por nome, número ou partido" aria-label="Buscar candidatos"/>{search&&<button onClick={()=>setSearch('')} aria-label="Limpar busca">×</button>}</label><div className="list-caption"><span>{filtered.length.toLocaleString('pt-BR')} candidaturas {search?'encontradas':'disponíveis'}</span><span>{hasFeaturedCandidates(step.office)?'Destaques, depois ordem alfabética':'Ordem alfabética'}</span></div>
    {selected&&search&&!filtered.some(c=>c.id===selected.id)&&<div className="selected-notice"><Check size={17}/> Selecionado: {selected.name}</div>}
    <RadioGroup value={value} onValueChange={v=>setChoices(previous=>({...previous,[step.key]:v,...(step.key==='senador1'&&v.startsWith('candidate:')&&previous.senador2===v?{senador2:''}:{})}))} aria-label={step.label} className="choice-group"><div className="candidates-list">{filtered.slice(0,limit).map((c,i)=>{const disabled=step.key==='senador2'&&choices.senador1==='candidate:'+c.id;return <Fragment key={c.id}>{i===0&&isFeaturedCandidate(c)&&<div className="candidate-section-label">NOMES EM DESTAQUE</div>}{hasFeaturedCandidates(step.office)&&!isFeaturedCandidate(c)&&(i===0||isFeaturedCandidate(filtered[i-1]))&&<div className="candidate-section-label">DEMAIS CANDIDATURAS</div>}<label className={'candidate-row '+(value==='candidate:'+c.id?'selected ':'')+(disabled?'unavailable':'')}><RadioGroupItem id={'cand-'+c.id} value={'candidate:'+c.id} disabled={disabled}/><CandidatePhoto src={c.photo} name={c.name}/><span className="candidate-name">{c.name}<small>{c.party}{disabled?' · Já selecionado':''}</small></span><span className="candidate-number">{c.number}</span></label></Fragment>;})}{!filtered.length&&<div className="empty-inline"><Search size={24}/><p>Nenhum candidato encontrado.</p><button className="text-button" onClick={()=>setSearch('')}>Limpar a busca</button></div>}</div>{filtered.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+30)}>Mostrar mais candidatos ({filtered.length-limit} restantes)</button>}
    {['federal','estadual'].includes(step.office)&&<details className="party-details"><summary>Quero escolher apenas um partido (legenda)</summary><div className="party-options">{parties.map(p=><label key={p} className={value==='party:'+p?'selected':''}><RadioGroupItem value={'party:'+p}/>{p}</label>)}</div></details>}
    <div className="alternative-title">OUTRAS RESPOSTAS</div><div className="alternative-options">{specialOptions.map(o=><label key={o.value} className={value===o.value?'selected':''}><RadioGroupItem value={o.value}/>{o.label}</label>)}</div></RadioGroup>
    <div className="question-actions"><button className="secondary-button" onClick={()=>index?go(index-1):setPhase('intro')}><ArrowLeft size={17}/> Voltar</button><button className="primary-button" disabled={!value} onClick={()=>{if(index<5)go(index+1);else{setPhase('review');setError('');window.scrollTo({top:0,behavior:'smooth'});}}}>{index<5?'Próxima escolha':'Revisar respostas'}<ArrowRight size={18}/></button></div>
   </>}</section></div>
  </>}
 </main><Footer/><Dialog open={privacy} onOpenChange={setPrivacy}><DialogContent className="privacy-dialog"><DialogHeader><DialogTitle>Privacidade e informações da pesquisa</DialogTitle><DialogDescription>Leia antes de participar.</DialogDescription></DialogHeader><div className="privacy-content"><h3>Quem realiza a pesquisa</h3><p>{settings.controller||(testMode?'Instalação em teste. O responsável pode cadastrar seus dados no painel.':'Responsável ainda não cadastrado. A coleta permanece fechada.')}</p>{settings.contact&&<p>Contato: {settings.contact}</p>}<h3>Finalidade e dados coletados</h3><p>Medir intenções de voto entre os participantes convidados. São registrados se você vota ou não em Várzea da Palma, respostas sobre preferência política, data de envio, consentimento e um código de convite. Não pedimos nome, CPF ou número de telefone no formulário.</p><h3>Confidencialidade</h3><p>Os resultados públicos são apresentados de forma agregada. O organizador pode relacionar um convite ao destinatário, por isso não prometemos anonimato absoluto. O acesso às respostas é restrito à administração.</p><h3>Seus direitos</h3><p>Você pode desistir antes de enviar. Para solicitar acesso, correção, revogação do consentimento ou exclusão, utilize o contato do responsável e informe seu código de convite. Prazo previsto de conservação: {settings.retentionDays} dias, ressalvadas obrigações legais. A administração é responsável por atender essas solicitações e aplicar a retenção.</p><h3>Metodologia e registro</h3><p>{settings.methodology||(testMode?'Teste de funcionamento: as respostas enviadas ficam no painel, separadas das respostas reais. Não serão divulgadas como pesquisa eleitoral.':'A metodologia está em preparação. A demonstração não gera respostas nem resultados eleitorais.')}</p>{settings.registration&&<p>Registro informado: {settings.registration}</p>}<p className="muted">Consentimento versão {settings.consentVersion}. Site independente, sem vínculo com o TSE.</p></div></DialogContent></Dialog></div>;
}
